clear;
close all;
clc;

%% ============================================================
% STEP 09B-5
% Real forward pilot for expanded paired Monte Carlo study.
%
% One physical k-Wave forward simulation:
%
%   Seed 1
%   fixed canonical three-line source
%   heterogeneous medium
%   attenuation
%   2-MHz / 80% detector response
%   0.20-mm finite receiver aperture
%
% The resulting system-level RF is then reused to construct
% five exactly paired AWGN conditions:
%
%   5, 10, 15, 20, 30 dB
%
% NO reconstruction is performed in this step.
% ============================================================

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

outDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step09_montecarlo');

if ~exist(outDir,'dir')
    mkdir(outDir);
end

sourceFile = fullfile( ...
    outDir, ...
    'canonical_three_line_192x192.mat');

assert(isfile(sourceFile), ...
    'Frozen canonical three-line source not found.');

%% ============================================================
% FROZEN PILOT DESIGN
% ============================================================

baseSeed = ...
    1;

snrLevels_dB = ...
    [5 10 15 20 30];

% Separate deterministic stream for additive-noise pattern.
noiseSeed = ...
    baseSeed + 300000;

%% ============================================================
% LOAD FROZEN SOURCE FOR REFERENCE AUDIT
% ============================================================

P = load( ...
    sourceFile, ...
    'p0', ...
    'meta');

p0Frozen = ...
    double(P.p0);

%% ============================================================
% FORWARD SIMULATION
%
% IMPORTANT:
% Noise is disabled here.
%
% We want one system-level RF realization and will add all
% five paired noise levels ourselves afterwards.
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09B-5: REAL FORWARD PILOT -- SEED 1\n');
fprintf('============================================================\n');

fprintf('Source      : canonical three-line\n');
fprintf('Base seed   : %d\n',baseSeed);
fprintf('Noise seed  : %d\n',noiseSeed);

fprintf('\nRunning one full-physics PATBox/k-Wave simulation...\n');

forwardTimer = tic;

simBase = patSimulate( ...
    sourceFile, ...
    ...
    'SourceModel','initial_pressure_mat', ...
    'InitialPressureVariable','p0', ...
    ...
    'GridSizeX',192, ...
    'GridSizeY',192, ...
    'Dx',50e-6, ...
    'Dy',50e-6, ...
    'CFL',0.20, ...
    'SimulationEndTime',16e-6, ...
    ...
    'PMLSize',20, ...
    'DataCast','single', ...
    'SmoothInitialPressure',false, ...
    ...
    'MinFrequency',0, ...
    'MaxFrequency',6e6, ...
    ...
    'SoundSpeed',1500, ...
    'Density',1000, ...
    'SoundSpeedStd',20, ...
    'DensityStd',15, ...
    'CorrelationLength',0.75e-3, ...
    ...
    'AlphaCoeff',0.75, ...
    'AlphaPower',1.5, ...
    'AlphaMode','full', ...
    ...
    'SensorType','circular', ...
    'SensorModel','kwave_array', ...
    'NumTransducers',128, ...
    'ElementWidth',0.20e-3, ...
    'ElementIntegrationPoints',0, ...
    'SensorRadius',4.20e-3, ...
    'SensorArcDeg',180, ...
    'SensorStartAngleDeg',-90, ...
    'SensorRotationDeg',0, ...
    ...
    'CenterFrequency',2.0e6, ...
    'FractionalBandwidthPercent',80, ...
    ...
    'NoiseModel','none', ...
    ...
    'RandomSeed',baseSeed);

forwardRuntime_s = ...
    toc(forwardTimer);

%% ============================================================
% SIMULATION-RECORD AUDIT
% ============================================================

assert(isfield(simBase,'sensor_data_system'));
assert(isfield(simBase.sensor_data_system,'p'));

assert(isfield(simBase,'sensor_data_clean'));
assert(isfield(simBase.sensor_data_clean,'p'));

assert(isfield(simBase,'p0_reference'));
assert(isfield(simBase,'medium'));
assert(isfield(simBase,'kgrid'));
assert(isfield(simBase,'info'));

pSystem = ...
    double(simBase.sensor_data_system.p);

pClean = ...
    double(simBase.sensor_data_clean.p);

pReference = ...
    double(simBase.p0_reference);

%% ============================================================
% SOURCE CONSISTENCY
% ============================================================

assert( ...
    isequal(size(pReference),size(p0Frozen)), ...
    'PATBox reference source has wrong dimensions.');

sourceRelativeDifference = ...
    norm(pReference(:)-p0Frozen(:)) / ...
    (norm(p0Frozen(:))+eps);

fprintf('\n');
fprintf('SOURCE AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('Frozen/source relative difference = %.12e\n', ...
    sourceRelativeDifference);

assert( ...
    sourceRelativeDifference < 1e-7, ...
    'PATBox source differs from frozen three-line source.');

%% ============================================================
% GRID / TIME AUDIT
% ============================================================

dt = ...
    double(simBase.kgrid.dt);

Nt = ...
    simBase.kgrid.Nt;

fprintf('\n');
fprintf('GRID / TIME AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('Grid              = %d x %d\n', ...
    simBase.kgrid.Nx, ...
    simBase.kgrid.Ny);

fprintf('dx / dy           = %.6f / %.6f um\n', ...
    double(simBase.kgrid.dx)*1e6, ...
    double(simBase.kgrid.dy)*1e6);

fprintf('dt                = %.9f ns\n', ...
    dt*1e9);

fprintf('Nt                = %d\n', ...
    Nt);

fprintf('t_end             = %.9f us\n', ...
    double(simBase.kgrid.t_array(end))*1e6);

assert(simBase.kgrid.Nx==192);
assert(simBase.kgrid.Ny==192);

assert(abs(double(simBase.kgrid.dx)-50e-6)<1e-12);
assert(abs(double(simBase.kgrid.dy)-50e-6)<1e-12);

assert( ...
    abs(double(simBase.kgrid.t_array(end))-16e-6) ...
    < 2*dt);

%% ============================================================
% MEDIUM AUDIT
% ============================================================

cMap = ...
    double(simBase.medium.sound_speed);

rhoMap = ...
    double(simBase.medium.density);

cMean = mean(cMap(:));
cStd  = std(cMap(:));
cMin  = min(cMap(:));
cMax  = max(cMap(:));

rhoMean = mean(rhoMap(:));
rhoStd  = std(rhoMap(:));
rhoMin  = min(rhoMap(:));
rhoMax  = max(rhoMap(:));

cRhoCorr = ...
    corr(cMap(:),rhoMap(:));

fprintf('\n');
fprintf('ACTUAL PATBOX MEDIUM AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('c mean          = %.9f m/s\n',cMean);
fprintf('c std           = %.9f m/s\n',cStd);
fprintf('c min           = %.9f m/s\n',cMin);
fprintf('c max           = %.9f m/s\n',cMax);

fprintf('\n');

fprintf('rho mean        = %.9f kg/m^3\n',rhoMean);
fprintf('rho std         = %.9f kg/m^3\n',rhoStd);
fprintf('rho min         = %.9f kg/m^3\n',rhoMin);
fprintf('rho max         = %.9f kg/m^3\n',rhoMax);

fprintf('\n');

fprintf('corr(c,rho)     = %.9f\n',cRhoCorr);

assert(all(isfinite(cMap(:))));
assert(all(isfinite(rhoMap(:))));

assert(cMin > 100);
assert(rhoMin > 100);

%% ============================================================
% ATTENUATION AUDIT
% ============================================================

fprintf('\n');
fprintf('ATTENUATION AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('alpha coeff      = %.6f\n', ...
    double(simBase.medium.alpha_coeff));

fprintf('alpha power      = %.6f\n', ...
    double(simBase.medium.alpha_power));

assert( ...
    abs(double(simBase.medium.alpha_coeff)-0.75) < 1e-12);

assert( ...
    abs(double(simBase.medium.alpha_power)-1.5) < 1e-12);

%% ============================================================
% SPATIAL-SAMPLING AUDIT
% ============================================================

fMax = ...
    6e6;

ppwAchieved = ...
    min( ...
    cMin/(double(simBase.kgrid.dx)*fMax), ...
    cMin/(double(simBase.kgrid.dy)*fMax));

fprintf('\n');
fprintf('SPATIAL-SAMPLING AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('PPW @ 6 MHz      = %.6f\n', ...
    ppwAchieved);

assert( ...
    ppwAchieved >= 4, ...
    'PPW acceptance criterion failed.');

%% ============================================================
% SENSOR AUDIT
% ============================================================

fprintf('\n');
fprintf('SENSOR AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('Sensor model     = %s\n', ...
    string(simBase.info.sensor_model));

fprintf('Receivers        = %d\n', ...
    simBase.info.num_sensors);

fprintf('Element width    = %.6f mm\n', ...
    double(simBase.info.element_width_m)*1e3);

fprintf('Center frequency = %.6f MHz\n', ...
    double(simBase.info.center_frequency_hz)*1e-6);

fprintf('Fractional BW    = %.6f %%\n', ...
    double(simBase.info.fractional_bandwidth_percent));

if isfield(simBase.info,'aperture_deg')

    fprintf('Recorded aperture = %.6f deg\n', ...
        double(simBase.info.aperture_deg));
end

assert( ...
    strcmpi( ...
    string(simBase.info.sensor_model), ...
    "kwave_array"));

assert(simBase.info.num_sensors==128);

assert( ...
    abs(double(simBase.info.element_width_m)-0.20e-3) ...
    < 1e-12);

assert( ...
    abs(double(simBase.info.center_frequency_hz)-2e6) ...
    < 1);

assert( ...
    abs( ...
    double(simBase.info.fractional_bandwidth_percent)-80) ...
    < 1e-9);

%% ============================================================
% RF AUDIT
% ============================================================

assert(size(pSystem,1)==128);
assert(size(pSystem,2)==Nt);

assert(isequal(size(pSystem),size(pClean)));

systemRMS = ...
    rmsGlobal(pSystem);

cleanRMS = ...
    rmsGlobal(pClean);

cleanSystemRelativeDifference = ...
    norm(pClean(:)-pSystem(:)) / ...
    (norm(pSystem(:))+eps);

fprintf('\n');
fprintf('SYSTEM RF AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('RF dimensions    = %d x %d\n', ...
    size(pSystem,1), ...
    size(pSystem,2));

fprintf('Clean RMS        = %.12e\n', ...
    cleanRMS);

fprintf('System RMS       = %.12e\n', ...
    systemRMS);

fprintf('Clean/system diff= %.12e\n', ...
    cleanSystemRelativeDifference);

assert(systemRMS > 0);
assert(all(isfinite(pSystem(:))));

%% ============================================================
% ONE FROZEN NOISE REALIZATION
% ============================================================

rng(noiseSeed,'twister');

noiseUnit = ...
    randn(size(pSystem));

noiseUnit = ...
    noiseUnit / ...
    rmsGlobal(noiseUnit);

fprintf('\n');
fprintf('PAIRED-NOISE SOURCE\n');
fprintf('------------------------------------------------------------\n');

fprintf('Noise seed        = %d\n',noiseSeed);
fprintf('Noise unit RMS    = %.12f\n', ...
    rmsGlobal(noiseUnit));

assert(abs(rmsGlobal(noiseUnit)-1)<1e-12);

%% ============================================================
% BUILD FIVE PAIRED MEASUREMENTS
% ============================================================

nSNR = ...
    numel(snrLevels_dB);

measuredRF = ...
    cell(nSNR,1);

beta = ...
    nan(nSNR,1);

achievedSNR_dB = ...
    nan(nSNR,1);

normalizedNoise = ...
    cell(nSNR,1);

for s = 1:nSNR

    targetSNR = ...
        snrLevels_dB(s);

    beta(s) = ...
        systemRMS / ...
        10^(targetSNR/20);

    addedNoise = ...
        beta(s) .* ...
        noiseUnit;

    measuredRF{s} = ...
        pSystem + ...
        addedNoise;

    achievedSNR_dB(s) = ...
        20*log10( ...
        systemRMS / ...
        rmsGlobal(addedNoise));

    normalizedNoise{s} = ...
        addedNoise / ...
        rmsGlobal(addedNoise);
end

%% ============================================================
% SNR AUDIT
% ============================================================

fprintf('\n');
fprintf('FIVE-SNR AUDIT\n');
fprintf('------------------------------------------------------------\n');

for s = 1:nSNR

    fprintf( ...
        ['Target %5.1f dB | beta %.12e | ' ...
         'achieved %.12f dB\n'], ...
        snrLevels_dB(s), ...
        beta(s), ...
        achievedSNR_dB(s));
end

snrError = ...
    achievedSNR_dB(:) - ...
    snrLevels_dB(:);

fprintf('\nMaximum |SNR error| = %.12e dB\n', ...
    max(abs(snrError)));

assert( ...
    max(abs(snrError)) < 1e-10, ...
    'Five-SNR calibration failed.');

%% ============================================================
% PAIRING AUDIT ACROSS ALL FIVE SNR LEVELS
% ============================================================

maxPairDifference = ...
    0;

minPairCorrelation = ...
    1;

for i = 1:nSNR

    for j = i+1:nSNR

        ni = ...
            normalizedNoise{i};

        nj = ...
            normalizedNoise{j};

        relativeDifference = ...
            norm(ni(:)-nj(:)) / ...
            (norm(ni(:))+eps);

        pairCorrelation = ...
            corr(ni(:),nj(:));

        maxPairDifference = ...
            max( ...
            maxPairDifference, ...
            relativeDifference);

        minPairCorrelation = ...
            min( ...
            minPairCorrelation, ...
            pairCorrelation);
    end
end

fprintf('\n');
fprintf('FIVE-SNR PAIRING AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('Maximum normalized-noise difference = %.12e\n', ...
    maxPairDifference);

fprintf('Minimum noise correlation           = %.12f\n', ...
    minPairCorrelation);

assert(maxPairDifference < 1e-12);
assert(minPairCorrelation > 1-1e-12);

%% ============================================================
% PILOT SUMMARY TABLE
% ============================================================

pilotTable = table( ...
    repmat(baseSeed,nSNR,1), ...
    repmat(noiseSeed,nSNR,1), ...
    snrLevels_dB(:), ...
    beta, ...
    achievedSNR_dB, ...
    repmat(systemRMS,nSNR,1), ...
    'VariableNames',{ ...
    'BaseSeed', ...
    'NoiseSeed', ...
    'TargetSNR_dB', ...
    'NoiseScale', ...
    'AchievedSNR_dB', ...
    'SystemRMS'});

disp(pilotTable);

%% ============================================================
% SAVE PILOT
%
% Save base simulation only once.
% Five measured RF arrays are stored separately in one cell.
% ============================================================

pilotMeta = struct();

pilotMeta.schema_version = ...
    'revision_mc_forward_pilot_v1';

pilotMeta.base_seed = ...
    baseSeed;

pilotMeta.noise_seed = ...
    noiseSeed;

pilotMeta.snr_levels_dB = ...
    snrLevels_dB;

pilotMeta.forward_runtime_s = ...
    forwardRuntime_s;

pilotMeta.ppw_achieved = ...
    ppwAchieved;

pilotMeta.actual_medium = struct( ...
    'c_mean_mps',cMean, ...
    'c_std_mps',cStd, ...
    'c_min_mps',cMin, ...
    'c_max_mps',cMax, ...
    'rho_mean_kgm3',rhoMean, ...
    'rho_std_kgm3',rhoStd, ...
    'rho_min_kgm3',rhoMin, ...
    'rho_max_kgm3',rhoMax, ...
    'corr_c_rho',cRhoCorr);

pilotFile = fullfile( ...
    outDir, ...
    'montecarlo_forward_pilot_seed001.mat');

save( ...
    pilotFile, ...
    'simBase', ...
    'measuredRF', ...
    'noiseUnit', ...
    'beta', ...
    'achievedSNR_dB', ...
    'pilotTable', ...
    'pilotMeta', ...
    '-v7.3');

writetable( ...
    pilotTable, ...
    fullfile( ...
        outDir, ...
        'montecarlo_forward_pilot_seed001.csv'));

%% ============================================================
% FINAL
% ============================================================

fprintf('\n');
fprintf('Forward runtime = %.2f s\n', ...
    forwardRuntime_s);

fprintf('\nSaved pilot:\n%s\n', ...
    pilotFile);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09B-5 FORWARD PILOT: PASS\n');
fprintf('============================================================\n');

fprintf('Frozen source preserved       : PASS\n');
fprintf('Heterogeneous medium present  : PASS\n');
fprintf('Attenuation                   : PASS\n');
fprintf('Finite receiver aperture      : PASS\n');
fprintf('2-MHz / 80%% response          : PASS\n');
fprintf('PPW >= 4                      : PASS\n');
fprintf('Five target SNRs              : PASS\n');
fprintf('Exact paired noise            : PASS\n');

fprintf('\n');
fprintf('STEP 09B-5 COMPLETE\n');
fprintf('============================================================\n');


%% ============================================================
% LOCAL FUNCTION
% ============================================================

function r = rmsGlobal(x)

    x = double(x);

    r = ...
        sqrt(mean(x(:).^2));

end