clear;
close all;
clc;

%% ============================================================
% PATH SETUP
% =============================================================
patboxRoot = 'C:\Users\asus\Documents\GitHub\PATBox';

addpath(patboxRoot,'-begin');

% Load PATBox subfolders and saved k-Wave path
install_patbox();

fprintf('\nPATBox:\n');
disp(which('patSimulate'));

fprintf('k-Wave:\n');
disp(which('kspaceFirstOrder2D'));

assert(~isempty(which('kspaceFirstOrder2D')), ...
    'k-Wave is not available.');

%% ============================================================
% INPUT SOURCE
% =============================================================
sourceFile = fullfile( ...
    patboxRoot, ...
    'revision', ...
    'outputs', ...
    'step01', ...
    'vascular_phantom_seed101.mat');

assert(isfile(sourceFile), ...
    'Source phantom file was not found.');

fprintf('\nSource file:\n%s\n',sourceFile);

%% ============================================================
% OUTPUT
% =============================================================
outputDir = fullfile( ...
    patboxRoot, ...
    'revision', ...
    'outputs', ...
    'step02');

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

%% ============================================================
% CHECK THAT THIS PATBOX VERSION SUPPORTS OUR PARAMETERS
% =============================================================
cfg = simParameters();

requiredFields = { ...
    'SourceModel', ...
    'SourceMapPath', ...
    'InitialPressureVariable', ...
    'MediumModel', ...
    'GridSizeX', ...
    'GridSizeY', ...
    'Dx', ...
    'Dy', ...
    'SensorType', ...
    'SensorModel'};

for k = 1:numel(requiredFields)

    assert(isfield(cfg,requiredFields{k}), ...
        'Current PATBox does not contain parameter: %s', ...
        requiredFields{k});
end

fprintf('\nPATBox parameter interface check: OK\n');

%% ============================================================
% IDEAL FORWARD SIMULATION
% =============================================================
fprintf('\n=============================================\n');
fprintf('STEP 02A: IDEAL HOMOGENEOUS FORWARD MODEL\n');
fprintf('=============================================\n');

tic;

simIdeal = patSimulate( ...
    sourceFile, ...
    ...
    'SourceModel', ...
        'initial_pressure_mat', ...
    ...
    'SourceMapPath', ...
        sourceFile, ...
    ...
    'InitialPressureVariable', ...
        'p0', ...
    ...
    'SourceScale', ...
        1, ...
    ...
    'SmoothInitialPressure', ...
        false, ...
    ...
    'GridSizeX', ...
        192, ...
    ...
    'GridSizeY', ...
        192, ...
    ...
    'Dx', ...
        50e-6, ...
    ...
    'Dy', ...
        50e-6, ...
    ...
    'PointsPerWavelength', ...
        4, ...
    ...
    'MaxFrequency', ...
        6e6, ...
    ...
    'CFL', ...
        0.2, ...
    ...
    'SimulationEndTime', ...
        16e-6, ...
    ...
    'PMLSize', ...
        20, ...
    ...
    'DataCast', ...
        'single', ...
    ...
    'PlotSimulation', ...
        false, ...
    ...
    'MediumModel', ...
        'homogeneous', ...
    ...
    'SoundSpeed', ...
        1500, ...
    ...
    'Density', ...
        1000, ...
    ...
    'AlphaCoeff', ...
        0, ...
    ...
    'SensorType', ...
        'circular', ...
    ...
    'SensorModel', ...
        'cartesian_point', ...
    ...
    'NumTransducers', ...
        128, ...
    ...
    'SensorRadius', ...
        4.2e-3, ...
    ...
    'ElementWidth', ...
        50e-6, ...
    ...
    'UseDirectivity', ...
        false, ...
    ...
    'CenterFrequency', ...
        0, ...
    ...
    'FractionalBandwidthPercent', ...
        0, ...
    ...
    'NoiseModel', ...
        'none', ...
    ...
    'SensorPositionStd', ...
        0, ...
    ...
    'SensorRadialPositionStd', ...
        0, ...
    ...
    'SensorAngularPositionStdDeg', ...
        0, ...
    ...
    'TimeJitterStd', ...
        0, ...
    ...
    'TriggerJitterStd', ...
        0, ...
    ...
    'RandomSeed', ...
        31);

elapsed = toc;

fprintf('\nSimulation runtime = %.2f s\n',elapsed);