clear;
close all;
clc;

%% ============================================================
% PATHS
% =============================================================
thisFile = mfilename('fullpath');
revisionDir = fileparts(thisFile);
patboxRoot = fileparts(revisionDir);

addpath(patboxRoot);
install_patbox();

outputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step02');

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

sourceFile = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step01', ...
    'vascular_phantom_seed101.mat');

mediumFile = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step01', ...
    'forward_medium_seed31.mat');

assert(isfile(sourceFile), ...
    'Source MAT file not found.');

assert(isfile(mediumFile), ...
    'Medium MAT file not found.');

%% ============================================================
% COMMON SIMULATION PARAMETERS
% =============================================================
commonArgs = { ...

    'SourceModel', ...
        'initial_pressure_mat', ...

    'SourceMapPath', ...
        sourceFile, ...

    'InitialPressureVariable', ...
        'p0', ...

    'SourceScale', ...
        1, ...

    'GridSizeX', ...
        192, ...

    'GridSizeY', ...
        192, ...

    'Dx', ...
        50e-6, ...

    'Dy', ...
        50e-6, ...

    'MaxFrequency', ...
        6e6, ...

    'PointsPerWavelength', ...
        4, ...

    'CFL', ...
        0.2, ...

    'SimulationEndTime', ...
        16e-6, ...

    'PMLSize', ...
        20, ...

    'DataCast', ...
        'single', ...

    'PlotSimulation', ...
        false, ...

    'SmoothInitialPressure', ...
        false, ...

    ... % -------- acquisition geometry --------
    'SensorType', ...
        'circular', ...

    'SensorModel', ...
        'cartesian_point', ...

    'NumTransducers', ...
        128, ...

    'SensorRadius', ...
        4.2e-3, ...

    'ElementWidth', ...
        50e-6, ...

    'UseDirectivity', ...
        false, ...

    ... % -------- ideal broadband detector --------
    'CenterFrequency', ...
        0, ...

    'FractionalBandwidthPercent', ...
        0, ...

    ... % -------- no acquisition noise --------
    'NoiseModel', ...
        'none', ...

    'TargetSNRdB', ...
        30, ...

    ... % no geometry errors
    'SensorPositionStd', ...
        0, ...

    'SensorRadialPositionStd', ...
        0, ...

    'SensorAngularPositionStdDeg', ...
        0, ...

    'TimeJitterStd', ...
        0, ...

    'TriggerJitterStd', ...
        0, ...

    'RandomSeed', ...
        31 ...
    };

%% ============================================================
% IDEAL HOMOGENEOUS FORWARD SIMULATION
% =============================================================
fprintf('\n=============================================\n');
fprintf('STEP 02A: IDEAL FORWARD SIMULATION\n');
fprintf('=============================================\n');

tStart = tic;

simIdeal = patSimulate( ...
    sourceFile, ...
    commonArgs{:}, ...
    'MediumModel','homogeneous', ...
    'SoundSpeed',1500, ...
    'Density',1000, ...
    'AlphaCoeff',0);

elapsedIdeal = toc(tStart);

%% ============================================================
% BASIC AUDIT
% =============================================================
rfIdeal = double(simIdeal.sensor_data.p);
rfClean = double(simIdeal.sensor_data_clean.p);

fprintf('\nSimulation completed.\n');
fprintf('Runtime           : %.2f s\n',elapsedIdeal);

fprintf('RF dimensions      : %d x %d\n', ...
    size(rfIdeal,1), ...
    size(rfIdeal,2));

fprintf('Number receivers   : %d\n', ...
    simIdeal.info.num_sensors);

fprintf('dt                 : %.4g s\n', ...
    simIdeal.kgrid.dt);

fprintf('Nt                 : %d\n', ...
    simIdeal.kgrid.Nt);

fprintf('Max |RF|           : %.6g\n', ...
    max(abs(rfIdeal(:))));

fprintf('Finite RF fraction : %.6f\n', ...
    mean(isfinite(rfIdeal(:))));

fprintf('Clean/measured diff: %.6g\n', ...
    norm(rfIdeal(:)-rfClean(:)) / ...
    (norm(rfClean(:))+eps));

assert(size(rfIdeal,1)==128, ...
    'Unexpected number of RF channels.');

assert(all(isfinite(rfIdeal(:))), ...
    'RF contains NaN or Inf.');

assert(any(abs(rfIdeal(:))>0), ...
    'RF data are identically zero.');

%% ============================================================
% VISUAL RF CHECK
% =============================================================
time_us = ...
    double(simIdeal.kgrid.t_array(:)) * 1e6;

figure( ...
    'Color','w', ...
    'Position',[100 100 1250 440]);

imagesc( ...
    time_us, ...
    1:size(rfIdeal,1), ...
    rfIdeal);

axis xy;

xlabel('Time [\mus]');
ylabel('Receiver channel');

title( ...
    'Ideal homogeneous full-view RF data');

colorbar;

figPath = fullfile( ...
    outputDir, ...
    'step02a_ideal_rf.png');

exportgraphics( ...
    gcf, ...
    figPath, ...
    'Resolution',300);

%% ============================================================
% SAVE COMPLETE SIMULATION RECORD
% =============================================================
save( ...
    fullfile(outputDir,'sim_ideal.mat'), ...
    'simIdeal', ...
    'elapsedIdeal', ...
    '-v7.3');

fprintf('\nSaved:\n%s\n',outputDir);

fprintf('\n=============================================\n');
fprintf('STEP 02A COMPLETE\n');
fprintf('=============================================\n');