clear;
close all;
clc;

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

phantomDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step08_morphology_suite', ...
    'phantoms');

outputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step08_generalization_forward');

simDir = ...
    fullfile(outputDir,'simulations');

if ~exist(simDir,'dir')
    mkdir(simDir);
end

%% ============================================================
% LOAD MEDIUM DESIGN
% ============================================================

mediumDesignFile = fullfile( ...
    outputDir, ...
    'generalization_medium_design.mat');

assert(isfile(mediumDesignFile), ...
    ['Run revision_step08B_prepare_media first.']);

M = load( ...
    mediumDesignFile, ...
    'media', ...
    'CFL', ...
    'dtTarget');

media = M.media;
CFL = M.CFL;
dtTarget = M.dtTarget;

%% ============================================================
% SOURCE DEFINITIONS
% ============================================================

families = [ ...
    "sparse", ...
    "dense", ...
    "cluttered", ...
    "fluence"];

replicateSeeds = [ ...
    101, ...
    202, ...
    303];

nReplicates = ...
    numel(replicateSeeds);

nFamilies = ...
    numel(families);

%% ============================================================
% ACQUISITIONS
% ============================================================

configs = ...
    generalizationAcquisitionConfigs();

nConfigs = ...
    numel(configs);

%% ============================================================
% TOTAL
% ============================================================

nTotal = ...
    nReplicates * ...
    nFamilies * ...
    nConfigs;

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 08B-2: GENERALIZATION FORWARD STUDY\n');
fprintf('============================================================\n');

fprintf('Replicates     = %d\n',nReplicates);
fprintf('Morphologies   = %d\n',nFamilies);
fprintf('Acquisitions   = %d\n',nConfigs);
fprintf('Total forwards = %d\n',nTotal);

%% ============================================================
% SUMMARY STORAGE
% ============================================================

summaryRows = [];

runCounter = 0;

%% ============================================================
% LOOP
% ============================================================

for r = 1:nReplicates

    mediumFile = ...
        media{r}.file;

    assert(isfile(mediumFile), ...
        'Missing medium file.');

    for a = 1:nConfigs

        cfgA = configs(a);

        % ------------------------------------------------------
        % SAME noise seed for all four morphology families
        % within this replicate/configuration pair.
        % ------------------------------------------------------

        noiseSeed = ...
            700000 + ...
            1000*r + ...
            10*a;

        for f = 1:nFamilies

            runCounter = ...
                runCounter + 1;

            sourceFile = fullfile( ...
                phantomDir, ...
                sprintf( ...
                'R%d_%s_seed%d.mat', ...
                r, ...
                char(families(f)), ...
                replicateSeeds(r)));

            assert(isfile(sourceFile), ...
                'Missing source: %s',sourceFile);

            fprintf('\n');
            fprintf('------------------------------------------------------------\n');

            fprintf( ...
                'Run %d/%d | R%d | %s | %s\n', ...
                runCounter, ...
                nTotal, ...
                r, ...
                families(f), ...
                cfgA.Id);

            fprintf('------------------------------------------------------------\n');

            %% =================================================
            % FORWARD SIMULATION
            % ==================================================

            tStart = tic;

            sim = patSimulate( ...
                sourceFile, ...
                ...
                'SourceModel','initial_pressure_mat', ...
                'SourceMapPath',sourceFile, ...
                'InitialPressureVariable','p0', ...
                'SourceScale',1, ...
                'SmoothInitialPressure',false, ...
                ...
                'GridSizeX',192, ...
                'GridSizeY',192, ...
                'Dx',50e-6, ...
                'Dy',50e-6, ...
                'PointsPerWavelength',4, ...
                'MaxFrequency',6e6, ...
                ...
                'CFL',CFL(r), ...
                'SimulationEndTime',16e-6, ...
                'PMLSize',20, ...
                'DataCast','single', ...
                'PlotSimulation',false, ...
                ...
                'MediumModel','mat', ...
                'MediumMapPath',mediumFile, ...
                ...
                'AlphaCoeff',0.75, ...
                'AlphaPower',1.5, ...
                'AlphaMode','full', ...
                ...
                'SensorType','circular', ...
                'SensorModel','kwave_array', ...
                'NumTransducers', ...
                    cfgA.NumTransducers, ...
                'SensorRadius',4.2e-3, ...
                'ElementWidth',0.20e-3, ...
                ...
                'CenterFrequency', ...
                    cfgA.CenterFrequency, ...
                ...
                'FractionalBandwidthPercent', ...
                    cfgA.FractionalBandwidthPercent, ...
                ...
                'UseDirectivity',false, ...
                ...
                'NoiseModel','awgn', ...
                'NoiseScaling','global', ...
                'NoiseCalibrationMode','target_snr', ...
                'TargetSNRdB',20, ...
                ...
                'SensorPositionStd',0, ...
                'SensorRadialPositionStd',0, ...
                'SensorAngularPositionStdDeg',0, ...
                'TimeJitterStd',0, ...
                'TriggerJitterStd',0, ...
                ...
                'RandomSeed',noiseSeed);

            elapsed = ...
                toc(tStart);

            %% =================================================
            % AUDIT
            % ==================================================

            rf = ...
                double(sim.sensor_data.p);

            assert( ...
                size(rf,1) == ...
                cfgA.NumTransducers, ...
                'Channel-count mismatch.');

            assert(all(isfinite(rf(:))), ...
                'Non-finite RF data.');

            achievedSNR = ...
                sim.info.acquisition. ...
                achieved_additive_snr_db;

            assert( ...
                abs(achievedSNR-20) < 0.05, ...
                'Achieved SNR differs from target.');

            currentDt = ...
                double(sim.kgrid.dt);

            relativeDtError = ...
                abs(currentDt-dtTarget) / ...
                dtTarget;

            assert(relativeDtError < 1e-6, ...
                'Common time sampling was not preserved.');

            if isfield( ...
                    sim.info, ...
                    'aperture_audit')

                assert( ...
                    sim.info.aperture_audit.inside, ...
                    'Source outside receiver aperture.');
            end

            %% =================================================
            % SAVE
            % ==================================================

            outputName = ...
                sprintf( ...
                'R%d_%s_%s.mat', ...
                r, ...
                char(families(f)), ...
                cfgA.Id);

            save( ...
                fullfile( ...
                    simDir, ...
                    outputName), ...
                'sim', ...
                'elapsed', ...
                '-v7.3');

            %% =================================================
            % SUMMARY
            % ==================================================

            rfRMS = ...
                sqrt(mean(rf(:).^2));

            newRow = table( ...
                r, ...
                replicateSeeds(r), ...
                families(f), ...
                string(cfgA.Id), ...
                string(cfgA.Label), ...
                cfgA.NumTransducers, ...
                cfgA.CenterFrequency/1e6, ...
                cfgA.FractionalBandwidthPercent, ...
                CFL(r), ...
                currentDt*1e9, ...
                sim.kgrid.Nt, ...
                achievedSNR, ...
                rfRMS, ...
                elapsed, ...
                noiseSeed, ...
                'VariableNames',{ ...
                'Replicate', ...
                'MorphologySeed', ...
                'Family', ...
                'Acquisition', ...
                'AcquisitionLabel', ...
                'Channels', ...
                'CenterFrequency_MHz', ...
                'FractionalBandwidth_percent', ...
                'CFL', ...
                'dt_ns', ...
                'Nt', ...
                'AchievedSNR_dB', ...
                'MeasuredRF_RMS', ...
                'ForwardRuntime_s', ...
                'NoiseSeed'});

            summaryRows = ...
                [summaryRows;newRow]; %#ok<AGROW>

            fprintf('Runtime       = %.2f s\n',elapsed);
            fprintf('Channels      = %d\n',size(rf,1));
            fprintf('dt            = %.9f ns\n', ...
                currentDt*1e9);
            fprintf('Nt            = %d\n',sim.kgrid.Nt);
            fprintf('Achieved SNR  = %.4f dB\n', ...
                achievedSNR);
            fprintf('RF RMS        = %.6e\n',rfRMS);

        end
    end
end

%% ============================================================
% FINAL AUDITS
% ============================================================

assert(height(summaryRows)==36, ...
    'Expected 36 forward simulations.');

%% ------------------------------------------------------------
% Temporal consistency
% ------------------------------------------------------------

relativeDtSpread = ...
    ( ...
    max(summaryRows.dt_ns) - ...
    min(summaryRows.dt_ns) ...
    ) / ...
    mean(summaryRows.dt_ns);

fprintf('\n');
fprintf('============================================================\n');
fprintf('GENERALIZATION FORWARD AUDIT\n');
fprintf('============================================================\n');

fprintf('Completed simulations = %d\n', ...
    height(summaryRows));

fprintf('Relative dt spread    = %.6e\n', ...
    relativeDtSpread);

fprintf('SNR min/max           = %.6f / %.6f dB\n', ...
    min(summaryRows.AchievedSNR_dB), ...
    max(summaryRows.AchievedSNR_dB));

assert(relativeDtSpread < 1e-6);

%% ============================================================
% SAVE SUMMARY
% ============================================================

writetable( ...
    summaryRows, ...
    fullfile( ...
        outputDir, ...
        'generalization_forward_summary.csv'));

save( ...
    fullfile( ...
        outputDir, ...
        'generalization_forward_summary.mat'), ...
    'summaryRows', ...
    'configs', ...
    '-v7.3');

disp(summaryRows);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 08B-2 COMPLETE\n');
fprintf('============================================================\n');