clear;
close all;
clc;

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

outputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step08_morphology_suite');

phantomDir = ...
    fullfile(outputDir,'phantoms');

if ~exist(phantomDir,'dir')
    mkdir(phantomDir);
end

%% ============================================================
% COMMON GRID
% ============================================================

Nx = 192;
Ny = 192;

dx = 50e-6;
dy = 50e-6;

kgrid = ...
    kWaveGrid(Nx,dx,Ny,dy);

%% ============================================================
% SUITE
% ============================================================

families = [ ...
    "sparse", ...
    "dense", ...
    "cluttered", ...
    "fluence"];

familyDisplay = { ...
    'Sparse vascular', ...
    'Dense vascular', ...
    'Dense + clutter', ...
    'Dense + fluence'};

% Three independent vascular realizations.
replicateSeeds = [ ...
    101, ...
    202, ...
    303];

nFamilies = numel(families);
nReplicates = numel(replicateSeeds);

%% ============================================================
% STORAGE
% ============================================================

suiteRows = [];

phantoms = cell( ...
    nReplicates, ...
    nFamilies);

componentsAll = cell( ...
    nReplicates, ...
    nFamilies);

metaAll = cell( ...
    nReplicates, ...
    nFamilies);

%% ============================================================
% GENERATE
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 08A: MORPHOLOGY GENERALIZATION SUITE\n');
fprintf('============================================================\n');

for r = 1:nReplicates

    fprintf('\n');
    fprintf('------------------------------------------------------------\n');
    fprintf('Replicate %d | base seed %d\n', ...
        r,replicateSeeds(r));
    fprintf('------------------------------------------------------------\n');

    denseReferenceVessel = [];

    for f = 1:nFamilies

        cfg = struct();

        cfg.family = ...
            families(f);

        cfg.randomSeed = ...
            replicateSeeds(r);

        cfg.peakPressurePa = ...
            1;

        cfg.nClutterRange = ...
            [14 22];

        cfg.fluenceMuEff_mmInv = ...
            0.25;

        cfg.fluenceFloor = ...
            0.25;

        [p0,components,meta] = ...
            makeMorphologyGeneralizationPhantom( ...
            kgrid,cfg);

        phantoms{r,f} = p0;
        componentsAll{r,f} = components;
        metaAll{r,f} = meta;

        %% -----------------------------------------------------
        % Paired-geometry audit
        % ------------------------------------------------------

        if families(f) == "dense"

            denseReferenceVessel = ...
                components.vessel_map;

        elseif ...
                families(f) == "cluttered" || ...
                families(f) == "fluence"

            assert(~isempty(denseReferenceVessel), ...
                'Dense family must be generated first.');

            geometryDifference = ...
                norm( ...
                double( ...
                components.vessel_map(:) - ...
                denseReferenceVessel(:))) / ...
                ( ...
                norm( ...
                double( ...
                denseReferenceVessel(:))) + ...
                eps);

            assert(geometryDifference < 1e-12, ...
                ['Dense / clutter / fluence vessel ' ...
                 'geometry mismatch.']);

        end

        %% -----------------------------------------------------
        % Save
        % ------------------------------------------------------

        fileName = sprintf( ...
            'R%d_%s_seed%d.mat', ...
            r, ...
            char(families(f)), ...
            replicateSeeds(r));

        save( ...
            fullfile(phantomDir,fileName), ...
            'p0', ...
            'components', ...
            'meta', ...
            '-v7.3');

        %% -----------------------------------------------------
        % Summary
        % ------------------------------------------------------

        p0RMS = ...
            sqrt(mean(double(p0(:)).^2));

        vesselFraction = ...
            meta.vesselSupportFraction;

        clutterFraction = ...
            meta.clutterSupportFraction;

        newRow = table( ...
            r, ...
            replicateSeeds(r), ...
            families(f), ...
            meta.segmentCount, ...
            meta.branchPointCount, ...
            meta.terminalPointCount, ...
            p0RMS, ...
            vesselFraction, ...
            clutterFraction, ...
            meta.fluenceMinOnVessels, ...
            meta.fluenceMeanOnVessels, ...
            meta.fluenceMaxOnVessels, ...
            'VariableNames',{ ...
            'Replicate', ...
            'Seed', ...
            'Family', ...
            'Segments', ...
            'BranchPoints', ...
            'TerminalPoints', ...
            'P0_RMS', ...
            'VesselSupportFraction', ...
            'ClutterSupportFraction', ...
            'FluenceMinOnVessels', ...
            'FluenceMeanOnVessels', ...
            'FluenceMaxOnVessels'});

        suiteRows = ...
            [suiteRows;newRow]; %#ok<AGROW>

        fprintf( ...
            '%-12s | segments %3d | branches %3d | terminals %3d | p0 RMS %.4f\n', ...
            families(f), ...
            meta.segmentCount, ...
            meta.branchPointCount, ...
            meta.terminalPointCount, ...
            p0RMS);
    end

    fprintf('Dense/clutter/fluence geometry pairing: PASS\n');
end

%% ============================================================
% SAVE SUMMARY
% ============================================================

summaryFile = fullfile( ...
    outputDir, ...
    'morphology_suite_summary.csv');

writetable( ...
    suiteRows, ...
    summaryFile);

disp(suiteRows);

%% ============================================================
% FIGURE 1:
% ALL 12 PHANTOMS
% ============================================================

fig1 = figure( ...
    'Color','w', ...
    'Position',[30 30 1500 1030]);

tl = tiledlayout( ...
    fig1, ...
    nReplicates, ...
    nFamilies, ...
    'TileSpacing','compact', ...
    'Padding','compact');

for r = 1:nReplicates

    for f = 1:nFamilies

        ax = nexttile(tl);

        imagesc( ...
            ax, ...
            1e3*double(kgrid.y_vec), ...
            1e3*double(kgrid.x_vec), ...
            phantoms{r,f});

        axis(ax,'image');

        set(ax,'YDir','normal');

        clim(ax,[0 1]);

        xlabel(ax,'y [mm]');
        ylabel(ax,'x [mm]');

        title( ...
            ax, ...
            sprintf( ...
            'R%d: %s', ...
            r, ...
            familyDisplay{f}), ...
            'FontWeight','bold');

        ax.FontSize = 9;
    end
end

title( ...
    tl, ...
    'Morphology-generalization phantom suite', ...
    'FontSize',16, ...
    'FontWeight','bold');

cb = colorbar;
cb.Layout.Tile = 'east';
ylabel(cb,'Normalized initial pressure');

exportgraphics( ...
    fig1, ...
    fullfile( ...
        outputDir, ...
        'morphology_suite_12_phantoms.png'), ...
    'Resolution',300);

%% ============================================================
% FIGURE 2:
% REPRESENTATIVE TASK DECOMPOSITION
% ============================================================

r = 1;

denseP0 = ...
    phantoms{r,2};

clutterP0 = ...
    phantoms{r,3};

fluenceP0 = ...
    phantoms{r,4};

fluenceMap = ...
    componentsAll{r,4}.fluence_map;

fig2 = figure( ...
    'Color','w', ...
    'Position',[50 80 1500 420]);

tl2 = tiledlayout( ...
    fig2, ...
    1,4, ...
    'TileSpacing','compact', ...
    'Padding','compact');

ax = nexttile(tl2);

imagesc( ...
    ax, ...
    1e3*double(kgrid.y_vec), ...
    1e3*double(kgrid.x_vec), ...
    denseP0);

axis(ax,'image');
set(ax,'YDir','normal');
clim(ax,[0 1]);

title(ax,'Dense vascular');
xlabel(ax,'y [mm]');
ylabel(ax,'x [mm]');


ax = nexttile(tl2);

imagesc( ...
    ax, ...
    1e3*double(kgrid.y_vec), ...
    1e3*double(kgrid.x_vec), ...
    clutterP0);

axis(ax,'image');
set(ax,'YDir','normal');
clim(ax,[0 1]);

title(ax,'Same vessels + clutter');
xlabel(ax,'y [mm]');
ylabel(ax,'x [mm]');


ax = nexttile(tl2);

imagesc( ...
    ax, ...
    1e3*double(kgrid.y_vec), ...
    1e3*double(kgrid.x_vec), ...
    fluenceMap);

axis(ax,'image');
set(ax,'YDir','normal');
clim(ax,[0 1]);

title(ax,'Controlled fluence surrogate');
xlabel(ax,'y [mm]');
ylabel(ax,'x [mm]');


ax = nexttile(tl2);

imagesc( ...
    ax, ...
    1e3*double(kgrid.y_vec), ...
    1e3*double(kgrid.x_vec), ...
    fluenceP0);

axis(ax,'image');
set(ax,'YDir','normal');
clim(ax,[0 1]);

title(ax,'Same vessels \times fluence');
xlabel(ax,'y [mm]');
ylabel(ax,'x [mm]');

title( ...
    tl2, ...
    'Controlled task modifications using identical vascular geometry', ...
    'FontSize',15, ...
    'FontWeight','bold');

exportgraphics( ...
    fig2, ...
    fullfile( ...
        outputDir, ...
        'morphology_task_decomposition.png'), ...
    'Resolution',300);

%% ============================================================
% SAVE SUITE WORKSPACE
% ============================================================

save( ...
    fullfile( ...
        outputDir, ...
        'morphology_suite_workspace.mat'), ...
    'suiteRows', ...
    'families', ...
    'replicateSeeds', ...
    'metaAll', ...
    '-v7.3');

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 08A COMPLETE\n');
fprintf('============================================================\n');

fprintf('\nOutputs:\n%s\n',outputDir);