clear;
close all;
clc;

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

%% ============================================================
% LOAD D0
% ============================================================

inputFile = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step03_sequential_forward', ...
    'D0_ideal.mat');

S = load(inputFile,'sim');

sim = S.sim;

%% ============================================================
% BEAMFORM
% ============================================================

[recons,bfInfo] = ...
    publicationBeamformers( ...
    sim, ...
    'SoundSpeed',1500, ...
    'Interpolation','linear', ...
    'CFPower',1.0, ...
    'SCFPower',1.5);

%% ============================================================
% EVALUATE
% ============================================================

pRef = double(sim.p0_reference);

names = { ...
    'DAS', ...
    'CFDAS', ...
    'SCFDAS', ...
    'DMAS', ...
    'DSDMAS'};

nMethods = numel(names);

metrics = cell(nMethods,1);

for k = 1:nMethods

    metrics{k} = ...
        publicationEvaluate( ...
        recons.(names{k}), ...
        pRef);
end

%% ============================================================
% TABLE
% ============================================================

Method = strings(nMethods,1);

SI_NRMSE = zeros(nMethods,1);
Correlation = zeros(nMethods,1);
SSIM = zeros(nMethods,1);
CNR = zeros(nMethods,1);
SBR_dB = zeros(nMethods,1);

ScaleFactor = zeros(nMethods,1);
BackgroundRMS = zeros(nMethods,1);

for k = 1:nMethods

    Method(k) = string(names{k});

    SI_NRMSE(k) = ...
        metrics{k}.si_nrmse;

    Correlation(k) = ...
        metrics{k}.correlation;

    SSIM(k) = ...
        metrics{k}.ssim;

    CNR(k) = ...
        metrics{k}.cnr;

    SBR_dB(k) = ...
        metrics{k}.sbr_db;

    ScaleFactor(k) = ...
        metrics{k}.scale_factor;

    BackgroundRMS(k) = ...
        metrics{k}.background_rms;
end

T = table( ...
    Method, ...
    SI_NRMSE, ...
    Correlation, ...
    SSIM, ...
    CNR, ...
    SBR_dB, ...
    ScaleFactor, ...
    BackgroundRMS);

fprintf('\n');
fprintf('=============================================\n');
fprintf('D0 PUBLICATION BEAMFORMER METRICS\n');
fprintf('=============================================\n');

disp(T);

%% ============================================================
% COMMON-SCALE VISUALIZATION
% ============================================================

refPeak = max(abs(pRef(:)));

figure( ...
    'Color','w', ...
    'Position',[60 60 1550 900]);

subplot(2,3,1);

imagesc( ...
    1e3*double(sim.kgrid.y_vec), ...
    1e3*double(sim.kgrid.x_vec), ...
    pRef);

axis image;
set(gca,'YDir','normal');

title('Reference');

clim([-0.1 1]*refPeak);

xlabel('y [mm]');
ylabel('x [mm]');

for k = 1:nMethods

    subplot(2,3,k+1);

    pAligned = ...
        metrics{k}.scale_factor .* ...
        double(recons.(names{k}));

    imagesc( ...
        1e3*double(sim.kgrid.y_vec), ...
        1e3*double(sim.kgrid.x_vec), ...
        pAligned);

    axis image;
    set(gca,'YDir','normal');

    clim([-0.1 1]*refPeak);

    xlabel('y [mm]');
    ylabel('x [mm]');

    title(sprintf( ...
        '%s | SSIM %.3f', ...
        names{k}, ...
        metrics{k}.ssim));
end

sgtitle( ...
    'D0 ideal acquisition: audited publication beamformers');

%% ============================================================
% SAVE
% ============================================================

outputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step05_beamformer_validation');

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

exportgraphics( ...
    gcf, ...
    fullfile( ...
        outputDir, ...
        'D0_publication_beamformers.png'), ...
    'Resolution',300);

writetable( ...
    T, ...
    fullfile( ...
        outputDir, ...
        'D0_publication_beamformer_metrics.csv'));

save( ...
    fullfile( ...
        outputDir, ...
        'D0_publication_beamformer_validation.mat'), ...
    'recons', ...
    'metrics', ...
    'bfInfo', ...
    'T', ...
    '-v7.3');

fprintf('\n=============================================\n');
fprintf('STEP 05B COMPLETE\n');
fprintf('=============================================\n');