clear;
close all;
clc;

%% ============================================================
% STEP 09D-2
% PUBLICATION FIGURES AND TABLES
%
% IMPORTANT:
% This script performs NO new inferential statistics.
%
% It only reads the frozen outputs from STEP 09D-1 and creates:
%
% MAIN:
%   1) Ranking-stability figure
%   2) Compact five-row Monte Carlo statistical table
%
% SUPPLEMENT:
%   3) Kendall-W / winner heatmap
%   4) Selected rank-biserial effect-size heatmaps
%   5) Full 25-family Friedman table
%   6) Selected pairwise-effect table
%
% Input statistics are NOT recomputed.
% ============================================================

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

statsDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step09_montecarlo', ...
    'statistics');

outDir = fullfile( ...
    statsDir, ...
    'publication_outputs');

if ~exist(outDir,'dir')
    mkdir(outDir);
end

%% ============================================================
% FROZEN INPUT FILES
% ============================================================

omnibusFile = fullfile( ...
    statsDir, ...
    'friedman_omnibus_25.csv');

pairwiseFile = fullfile( ...
    statsDir, ...
    'wilcoxon_pairwise_375.csv');

stabilityFile = fullfile( ...
    statsDir, ...
    'rank_stability_125.csv');

checkpointFile = fullfile( ...
    statsDir, ...
    'rank_stability_checkpoint_summary.csv');

assert(isfile(omnibusFile), ...
    'Missing Friedman omnibus table.');

assert(isfile(pairwiseFile), ...
    'Missing Wilcoxon pairwise table.');

assert(isfile(stabilityFile), ...
    'Missing rank-stability table.');

assert(isfile(checkpointFile), ...
    'Missing checkpoint-summary table.');

%% ============================================================
% LOAD FROZEN STATISTICAL OUTPUTS
% ============================================================

O = readtable( ...
    omnibusFile, ...
    'TextType','string');

P = readtable( ...
    pairwiseFile, ...
    'TextType','string');

R = readtable( ...
    stabilityFile, ...
    'TextType','string');

C = readtable( ...
    checkpointFile, ...
    'TextType','string');

%% ============================================================
% BASIC AUDIT
% ============================================================

assert(height(O)==25, ...
    'Expected 25 Friedman families.');

assert(height(P)==375, ...
    'Expected 375 pairwise comparisons.');

assert(height(R)==125, ...
    'Expected 125 rank-stability rows.');

assert(height(C)==5, ...
    'Expected five sample-size checkpoints.');

assert(all(O.Significant_Holm25), ...
    'Not all frozen omnibus tests passed Holm-25.');

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09D-2: PUBLICATION OUTPUT GENERATION\n');
fprintf('============================================================\n');

fprintf('Friedman families       = %d\n',height(O));
fprintf('Pairwise comparisons    = %d\n',height(P));
fprintf('Rank-stability rows     = %d\n',height(R));
fprintf('Checkpoints             = %d\n',height(C));

%% ============================================================
% FROZEN DISPLAY ORDER
% ============================================================

snrLevels = ...
    [5 10 15 20 30];

metricOrder = [ ...
    "SI-NRMSE", ...
    "Correlation", ...
    "SSIM", ...
    "CNR", ...
    "SBR"];

%% ============================================================
% FIGURE 1
% MAIN-PAPER RANKING-STABILITY FIGURE
%
% Panel A:
% Mean Spearman correlation to final N=50 ranking.
% Vertical extent = minimum--maximum across 25 families.
%
% Panel B:
% Fraction of families with same winning method as N=50.
%
% Panel C:
% Maximum absolute mean-rank shift from final N=50 ranking.
%
% These values are already present in the frozen checkpoint
% summary. No ranking is recomputed here.
% ============================================================

fprintf('\nCreating main ranking-stability figure...\n');

N = ...
    double(C.N);

meanRho = ...
    double(C.MeanSpearmanToN50);

minRho = ...
    double(C.MinimumSpearmanToN50);

maxRho = ...
    double(C.MaximumSpearmanToN50);

winnerFraction = ...
    double(C.WinnerMatchCount) ./ ...
    double(C.NumberOfFamilies);

meanRankShift = ...
    double(C.MeanMaxAbsRankShift);

worstRankShift = ...
    double(C.WorstMaxAbsRankShift);

fig1 = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[80 80 1500 470]);

tl = tiledlayout( ...
    fig1, ...
    1,3, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% ------------------------------------------------------------
% PANEL A
% ------------------------------------------------------------

ax1 = nexttile(tl,1);

hold(ax1,'on');

xBand = ...
    [N;flipud(N)];

yBand = ...
    [minRho;flipud(maxRho)];

fill( ...
    ax1, ...
    xBand, ...
    yBand, ...
    [0.85 0.85 0.85], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.65);

plot( ...
    ax1, ...
    N, ...
    meanRho, ...
    '-o', ...
    'LineWidth',1.8, ...
    'MarkerSize',6, ...
    'MarkerFaceColor','w');

plot( ...
    ax1, ...
    N, ...
    ones(size(N)), ...
    '--', ...
    'LineWidth',1.0);

xlabel(ax1,'Number of paired realizations, N');

ylabel(ax1, ...
    'Spearman correlation to N = 50');

title(ax1,'A  Ranking convergence');

xlim(ax1,[8 52]);
ylim(ax1,[0.80 1.01]);
yticks(ax1,0.80:0.05:1.00);

xticks(ax1,N);

grid(ax1,'on');
box(ax1,'on');

text( ...
    ax1, ...
    0.02, ...
    0.06, ...
    'Shading: range across 25 SNR-metric families', ...
    'Units','normalized', ...
    'FontSize',8, ...
    'VerticalAlignment','bottom');

%% ------------------------------------------------------------
% PANEL B
% ------------------------------------------------------------

ax2 = nexttile(tl,2);

plot( ...
    ax2, ...
    N, ...
    winnerFraction, ...
    '-o', ...
    'LineWidth',1.8, ...
    'MarkerSize',6, ...
    'MarkerFaceColor','w');

hold(ax2,'on');

plot( ...
    ax2, ...
    N, ...
    ones(size(N)), ...
    '--', ...
    'LineWidth',1.0);

for k = 1:numel(N)

    text( ...
        ax2, ...
        N(k), ...
        winnerFraction(k)+0.045, ...
        sprintf( ...
        '%d/%d', ...
        C.WinnerMatchCount(k), ...
        C.NumberOfFamilies(k)), ...
        'HorizontalAlignment','center', ...
        'FontSize',8);
end

xlabel(ax2,'Number of paired realizations, N');

ylabel(ax2, ...
    'Winner agreement with N = 50');

title(ax2,'B  Highest-ranked method');

xlim(ax2,[8 52]);
ylim(ax2,[0.88 1.03]);
yticks(ax2,[0.90 0.95 1.00]);
xticks(ax2,N);

yticks(ax2,0:0.2:1);

grid(ax2,'on');
box(ax2,'on');

%% ------------------------------------------------------------
% PANEL C
% ------------------------------------------------------------

ax3 = nexttile(tl,3);

plot( ...
    ax3, ...
    N, ...
    worstRankShift, ...
    '-o', ...
    'LineWidth',1.8, ...
    'MarkerSize',6, ...
    'MarkerFaceColor','w');

hold(ax3,'on');

plot( ...
    ax3, ...
    N, ...
    meanRankShift, ...
    '--s', ...
    'LineWidth',1.4, ...
    'MarkerSize',5, ...
    'MarkerFaceColor','w');

xlabel(ax3,'Number of paired realizations, N');

ylabel(ax3,'Absolute mean-rank shift');

title(ax3,'C  Rank displacement');

xlim(ax3,[8 52]);

ylim(ax3,[0 ...
    max(worstRankShift)*1.15 + eps]);

xticks(ax3,N);

legend( ...
    ax3, ...
    {'Worst family','Mean across families'}, ...
    'Location','northeast', ...
    'Box','off');

grid(ax3,'on');
box(ax3,'on');

%% ------------------------------------------------------------
% COMMON AXES APPEARANCE
% ------------------------------------------------------------

axesList = ...
    [ax1 ax2 ax3];

for a = axesList

    set( ...
        a, ...
        'FontName','Arial', ...
        'FontSize',10, ...
        'LineWidth',0.9, ...
        'TickDir','out');
end

%% ------------------------------------------------------------
% EXPORT
% ------------------------------------------------------------

mainFigurePNG = fullfile( ...
    outDir, ...
    'Fig_MC_RankStability.png');

mainFigurePDF = fullfile( ...
    outDir, ...
    'Fig_MC_RankStability.pdf');

exportgraphics( ...
    fig1, ...
    mainFigurePNG, ...
    'Resolution',600);

exportgraphics( ...
    fig1, ...
    mainFigurePDF, ...
    'ContentType','vector');

%% ============================================================
% FIGURE 2
% SUPPLEMENTARY KENDALL-W + WINNER MAP
%
% Cell value = Kendall W
% Cell text  = winner at N=50
% ============================================================

fprintf('Creating Kendall-W / winner heatmap...\n');

Wmatrix = ...
    nan(numel(metricOrder),numel(snrLevels));

winnerMatrix = ...
    strings(numel(metricOrder),numel(snrLevels));

pHolmMatrix = ...
    nan(numel(metricOrder),numel(snrLevels));

for m = 1:numel(metricOrder)

    for s = 1:numel(snrLevels)

        idx = ...
            O.MetricLabel == metricOrder(m) & ...
            O.SNR_dB == snrLevels(s);

        assert(nnz(idx)==1);

        Wmatrix(m,s) = ...
            O.Kendall_W(idx);

        winnerMatrix(m,s) = ...
            O.Winner_N50(idx);

        pHolmMatrix(m,s) = ...
            O.P_Friedman_Holm25(idx);
    end
end

fig2 = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[100 100 980 620]);

ax = axes(fig2);

imagesc( ...
    ax, ...
    snrLevels, ...
    1:numel(metricOrder), ...
    Wmatrix);

set(ax,'YDir','reverse');

caxis(ax,[0.85 1.00]);

colormap(ax,parula(256));

cb = colorbar(ax);

ylabel(cb,'Kendall''s W (display range 0.85-1.00)');
xticks(ax,snrLevels);

yticks(ax,1:numel(metricOrder));

yticklabels(ax,metricOrder);

xlabel(ax,'Input SNR [dB]');

ylabel(ax,'Evaluation metric');

title(ax, ...
    'N = 50 Friedman concordance and highest-ranked method');

for m = 1:numel(metricOrder)

    for s = 1:numel(snrLevels)

        label = sprintf( ...
            '%s\nW = %.3f', ...
            winnerMatrix(m,s), ...
            Wmatrix(m,s));

        text( ...
            ax, ...
            snrLevels(s), ...
            m, ...
            label, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontWeight','bold', ...
            'FontSize',8, ...
            'Color','k');
    end
end

set( ...
    ax, ...
    'FontName','Arial', ...
    'FontSize',10, ...
    'LineWidth',0.9, ...
    'TickDir','out');

suppFigurePNG = fullfile( ...
    outDir, ...
    'FigS_MC_KendallW_Winners.png');

suppFigurePDF = fullfile( ...
    outDir, ...
    'FigS_MC_KendallW_Winners.pdf');

exportgraphics( ...
    fig2, ...
    suppFigurePNG, ...
    'Resolution',600);

exportgraphics( ...
    fig2, ...
    suppFigurePDF, ...
    'ContentType','vector');

%% ============================================================
% FIGURE 3
% SELECTED SCIENTIFIC PAIRWISE EFFECT-SIZE HEATMAPS
%
% Rank-biserial sign has already been oriented in STEP 09D-1:
%
%   +1 : Method A consistently better
%    0 : no directional dominance
%   -1 : Method B consistently better
%
% Three prespecified contrasts:
%
%   DAS     vs TR
%   DAS     vs SCF-DAS
%   SCF-DAS vs TR
%
% A dot marks primary Holm-significant pairwise comparisons.
% ============================================================

fprintf('Creating selected effect-size heatmaps...\n');

contrastA = [ ...
    "DAS", ...
    "DAS", ...
    "SCF-DAS"];

contrastB = [ ...
    "TR", ...
    "SCF-DAS", ...
    "TR"];

contrastTitles = [ ...
    "DAS vs TR", ...
    "DAS vs SCF-DAS", ...
    "SCF-DAS vs TR"];

nContrasts = ...
    numel(contrastA);

fig3 = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[80 80 1500 540]);

tl3 = tiledlayout( ...
    fig3, ...
    1,nContrasts, ...
    'TileSpacing','compact', ...
    'Padding','compact');

for c = 1:nContrasts

    effectMatrix = ...
        nan(numel(metricOrder),numel(snrLevels));

    sigMatrix = ...
        false(numel(metricOrder),numel(snrLevels));

    for m = 1:numel(metricOrder)

        for s = 1:numel(snrLevels)

            idx = ...
                P.MetricLabel == metricOrder(m) & ...
                P.SNR_dB == snrLevels(s) & ...
                P.MethodA == contrastA(c) & ...
                P.MethodB == contrastB(c);

            assert(nnz(idx)==1, ...
                'Requested selected pair was not found.');

            effectMatrix(m,s) = ...
                P.RankBiserial(idx);

            sigMatrix(m,s) = ...
                P.PrimaryPairwiseSignificant(idx);
        end
    end

    axc = nexttile(tl3,c);

    imagesc( ...
        axc, ...
        snrLevels, ...
        1:numel(metricOrder), ...
        effectMatrix);

set(axc,'YDir','reverse');
    caxis(axc,[-1 1]);

    colormap(axc,localDivergingMap(256));

    xticks(axc,snrLevels);

    yticks(axc,1:numel(metricOrder));

    if c==1
        yticklabels(axc,metricOrder);
        ylabel(axc,'Evaluation metric');
    else
        yticklabels(axc,[]);
    end

    xlabel(axc,'Input SNR [dB]');

    title(axc,contrastTitles(c));

    for m = 1:numel(metricOrder)

        for s = 1:numel(snrLevels)

            if sigMatrix(m,s)
                sigSymbol = ' *';
            else
                sigSymbol = '';
            end

            txt = sprintf( ...
                '%.2f%s', ...
                effectMatrix(m,s), ...
                sigSymbol);

            if abs(effectMatrix(m,s)) >= 0.55
                textColor = 'w';
            else
                textColor = 'k';
            end

            text( ...
                axc, ...
                snrLevels(s), ...
                m, ...
                txt, ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle', ...
                'FontWeight','bold', ...
                'FontSize',8, ...
                'Color',textColor);
        end
    end

    set( ...
        axc, ...
        'FontName','Arial', ...
        'FontSize',10, ...
        'LineWidth',0.9, ...
        'TickDir','out');
end

cb3 = colorbar;

cb3.Layout.Tile = 'east';

ylabel( ...
    cb3, ...
    ['Matched-pairs rank-biserial correlation' ...
     '  (+ = first method better)']);

title( ...
    tl3, ...
    'Selected paired effect sizes', ...
    'FontWeight','bold');

effectFigurePNG = fullfile( ...
    outDir, ...
    'FigS_MC_SelectedRankBiserial.png');

effectFigurePDF = fullfile( ...
    outDir, ...
    'FigS_MC_SelectedRankBiserial.pdf');

exportgraphics( ...
    fig3, ...
    effectFigurePNG, ...
    'Resolution',600);

exportgraphics( ...
    fig3, ...
    effectFigurePDF, ...
    'ContentType','vector');

%% ============================================================
% MAIN TABLE
%
% Compact five-row summary:
%
% Metric
% Winner across SNR
% Kendall W range
% largest Holm-adjusted omnibus p across SNR
%
% We first ASSERT that winner identity is constant across SNR.
% ============================================================

fprintf('Creating compact main-paper table...\n');

mainTable = table();

for m = 1:numel(metricOrder)

    idx = ...
        O.MetricLabel == metricOrder(m);

    Om = ...
        O(idx,:);

    assert(height(Om)==5);

    uniqueWinners = ...
        unique(Om.Winner_N50);

    assert(numel(uniqueWinners)==1, ...
        ['Winner is not constant across SNR for metric ' ...
         char(metricOrder(m)) '.']);

    row = table( ...
        metricOrder(m), ...
        uniqueWinners(1), ...
        min(Om.Kendall_W), ...
        max(Om.Kendall_W), ...
        max(Om.P_Friedman_Holm25), ...
        all(Om.Significant_Holm25), ...
        ...
        'VariableNames',{ ...
        'Metric', ...
        'WinnerAcrossAllSNR', ...
        'KendallW_Min', ...
        'KendallW_Max', ...
        'LargestHolm25P', ...
        'SignificantAtAllSNR'});

    mainTable = ...
        [mainTable;row]; %#ok<AGROW>
end

disp(mainTable);

writetable( ...
    mainTable, ...
    fullfile( ...
    outDir, ...
    'Table_Main_MC_StatisticalSummary.csv'));

%% ============================================================
% MAIN TABLE -> LaTeX
% ============================================================

mainTexFile = fullfile( ...
    outDir, ...
    'Table_Main_MC_StatisticalSummary.tex');

fid = fopen(mainTexFile,'w');

assert(fid>0);

fprintf(fid,'%% Auto-generated by STEP 09D-2\n');
fprintf(fid,'\\begin{table}[t]\n');
fprintf(fid,'\\centering\n');
fprintf(fid,'\\caption{Expanded paired Monte Carlo ranking summary. ');
fprintf(fid,['The highest-ranked method was invariant across the five ' ...
             'evaluated SNR levels (5--30~dB). ']);
fprintf(fid,['Kendall''s $W$ summarizes concordance among the paired ' ...
             'method rankings.}\n']);
fprintf(fid,'\\label{tab:mc-ranking-summary}\n');
fprintf(fid,'\\small\n');
fprintf(fid,'\\begin{tabular}{lccc}\n');
fprintf(fid,'\\hline\n');
fprintf(fid,['Metric & Highest-ranked method & ' ...
             '$W$ range & Largest Holm-adjusted $p$ \\\\\n']);
fprintf(fid,'\\hline\n');

for r = 1:height(mainTable)

    fprintf(fid, ...
        '%s & %s & %.3f--%.3f & %s \\\\\n', ...
        localLatexEscape(mainTable.Metric(r)), ...
        localLatexEscape( ...
            mainTable.WinnerAcrossAllSNR(r)), ...
        mainTable.KendallW_Min(r), ...
        mainTable.KendallW_Max(r), ...
        localLatexSci( ...
            mainTable.LargestHolm25P(r)));
end

fprintf(fid,'\\hline\n');
fprintf(fid,'\\end{tabular}\n');
fprintf(fid,'\\end{table}\n');

fclose(fid);

%% ============================================================
% SUPPLEMENTARY FULL 25-FAMILY TABLE
% ============================================================

fprintf('Creating full 25-family supplementary table...\n');

supp25 = O(:,{ ...
    'SNR_dB', ...
    'MetricLabel', ...
    'Winner_N50', ...
    'Kendall_W', ...
    'P_Friedman_Raw', ...
    'P_Friedman_Holm25', ...
    'Significant_Holm25'});

supp25 = sortrows( ...
    supp25, ...
    {'SNR_dB','MetricLabel'});

writetable( ...
    supp25, ...
    fullfile( ...
    outDir, ...
    'TableS_Friedman25.csv'));

suppTexFile = fullfile( ...
    outDir, ...
    'TableS_Friedman25.tex');

fid = fopen(suppTexFile,'w');

assert(fid>0);

fprintf(fid,'%% Auto-generated by STEP 09D-2\n');
fprintf(fid,'\\begin{table*}[t]\n');
fprintf(fid,'\\centering\n');
fprintf(fid,['\\caption{Friedman omnibus results for the 25 ' ...
             'SNR--metric families in the expanded paired Monte Carlo ' ...
             'analysis ($N=50$). Holm adjustment was applied across ' ...
             'all 25 omnibus tests.}\n']);
fprintf(fid,'\\label{tab:mc-friedman25}\n');
fprintf(fid,'\\small\n');
fprintf(fid,'\\begin{tabular}{cllccc}\n');
fprintf(fid,'\\hline\n');
fprintf(fid,['SNR [dB] & Metric & Highest-ranked method & ' ...
             '$W$ & Raw $p$ & Holm-25 $p$ \\\\\n']);
fprintf(fid,'\\hline\n');

for r = 1:height(supp25)

    fprintf(fid, ...
        '%g & %s & %s & %.4f & %s & %s \\\\\n', ...
        supp25.SNR_dB(r), ...
        localLatexEscape(supp25.MetricLabel(r)), ...
        localLatexEscape(supp25.Winner_N50(r)), ...
        supp25.Kendall_W(r), ...
        localLatexSci(supp25.P_Friedman_Raw(r)), ...
        localLatexSci(supp25.P_Friedman_Holm25(r)));
end

fprintf(fid,'\\hline\n');
fprintf(fid,'\\end{tabular}\n');
fprintf(fid,'\\end{table*}\n');

fclose(fid);

%% ============================================================
% SELECTED PAIRWISE EFFECT-SIZE TABLE
%
% All SNR and all five metrics are retained.
% Only the three prespecified scientifically interpretable
% contrasts are selected.
%
% No pairwise result is recomputed.
% ============================================================

fprintf('Creating selected pairwise effect-size table...\n');

selectedMask = ...
    (P.MethodA=="DAS" & P.MethodB=="TR") | ...
    (P.MethodA=="DAS" & P.MethodB=="SCF-DAS") | ...
    (P.MethodA=="SCF-DAS" & P.MethodB=="TR");

selectedPairwise = ...
    P(selectedMask,{ ...
    'SNR_dB', ...
    'MetricLabel', ...
    'MethodA', ...
    'MethodB', ...
    'MedianDelta_AminusB_Raw', ...
    'RawMedianCI95_Low', ...
    'RawMedianCI95_High', ...
    'RankBiserial', ...
    'P_Wilcoxon_Raw', ...
    'P_Wilcoxon_Holm15', ...
    'PrimaryPairwiseSignificant', ...
    'Seeds_A_Better', ...
    'Seeds_B_Better', ...
    'Seeds_Tied'});

assert(height(selectedPairwise)==75, ...
    'Expected 75 selected pairwise rows.');

selectedPairwise = sortrows( ...
    selectedPairwise, ...
    {'MetricLabel','SNR_dB','MethodA','MethodB'});

writetable( ...
    selectedPairwise, ...
    fullfile( ...
    outDir, ...
    'TableS_SelectedPairwiseEffects_75.csv'));

%% ============================================================
% HUMAN-READABLE RANK-STABILITY TABLE
% ============================================================

rankTable = C(:,{ ...
    'N', ...
    'MeanSpearmanToN50', ...
    'MedianSpearmanToN50', ...
    'MinimumSpearmanToN50', ...
    'WinnerMatchCount', ...
    'NumberOfFamilies', ...
    'MeanMaxAbsRankShift', ...
    'WorstMaxAbsRankShift'});

writetable( ...
    rankTable, ...
    fullfile( ...
    outDir, ...
    'Table_MC_RankStability.csv'));

rankTexFile = fullfile( ...
    outDir, ...
    'Table_MC_RankStability.tex');

fid = fopen(rankTexFile,'w');

assert(fid>0);

fprintf(fid,'%% Auto-generated by STEP 09D-2\n');
fprintf(fid,'\\begin{table}[t]\n');
fprintf(fid,'\\centering\n');
fprintf(fid,'\\caption{Ranking stability with increasing paired Monte Carlo sample size.}\n');
fprintf(fid,'\\label{tab:mc-rank-stability}\n');
fprintf(fid,'\\small\n');
fprintf(fid,'\\begin{tabular}{ccccc}\n');
fprintf(fid,'\\hline\n');
fprintf(fid,['$N$ & Mean $\\rho_S$ & Minimum $\\rho_S$ & ' ...
             'Winner agreement & Worst rank shift \\\\\n']);
fprintf(fid,'\\hline\n');

for r = 1:height(rankTable)

    fprintf(fid, ...
        '%d & %.3f & %.3f & %d/%d & %.3f \\\\\n', ...
        rankTable.N(r), ...
        rankTable.MeanSpearmanToN50(r), ...
        rankTable.MinimumSpearmanToN50(r), ...
        rankTable.WinnerMatchCount(r), ...
        rankTable.NumberOfFamilies(r), ...
        rankTable.WorstMaxAbsRankShift(r));
end

fprintf(fid,'\\hline\n');
fprintf(fid,'\\end{tabular}\n');
fprintf(fid,'\\end{table}\n');

fclose(fid);

%% ============================================================
% FIGURE CAPTIONS
% ============================================================

captionFile = fullfile( ...
    outDir, ...
    'publication_captions_step09D2.txt');

fid = fopen(captionFile,'w');

assert(fid>0);

fprintf(fid, ...
    ['MAIN FIGURE -- Ranking stability\n\n' ...
     'Ranking stability of the expanded paired Monte Carlo analysis. ' ...
     '(A) Mean Spearman correlation between interim six-method rankings ' ...
     'and the final N=50 rankings as the number of paired realizations ' ...
     'increased from 10 to 50; the shaded region spans the minimum to ' ...
     'maximum correlation across the 25 SNR--metric families. ' ...
     '(B) Fraction of families for which the highest-ranked method ' ...
     'matched the final N=50 result. ' ...
     '(C) Mean and worst absolute displacement of method mean ranks ' ...
     'relative to N=50. By N=40, the highest-ranked method agreed with ' ...
     'the final analysis in all 25 families.\n\n']);

fprintf(fid, ...
    ['SUPPLEMENTARY FIGURE -- Kendall W and winners\n\n' ...
     'Method-ranking concordance in the N=50 paired Monte Carlo study. ' ...
     'Each cell reports Kendall''s coefficient of concordance W and ' ...
     'the highest-ranked reconstruction method for one SNR--metric ' ...
     'family. All 25 Friedman tests remained significant after Holm ' ...
     'correction across the omnibus family.\n\n']);

fprintf(fid, ...
    ['SUPPLEMENTARY FIGURE -- Selected effect sizes\n\n' ...
     'Matched-pairs rank-biserial effect sizes for three prespecified ' ...
     'method contrasts across five input SNR levels and five evaluation ' ...
     'metrics. Positive values favor the first named method and negative ' ...
     'values favor the second after orienting each metric so that positive ' ...
     'performance differences represent improvement. Asterisks denote ' ...
     'pairwise comparisons significant under the primary within-family ' ...
     'Holm correction following a significant omnibus Friedman test.\n']);

fclose(fid);

%% ============================================================
% FINAL AUDIT / CONSOLE SUMMARY
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09D-2 PUBLICATION OUTPUT AUDIT\n');
fprintf('============================================================\n');

fprintf('Main stability figure PNG       : %d\n', ...
    isfile(mainFigurePNG));

fprintf('Main stability figure PDF       : %d\n', ...
    isfile(mainFigurePDF));

fprintf('Kendall-W figure PNG            : %d\n', ...
    isfile(suppFigurePNG));

fprintf('Kendall-W figure PDF            : %d\n', ...
    isfile(suppFigurePDF));

fprintf('Effect-size figure PNG          : %d\n', ...
    isfile(effectFigurePNG));

fprintf('Effect-size figure PDF          : %d\n', ...
    isfile(effectFigurePDF));

fprintf('Main summary table rows         : %d\n', ...
    height(mainTable));

fprintf('Full Friedman table rows        : %d\n', ...
    height(supp25));

fprintf('Selected pairwise rows          : %d\n', ...
    height(selectedPairwise));

fprintf('\nMAIN TABLE\n');
fprintf('------------------------------------------------------------\n');

disp(mainTable);

fprintf('\nRANK STABILITY TABLE\n');
fprintf('------------------------------------------------------------\n');

disp(rankTable);

fprintf('\nOutput directory:\n%s\n', ...
    outDir);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09D-2 COMPLETE: PASS\n');
fprintf('============================================================\n');


%% ============================================================
% LOCAL FUNCTION
% LATEX ESCAPE
% ============================================================

function out = localLatexEscape(in)

    out = ...
        char(string(in));

    out = ...
        strrep(out,'_','\_');

    out = ...
        strrep(out,'%','\%');

    out = ...
        strrep(out,'&','\&');

end


%% ============================================================
% LOCAL FUNCTION
% SCIENTIFIC NUMBER -> LATEX
%
% Example:
%   5.89e-46
%
% becomes:
%   $5.89\times10^{-46}$
% ============================================================

function out = localLatexSci(x)

    if x == 0

        out = '$0$';
        return;
    end

    exponent = ...
        floor(log10(abs(x)));

    mantissa = ...
        x / ...
        10^exponent;

    out = ...
        sprintf( ...
        '$%.2f\\times10^{%d}$', ...
        mantissa, ...
        exponent);

end


%% ============================================================
% LOCAL FUNCTION
% SIMPLE BLUE-WHITE-RED DIVERGING MAP
% ============================================================

function cmap = localDivergingMap(n)

    if nargin < 1
        n = 256;
    end

    n1 = ...
        floor(n/2);

    n2 = ...
        n-n1;

    left = [ ...
        linspace(0.10,1,n1).', ...
        linspace(0.25,1,n1).', ...
        linspace(0.80,1,n1).'];

    right = [ ...
        linspace(1,0.75,n2).', ...
        linspace(1,0.15,n2).', ...
        linspace(1,0.10,n2).'];

    cmap = ...
        [left;right];

    cmap = ...
        min(max(cmap,0),1);

end