clear;
close all;
clc;

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

inputFile = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step06_sequential_reconstruction', ...
    'sequential_reconstruction_metrics.csv');

outputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step07_sequential_figures');

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

assert(isfile(inputFile), ...
    'Sequential metrics CSV not found.');

T = readtable( ...
    inputFile, ...
    'TextType','string');

assert(height(T)==36, ...
    'Expected 36 outcomes.');

%% ============================================================
% DEFINITIONS
% ============================================================

stageIds = [ ...
    "D0_ideal", ...
    "D1_bandwidth", ...
    "D2_finite_aperture", ...
    "D3_heterogeneity", ...
    "D4_attenuation", ...
    "D5_noise"];

stageLabels = { ...
    'Ideal', ...
    '+BW', ...
    '+Aperture', ...
    '+Heterogeneity', ...
    '+Attenuation', ...
    '+Noise'};

factorLabels = { ...
    'Bandwidth', ...
    'Finite aperture', ...
    'Heterogeneity', ...
    'Attenuation', ...
    'Noise'};

methodLabels = [ ...
    "DAS", ...
    "CF-DAS", ...
    "SCF-DAS", ...
    "DMAS", ...
    "DS-DMAS", ...
    "TR"];

metricNames = [ ...
    "SI_NRMSE", ...
    "Correlation", ...
    "SSIM", ...
    "CNR", ...
    "SBR_dB"];

metricTitles = { ...
    'SI-NRMSE', ...
    'Correlation', ...
    'SSIM', ...
    'CNR', ...
    'SBR [dB]'};

higherIsBetter = [ ...
    false, ...
    true, ...
    true, ...
    true, ...
    true];

nStages = numel(stageIds);
nMethods = numel(methodLabels);
nMetrics = numel(metricNames);

%% ============================================================
% CREATE NUMERIC MATRICES
%
% metricData{q}:
% rows    = methods
% columns = stages
% ============================================================

metricData = cell(nMetrics,1);

for q = 1:nMetrics

    M = nan(nMethods,nStages);

    for m = 1:nMethods

        for s = 1:nStages

            idx = ...
                T.Method == methodLabels(m) & ...
                T.Stage == stageIds(s);

            assert(nnz(idx)==1, ...
                'Expected one row per method-stage pair.');

            M(m,s) = ...
                T.(metricNames(q))(idx);
        end
    end

    metricData{q} = M;
end

%% ============================================================
% FIGURE A
% ABSOLUTE METRIC TRAJECTORIES
% ============================================================

fig1 = figure( ...
    'Color','w', ...
    'Position',[50 50 1500 900]);

tl = tiledlayout( ...
    fig1, ...
    2, ...
    3, ...
    'TileSpacing','compact', ...
    'Padding','compact');

firstHandles = gobjects(nMethods,1);

for q = 1:nMetrics

    ax = nexttile(tl,q);

    hold(ax,'on');

    M = metricData{q};

    for m = 1:nMethods

        h = plot( ...
            ax, ...
            0:nStages-1, ...
            M(m,:), ...
            '-o', ...
            'LineWidth',1.5, ...
            'MarkerSize',5);

        if q == 1
            firstHandles(m) = h;
        end
    end

    hold(ax,'off');

    grid(ax,'on');
    box(ax,'on');

    xlim(ax,[-0.2 nStages-0.8]);

    xticks(ax,0:nStages-1);
    xticklabels(ax,stageLabels);

    xtickangle(ax,25);

    ylabel(ax,metricTitles{q});

    if higherIsBetter(q)
        directionText = 'higher is better';
    else
        directionText = 'lower is better';
    end

    title( ...
        ax, ...
        sprintf('%s (%s)', ...
        metricTitles{q}, ...
        directionText), ...
        'FontWeight','bold');

    ax.FontSize = 10;
end

title( ...
    tl, ...
    ['Sequential physical-degradation sensitivity: ' ...
     'absolute reconstruction metrics'], ...
    'FontSize',16, ...
    'FontWeight','bold');

lgd = legend( ...
    firstHandles, ...
    cellstr(methodLabels), ...
    'Orientation','horizontal', ...
    'NumColumns',3);

lgd.Layout.Tile = 'south';

%% ------------------------------------------------------------
% Export
% ------------------------------------------------------------

exportgraphics( ...
    fig1, ...
    fullfile( ...
        outputDir, ...
        'Fig_R1_2_absolute_metric_trajectories.png'), ...
    'Resolution',300);

exportgraphics( ...
    fig1, ...
    fullfile( ...
        outputDir, ...
        'Fig_R1_2_absolute_metric_trajectories.pdf'), ...
    'ContentType','vector');

%% ============================================================
% INCREMENTAL DETERIORATION
%
% Convention:
%
% SI-NRMSE:
%     current - previous
%
% Higher-is-better metrics:
%     previous - current
%
% Therefore:
%     positive = deterioration
%     negative = apparent improvement
% ============================================================

deteriorationData = cell(nMetrics,1);

deltaRows = [];

for q = 1:nMetrics

    M = metricData{q};

    rawDelta = diff(M,1,2);

    if higherIsBetter(q)

        D = -rawDelta;

    else

        D = rawDelta;
    end

    deteriorationData{q} = D;

    %% Long-form table
    for m = 1:nMethods

        for f = 1:(nStages-1)

            newRow = table( ...
                methodLabels(m), ...
                string(factorLabels{f}), ...
                metricNames(q), ...
                D(m,f), ...
                'VariableNames', { ...
                'Method', ...
                'AddedFactor', ...
                'Metric', ...
                'Deterioration'});

            deltaRows = [deltaRows; newRow]; %#ok<AGROW>
        end
    end
end

writetable( ...
    deltaRows, ...
    fullfile( ...
        outputDir, ...
        'incremental_degradation_effects.csv'));

%% ============================================================
% FIGURE B
% INCREMENTAL EFFECT HEATMAPS
% ============================================================

fig2 = figure( ...
    'Color','w', ...
    'Position',[50 50 1550 900]);

tl2 = tiledlayout( ...
    fig2, ...
    2, ...
    3, ...
    'TileSpacing','compact', ...
    'Padding','compact');

cmap = blueWhiteRedMap(256);

for q = 1:nMetrics

    ax = nexttile(tl2,q);

    D = deteriorationData{q};

    imagesc(ax,D);

    colormap(ax,cmap);

    maxAbs = max(abs(D(:)));

    if maxAbs <= eps
        maxAbs = 1;
    end

    clim(ax,[-maxAbs maxAbs]);

    cb = colorbar(ax);

    ylabel(cb, ...
        sprintf('\\Delta %s',metricTitles{q}));

    xticks(ax,1:numel(factorLabels));
    xticklabels(ax,factorLabels);
    xtickangle(ax,25);

    yticks(ax,1:nMethods);
    yticklabels(ax,cellstr(methodLabels));

    title( ...
        ax, ...
        metricTitles{q}, ...
        'FontWeight','bold');

    ax.FontSize = 10;

    %% --------------------------------------------------------
    % Numeric values inside cells
    % ---------------------------------------------------------

    for r = 1:nMethods

        for c = 1:numel(factorLabels)

            value = D(r,c);

            if q == 5

                valueText = ...
                    sprintf('%.2f',value);

            else

                valueText = ...
                    sprintf('%.3f',value);
            end

            text( ...
                ax, ...
                c, ...
                r, ...
                valueText, ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle', ...
                'FontSize',8, ...
                'FontWeight','bold');
        end
    end
end

title( ...
    tl2, ...
    { ...
    'Incremental effect of each added physical degradation', ...
    'Positive values indicate deterioration; negative values indicate apparent improvement' ...
    }, ...
    'FontSize',15, ...
    'FontWeight','bold');

exportgraphics( ...
    fig2, ...
    fullfile( ...
        outputDir, ...
        'Fig_R1_2_incremental_degradation_heatmaps.png'), ...
    'Resolution',300);

exportgraphics( ...
    fig2, ...
    fullfile( ...
        outputDir, ...
        'Fig_R1_2_incremental_degradation_heatmaps.pdf'), ...
    'ContentType','vector');

%% ============================================================
% BEST METHOD AT EACH STAGE
% ============================================================

bestRows = [];

for s = 1:nStages

    for q = 1:nMetrics

        M = metricData{q};

        values = M(:,s);

        if higherIsBetter(q)

            [bestValue,bestIndex] = ...
                max(values);

        else

            [bestValue,bestIndex] = ...
                min(values);
        end

        newRow = table( ...
            stageIds(s), ...
            string(stageLabels{s}), ...
            metricNames(q), ...
            methodLabels(bestIndex), ...
            bestValue, ...
            'VariableNames',{ ...
            'Stage', ...
            'StageLabel', ...
            'Metric', ...
            'BestMethod', ...
            'BestValue'});

        bestRows = ...
            [bestRows;newRow]; %#ok<AGROW>
    end
end

writetable( ...
    bestRows, ...
    fullfile( ...
        outputDir, ...
        'best_method_by_stage.csv'));

%% ============================================================
% CONSOLE SUMMARY
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('SEQUENTIAL SENSITIVITY SUMMARY\n');
fprintf('============================================================\n');

disp(bestRows);

%% ============================================================
% FINITE APERTURE EFFECT AUDIT
% ============================================================

fprintf('\n');
fprintf('Finite-aperture maximum absolute changes:\n');
fprintf('------------------------------------------------------------\n');

for q = 1:nMetrics

    % factor column 2 = finite aperture
    D = deteriorationData{q};

    maxEffect = ...
        max(abs(D(:,2)));

    fprintf( ...
        '%-12s : %.6f\n', ...
        metricTitles{q}, ...
        maxEffect);
end

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 07 COMPLETE\n');
fprintf('============================================================\n');

fprintf('\nFigures and tables written to:\n%s\n', ...
    outputDir);

%% ============================================================
% LOCAL FUNCTION
% ============================================================

function cmap = blueWhiteRedMap(n)

    if nargin < 1
        n = 256;
    end

    n1 = floor(n/2);
    n2 = n-n1;

    blue = [0.20 0.40 0.85];
    white = [1 1 1];
    red = [0.85 0.25 0.20];

    firstHalf = [ ...
        linspace(blue(1),white(1),n1)', ...
        linspace(blue(2),white(2),n1)', ...
        linspace(blue(3),white(3),n1)'];

    secondHalf = [ ...
        linspace(white(1),red(1),n2)', ...
        linspace(white(2),red(2),n2)', ...
        linspace(white(3),red(3),n2)'];

    cmap = [firstHalf;secondHalf];
end