clear;
close all;
clc;

%% ============================================================
% STEP 09D-1
% Expanded Monte Carlo statistical analysis
%
% Dataset:
%   50 paired seeds
% x 5 SNR levels
% x 6 reconstruction methods
% = 1500 outcomes
%
% Inferential analysis:
%
% 1) 25 paired Friedman tests
% 2) Holm correction across all 25 omnibus tests
% 3) 15 paired Wilcoxon comparisons / family
% 4) Holm correction within each pairwise family
% 5) matched-pairs rank-biserial effect size
% 6) paired bootstrap 95% CI for median differences
% 7) ranking convergence at N = 10,20,30,40,50
%
% No simulation or reconstruction occurs here.
% ============================================================

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

mcRoot = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step09_montecarlo');

inputFile = fullfile( ...
    mcRoot, ...
    'montecarlo_reconstruction_metrics_1500.csv');

analysisDir = fullfile( ...
    mcRoot, ...
    'statistics');

if ~exist(analysisDir,'dir')
    mkdir(analysisDir);
end

assert(isfile(inputFile), ...
    '1500-outcome Monte Carlo table not found.');

%% ============================================================
% LOAD
% ============================================================

T = readtable( ...
    inputFile, ...
    'TextType','string');

assert(height(T)==1500, ...
    'Expected exactly 1500 reconstruction outcomes.');

%% ============================================================
% FROZEN DEFINITIONS
% ============================================================

baseSeeds = ...
    (1:50).';

snrLevels_dB = ...
    [5 10 15 20 30];

methods = [ ...
    "DAS", ...
    "CF-DAS", ...
    "SCF-DAS", ...
    "DMAS", ...
    "DS-DMAS", ...
    "TR"];

metrics = [ ...
    "SI_NRMSE", ...
    "Correlation", ...
    "SSIM", ...
    "CNR", ...
    "SBR_dB"];

metricLabels = [ ...
    "SI-NRMSE", ...
    "Correlation", ...
    "SSIM", ...
    "CNR", ...
    "SBR"];

% true  -> larger metric value = better
% false -> smaller metric value = better

higherIsBetter = [ ...
    false, ...
    true, ...
    true, ...
    true, ...
    true];

checkpoints = ...
    [10 20 30 40 50];

alpha = ...
    0.05;

nBootstrap = ...
    5000;

analysisSeed = ...
    950001;

nSeeds = ...
    numel(baseSeeds);

nSNR = ...
    numel(snrLevels_dB);

nMethods = ...
    numel(methods);

nMetrics = ...
    numel(metrics);

nFamilies = ...
    nSNR*nMetrics;

nPairsPerFamily = ...
    nchoosek(nMethods,2);

%% ============================================================
% MASTER DATA AUDIT
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09D-1: EXPANDED MONTE CARLO STATISTICS\n');
fprintf('============================================================\n');

fprintf('Rows                   = %d\n',height(T));
fprintf('Seeds                  = %d\n',nSeeds);
fprintf('SNR levels             = %d\n',nSNR);
fprintf('Methods                = %d\n',nMethods);
fprintf('Metrics                = %d\n',nMetrics);

fprintf('Friedman families      = %d\n',nFamilies);
fprintf('Pairs / family         = %d\n',nPairsPerFamily);

fprintf('Bootstrap resamples    = %d\n',nBootstrap);
fprintf('Alpha                  = %.3f\n',alpha);

assert(numel(unique(T.BaseSeed))==50);
assert(numel(unique(T.TargetSNR_dB))==5);
assert(numel(unique(T.Method))==6);

%% ------------------------------------------------------------
% Every seed x SNR x method combination must appear once.
% ------------------------------------------------------------

for s = 1:nSNR

    for n = 1:nSeeds

        idxBlock = ...
            T.TargetSNR_dB == snrLevels_dB(s) & ...
            T.BaseSeed == baseSeeds(n);

        assert(nnz(idxBlock)==6, ...
            'Incomplete paired block.');
    end
end

fprintf('\nPaired block structure   : PASS\n');

%% ============================================================
% STORAGE
% ============================================================

omnibusTable = [];

pairwiseTable = [];

checkpointRankTable = [];

stabilityTable = [];

familyCounter = ...
    0;

%% ============================================================
% SAVE / RESTORE RNG STATE
% ============================================================

oldRngState = ...
    rng;

rngCleanup = ...
    onCleanup(@() rng(oldRngState));

%% ============================================================
% FAMILY LOOP
% ============================================================

for s = 1:nSNR

    targetSNR = ...
        snrLevels_dB(s);

    for q = 1:nMetrics

        familyCounter = ...
            familyCounter + 1;

        metricName = ...
            metrics(q);

        metricLabel = ...
            metricLabels(q);

        fprintf('\n');
        fprintf('------------------------------------------------------------\n');
        fprintf('Family %2d / %2d | SNR %2g dB | %s\n', ...
            familyCounter, ...
            nFamilies, ...
            targetSNR, ...
            metricLabel);
        fprintf('------------------------------------------------------------\n');

        %% ====================================================
        % BUILD EXACT 50 x 6 PAIRED MATRIX
        %
        % rows    = base seeds 1...50
        % columns = reconstruction methods
        % =====================================================

        X = ...
            localBuildPairedMatrix( ...
            T, ...
            targetSNR, ...
            metricName, ...
            baseSeeds, ...
            methods);

        assert(isequal(size(X),[50 6]));

        assert(all(isfinite(X(:))));

        %% ====================================================
        % ORIENT METRIC SO THAT LARGER = BETTER
        %
        % This does not alter Friedman significance.
        % It only makes:
        %
        %   rank 1 = best method
        %
        % and pairwise effect signs consistent.
        % =====================================================

        if higherIsBetter(q)

            directionSign = ...
                1;

        else

            directionSign = ...
                -1;
        end

        Xoriented = ...
            directionSign .* X;

        %% ====================================================
        % FRIEDMAN N = 50
        % =====================================================

        pFriedmanRaw = ...
            friedman( ...
            Xoriented, ...
            1, ...
            'off');

        [rankMatrix50,kendallW50] = ...
            localFriedmanRankStatistics( ...
            Xoriented);

        meanRanks50 = ...
            mean(rankMatrix50,1);

        medianRanks50 = ...
            median(rankMatrix50,1);

        finalWinnerSet = ...
            localWinnerSet( ...
            meanRanks50, ...
            methods);

        finalWinnerLabel = ...
            strjoin(finalWinnerSet," + ");

        fprintf('Friedman p raw = %.6e\n', ...
            pFriedmanRaw);

        fprintf('Kendall W      = %.6f\n', ...
            kendallW50);

        fprintf('N=50 winner    = %s\n', ...
            finalWinnerLabel);

        %% ====================================================
        % OMNIBUS ROW
        % =====================================================

        omnibusRow = table( ...
            familyCounter, ...
            targetSNR, ...
            metricName, ...
            metricLabel, ...
            pFriedmanRaw, ...
            kendallW50, ...
            finalWinnerLabel, ...
            ...
            'VariableNames',{ ...
            'FamilyID', ...
            'SNR_dB', ...
            'Metric', ...
            'MetricLabel', ...
            'P_Friedman_Raw', ...
            'Kendall_W', ...
            'Winner_N50'});

        omnibusTable = ...
            [omnibusTable;omnibusRow]; %#ok<AGROW>

        %% ====================================================
        % ONE COMMON PAIRED BOOTSTRAP INDEX MATRIX PER FAMILY
        %
        % Resampling unit = BASE SEED.
        %
        % Thus all bootstrap operations preserve pairing.
        % =====================================================

        rng( ...
            analysisSeed + familyCounter, ...
            'twister');

        bootstrapIndex = ...
            randi( ...
            nSeeds, ...
            nSeeds, ...
            nBootstrap);

        %% ====================================================
        % ALL 15 PAIRWISE COMPARISONS
        % =====================================================

        familyPairTable = [];

        for i = 1:nMethods-1

            for j = i+1:nMethods

                methodA = ...
                    methods(i);

                methodB = ...
                    methods(j);

                rawA = ...
                    X(:,i);

                rawB = ...
                    X(:,j);

                %% --------------------------------------------
                % Raw paired difference:
                %
                %     A - B
                %
                % This preserves the native metric scale.
                % --------------------------------------------

                dRaw = ...
                    rawA - rawB;

                %% --------------------------------------------
                % Oriented difference:
                %
                % Positive = A performs better than B.
                % --------------------------------------------

                dOriented = ...
                    directionSign .* ...
                    dRaw;

                %% --------------------------------------------
                % Wilcoxon signed-rank
                % --------------------------------------------

                if all(dOriented==0)

                    pWilcoxon = ...
                        1;

                else

                    pWilcoxon = ...
                        signrank( ...
                        dOriented, ...
                        0, ...
                        'method','approximate');
                end

                %% --------------------------------------------
                % Matched-pairs rank-biserial correlation
                %
                % Positive:
                % Method A better.
                %
                % Negative:
                % Method B better.
                % --------------------------------------------

                rankBiserial = ...
                    localMatchedRankBiserial( ...
                    dOriented);

                %% --------------------------------------------
                % Paired median differences
                % --------------------------------------------

                medianRawDifference = ...
                    median(dRaw);

                medianOrientedDifference = ...
                    median(dOriented);

                %% --------------------------------------------
                % 95% paired-bootstrap CI for median difference
                % --------------------------------------------

                bootstrapRawMedian = ...
                    median( ...
                    dRaw(bootstrapIndex), ...
                    1);

                bootstrapOrientedMedian = ...
                    directionSign .* ...
                    bootstrapRawMedian;

                rawCI = ...
                    localPercentileCI( ...
                    bootstrapRawMedian, ...
                    95);

                orientedCI = ...
                    localPercentileCI( ...
                    bootstrapOrientedMedian, ...
                    95);

                %% --------------------------------------------
                % Simple paired direction counts
                % --------------------------------------------

                nABetter = ...
                    nnz(dOriented > 0);

                nBBetter = ...
                    nnz(dOriented < 0);

                nTied = ...
                    nnz(dOriented == 0);

                pairRow = table( ...
                    familyCounter, ...
                    targetSNR, ...
                    metricName, ...
                    metricLabel, ...
                    methodA, ...
                    methodB, ...
                    medianRawDifference, ...
                    rawCI(1), ...
                    rawCI(2), ...
                    medianOrientedDifference, ...
                    orientedCI(1), ...
                    orientedCI(2), ...
                    pWilcoxon, ...
                    rankBiserial, ...
                    nABetter, ...
                    nBBetter, ...
                    nTied, ...
                    ...
                    'VariableNames',{ ...
                    'FamilyID', ...
                    'SNR_dB', ...
                    'Metric', ...
                    'MetricLabel', ...
                    'MethodA', ...
                    'MethodB', ...
                    'MedianDelta_AminusB_Raw', ...
                    'RawMedianCI95_Low', ...
                    'RawMedianCI95_High', ...
                    'MedianDelta_Oriented', ...
                    'OrientedMedianCI95_Low', ...
                    'OrientedMedianCI95_High', ...
                    'P_Wilcoxon_Raw', ...
                    'RankBiserial', ...
                    'Seeds_A_Better', ...
                    'Seeds_B_Better', ...
                    'Seeds_Tied'});

                familyPairTable = ...
                    [familyPairTable;pairRow]; %#ok<AGROW>
            end
        end

        assert(height(familyPairTable)==15);

        %% ====================================================
        % HOLM CORRECTION WITHIN THIS 15-COMPARISON FAMILY
        % =====================================================

        familyPairTable.P_Wilcoxon_Holm15 = ...
            localHolmAdjust( ...
            familyPairTable.P_Wilcoxon_Raw);

        familyPairTable.Significant_Holm15 = ...
            familyPairTable.P_Wilcoxon_Holm15 < alpha;

        pairwiseTable = ...
            [pairwiseTable;familyPairTable]; %#ok<AGROW>

        %% ====================================================
        % RANK-CONVERGENCE CHECKPOINTS
        % =====================================================

        for c = 1:numel(checkpoints)

            N = ...
                checkpoints(c);

            XN = ...
                Xoriented(1:N,:);

            pCheckpoint = ...
                friedman( ...
                XN, ...
                1, ...
                'off');

            [rankMatrixN,kendallWN] = ...
                localFriedmanRankStatistics( ...
                XN);

            meanRanksN = ...
                mean(rankMatrixN,1);

            medianRanksN = ...
                median(rankMatrixN,1);

            rhoToFinal = ...
                localSpearman( ...
                meanRanksN, ...
                meanRanks50);

            checkpointWinnerSet = ...
                localWinnerSet( ...
                meanRanksN, ...
                methods);

            checkpointWinnerLabel = ...
                strjoin( ...
                checkpointWinnerSet, ...
                " + ");

            winnerMatchesFinal = ...
                any( ...
                ismember( ...
                checkpointWinnerSet, ...
                finalWinnerSet));

            maxAbsoluteMeanRankShift = ...
                max( ...
                abs( ...
                meanRanksN - ...
                meanRanks50));

            %% --------------------------------------------
            % One stability row
            % --------------------------------------------

            stabilityRow = table( ...
                familyCounter, ...
                targetSNR, ...
                metricName, ...
                metricLabel, ...
                N, ...
                pCheckpoint, ...
                kendallWN, ...
                rhoToFinal, ...
                checkpointWinnerLabel, ...
                finalWinnerLabel, ...
                winnerMatchesFinal, ...
                maxAbsoluteMeanRankShift, ...
                ...
                'VariableNames',{ ...
                'FamilyID', ...
                'SNR_dB', ...
                'Metric', ...
                'MetricLabel', ...
                'N', ...
                'P_Friedman', ...
                'Kendall_W', ...
                'SpearmanToN50', ...
                'CheckpointWinner', ...
                'FinalWinner_N50', ...
                'WinnerMatchesFinal', ...
                'MaxAbsMeanRankShift'});

            stabilityTable = ...
                [stabilityTable;stabilityRow]; %#ok<AGROW>

            %% --------------------------------------------
            % Method-level checkpoint ranks
            % --------------------------------------------

            for m = 1:nMethods

                rankRow = table( ...
                    familyCounter, ...
                    targetSNR, ...
                    metricName, ...
                    metricLabel, ...
                    N, ...
                    methods(m), ...
                    meanRanksN(m), ...
                    medianRanksN(m), ...
                    meanRanks50(m), ...
                    meanRanksN(m)-meanRanks50(m), ...
                    ...
                    'VariableNames',{ ...
                    'FamilyID', ...
                    'SNR_dB', ...
                    'Metric', ...
                    'MetricLabel', ...
                    'N', ...
                    'Method', ...
                    'MeanRank', ...
                    'MedianRank', ...
                    'FinalMeanRank_N50', ...
                    'MeanRankShiftFromN50'});

                checkpointRankTable = ...
                    [checkpointRankTable;rankRow]; %#ok<AGROW>
            end
        end
    end
end

%% ============================================================
% HOLM CORRECTION ACROSS ALL 25 FRIEDMAN TESTS
% ============================================================

omnibusTable.P_Friedman_Holm25 = ...
    localHolmAdjust( ...
    omnibusTable.P_Friedman_Raw);

omnibusTable.Significant_Holm25 = ...
    omnibusTable.P_Friedman_Holm25 < alpha;

%% ============================================================
% OPTIONAL CONSERVATIVE SENSITIVITY:
% HOLM ACROSS ALL 375 PAIRWISE TESTS
%
% Main interpretation will still use:
%
%   omnibus Holm-25
%   +
%   within-family Holm-15
%
% This all-375 column is retained as a conservative sensitivity
% analysis only.
% ============================================================

pairwiseTable.P_Wilcoxon_Holm375 = ...
    localHolmAdjust( ...
    pairwiseTable.P_Wilcoxon_Raw);

pairwiseTable.Significant_Holm375 = ...
    pairwiseTable.P_Wilcoxon_Holm375 < alpha;

%% ============================================================
% MARK PAIRWISE RESULTS WHOSE OMNIBUS FAMILY PASSED HOLM-25
% ============================================================

pairwiseTable.OmnibusSignificant_Holm25 = ...
    false(height(pairwiseTable),1);

for f = 1:height(omnibusTable)

    idx = ...
        pairwiseTable.FamilyID == ...
        omnibusTable.FamilyID(f);

    pairwiseTable.OmnibusSignificant_Holm25(idx) = ...
        omnibusTable.Significant_Holm25(f);
end

pairwiseTable.PrimaryPairwiseSignificant = ...
    pairwiseTable.OmnibusSignificant_Holm25 & ...
    pairwiseTable.Significant_Holm15;

%% ============================================================
% CHECKPOINT AGGREGATE AUDIT
% ============================================================

checkpointSummary = [];

for c = 1:numel(checkpoints)

    N = ...
        checkpoints(c);

    idx = ...
        stabilityTable.N==N;

    S = ...
        stabilityTable(idx,:);

    newRow = table( ...
        N, ...
        mean(S.SpearmanToN50), ...
        median(S.SpearmanToN50), ...
        min(S.SpearmanToN50), ...
        max(S.SpearmanToN50), ...
        nnz(S.WinnerMatchesFinal), ...
        height(S), ...
        mean(S.MaxAbsMeanRankShift), ...
        max(S.MaxAbsMeanRankShift), ...
        ...
        'VariableNames',{ ...
        'N', ...
        'MeanSpearmanToN50', ...
        'MedianSpearmanToN50', ...
        'MinimumSpearmanToN50', ...
        'MaximumSpearmanToN50', ...
        'WinnerMatchCount', ...
        'NumberOfFamilies', ...
        'MeanMaxAbsRankShift', ...
        'WorstMaxAbsRankShift'});

    checkpointSummary = ...
        [checkpointSummary;newRow]; %#ok<AGROW>
end

%% ============================================================
% AUDITS
% ============================================================

assert(height(omnibusTable)==25);

assert(height(pairwiseTable)== ...
    25*15);

assert(height(stabilityTable)== ...
    25*5);

assert(height(checkpointRankTable)== ...
    25*5*6);

assert(all( ...
    omnibusTable.Kendall_W >= -1e-12 & ...
    omnibusTable.Kendall_W <= 1+1e-12));

assert(all( ...
    stabilityTable.SpearmanToN50 >= -1-1e-12 & ...
    stabilityTable.SpearmanToN50 <= 1+1e-12));

assert(all( ...
    pairwiseTable.RankBiserial >= -1-1e-12 & ...
    pairwiseTable.RankBiserial <= 1+1e-12));

assert(all(isfinite( ...
    pairwiseTable.MedianDelta_AminusB_Raw)));

assert(all(isfinite( ...
    pairwiseTable.RawMedianCI95_Low)));

assert(all(isfinite( ...
    pairwiseTable.RawMedianCI95_High)));

%% ============================================================
% SAVE TABLES
% ============================================================

omnibusFile = fullfile( ...
    analysisDir, ...
    'friedman_omnibus_25.csv');

pairwiseFile = fullfile( ...
    analysisDir, ...
    'wilcoxon_pairwise_375.csv');

rankFile = fullfile( ...
    analysisDir, ...
    'rank_checkpoint_methods_750.csv');

stabilityFile = fullfile( ...
    analysisDir, ...
    'rank_stability_125.csv');

checkpointFile = fullfile( ...
    analysisDir, ...
    'rank_stability_checkpoint_summary.csv');

writetable( ...
    omnibusTable, ...
    omnibusFile);

writetable( ...
    pairwiseTable, ...
    pairwiseFile);

writetable( ...
    checkpointRankTable, ...
    rankFile);

writetable( ...
    stabilityTable, ...
    stabilityFile);

writetable( ...
    checkpointSummary, ...
    checkpointFile);

save( ...
    fullfile( ...
    analysisDir, ...
    'montecarlo_statistics_complete.mat'), ...
    'omnibusTable', ...
    'pairwiseTable', ...
    'checkpointRankTable', ...
    'stabilityTable', ...
    'checkpointSummary', ...
    'methods', ...
    'metrics', ...
    'metricLabels', ...
    'snrLevels_dB', ...
    'checkpoints', ...
    'alpha', ...
    'nBootstrap', ...
    '-v7.3');

%% ============================================================
% CONSOLE: OMNIBUS
% ============================================================

fprintf('\n\n');
fprintf('============================================================\n');
fprintf('FRIEDMAN OMNIBUS RESULTS -- N = 50\n');
fprintf('============================================================\n');

disp( ...
    omnibusTable(:,{ ...
    'SNR_dB', ...
    'MetricLabel', ...
    'P_Friedman_Raw', ...
    'P_Friedman_Holm25', ...
    'Kendall_W', ...
    'Winner_N50', ...
    'Significant_Holm25'}));

%% ============================================================
% CONSOLE: RANK STABILITY
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('RANK CONVERGENCE TOWARD N = 50\n');
fprintf('============================================================\n');

disp(checkpointSummary);

%% ============================================================
% GLOBAL SUMMARY
% ============================================================

nOmnibusSignificantRaw = ...
    nnz( ...
    omnibusTable.P_Friedman_Raw < alpha);

nOmnibusSignificantHolm = ...
    nnz( ...
    omnibusTable.Significant_Holm25);

nPrimaryPairwise = ...
    nnz( ...
    pairwiseTable.PrimaryPairwiseSignificant);

nAll375Significant = ...
    nnz( ...
    pairwiseTable.Significant_Holm375);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STATISTICAL AUDIT SUMMARY\n');
fprintf('============================================================\n');

fprintf('Friedman tests                         = %d\n', ...
    height(omnibusTable));

fprintf('Raw significant Friedman tests         = %d / 25\n', ...
    nOmnibusSignificantRaw);

fprintf('Holm-25 significant Friedman tests     = %d / 25\n', ...
    nOmnibusSignificantHolm);

fprintf('\n');

fprintf('Pairwise Wilcoxon comparisons          = %d\n', ...
    height(pairwiseTable));

fprintf(['Primary significant pairwise results  = %d / %d\n'], ...
    nPrimaryPairwise, ...
    height(pairwiseTable));

fprintf(['Holm-all-375 significant sensitivity  = %d / %d\n'], ...
    nAll375Significant, ...
    height(pairwiseTable));

fprintf('\n');

fprintf('Kendall W range                        = %.6f -- %.6f\n', ...
    min(omnibusTable.Kendall_W), ...
    max(omnibusTable.Kendall_W));

fprintf('Rank-biserial range                    = %.6f -- %.6f\n', ...
    min(pairwiseTable.RankBiserial), ...
    max(pairwiseTable.RankBiserial));

fprintf('\n');

fprintf('Output directory:\n%s\n', ...
    analysisDir);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09D-1 COMPLETE: PASS\n');
fprintf('============================================================\n');


%% ============================================================
% LOCAL FUNCTION
% BUILD EXACT PAIRED MATRIX
% ============================================================

function X = localBuildPairedMatrix( ...
    T,targetSNR,metricName,seeds,methods)

    nSeeds = ...
        numel(seeds);

    nMethods = ...
        numel(methods);

    X = ...
        nan(nSeeds,nMethods);

    metricColumn = ...
        char(metricName);

    for n = 1:nSeeds

        for m = 1:nMethods

            idx = ...
                T.BaseSeed == seeds(n) & ...
                T.TargetSNR_dB == targetSNR & ...
                T.Method == methods(m);

            assert(nnz(idx)==1, ...
                ['Expected exactly one result for ' ...
                 'seed/SNR/method block.']);

            value = ...
                T.(metricColumn)(idx);

            X(n,m) = ...
                double(value);
        end
    end
end


%% ============================================================
% LOCAL FUNCTION
% FRIEDMAN RANKS + KENDALL W
%
% Input X is already oriented so larger = better.
%
% We assign:
%
%   rank 1 = best
%   rank 6 = worst
%
% Kendall W is tie corrected.
% ============================================================

function [rankMatrix,W] = ...
    localFriedmanRankStatistics(X)

    X = ...
        double(X);

    [N,k] = ...
        size(X);

    rankMatrix = ...
        zeros(N,k);

    tieTerm = ...
        0;

    for n = 1:N

        row = ...
            X(n,:);

        % Negative sign converts:
        %
        % larger performance -> smaller ranking value
        %
        % hence rank 1 = best.

        rankMatrix(n,:) = ...
            localAverageRanks( ...
            -row);

        tieTerm = ...
            tieTerm + ...
            localTieTerm(row);
    end

    rankSums = ...
        sum(rankMatrix,1);

    expectedRankSum = ...
        N*(k+1)/2;

    S = ...
        sum( ...
        (rankSums-expectedRankSum).^2);

    denominator = ...
        N^2*(k^3-k) - ...
        N*tieTerm;

    if denominator <= 0

        W = ...
            NaN;

    else

        W = ...
            12*S / ...
            denominator;
    end

    % Defensive numerical clipping only.
    W = ...
        min(max(W,0),1);
end


%% ============================================================
% LOCAL FUNCTION
% AVERAGE RANKS WITH EXACT TIES
% ============================================================

function ranks = ...
    localAverageRanks(x)

    x = ...
        double(x(:));

    [sortedValues,order] = ...
        sort(x,'ascend');

    ranksSorted = ...
        zeros(size(x));

    i = 1;

    while i <= numel(x)

        j = i;

        while j < numel(x) && ...
                sortedValues(j+1) == ...
                sortedValues(i)

            j = ...
                j+1;
        end

        averageRank = ...
            mean(i:j);

        ranksSorted(i:j) = ...
            averageRank;

        i = ...
            j+1;
    end

    ranks = ...
        zeros(size(x));

    ranks(order) = ...
        ranksSorted;

    ranks = ...
        ranks.';
end


%% ============================================================
% LOCAL FUNCTION
% TIE TERM FOR KENDALL W
%
% For every tied group of size t:
%
%       t^3 - t
% ============================================================

function tieTerm = ...
    localTieTerm(x)

    x = ...
        sort(double(x(:)));

    tieTerm = ...
        0;

    i = 1;

    while i <= numel(x)

        j = i;

        while j < numel(x) && ...
                x(j+1) == x(i)

            j = ...
                j+1;
        end

        t = ...
            j-i+1;

        if t > 1

            tieTerm = ...
                tieTerm + ...
                (t^3-t);
        end

        i = ...
            j+1;
    end
end


%% ============================================================
% LOCAL FUNCTION
% WINNER SET FROM MEAN RANKS
% ============================================================

function winnerSet = ...
    localWinnerSet(meanRanks,methods)

    bestRank = ...
        min(meanRanks);

    tolerance = ...
        1e-12;

    winnerSet = ...
        methods( ...
        abs(meanRanks-bestRank) <= tolerance);
end


%% ============================================================
% LOCAL FUNCTION
% MATCHED-PAIRS RANK-BISERIAL CORRELATION
%
% Input d:
%   positive = Method A better
%   negative = Method B better
%
% r_rb =
% (W+ - W-) / (W+ + W-)
% ============================================================

function r = ...
    localMatchedRankBiserial(d)

    d = ...
        double(d(:));

    d = ...
        d(d~=0);

    if isempty(d)

        r = ...
            0;

        return;
    end

    absRanks = ...
        localAverageRanks(abs(d));

    absRanks = ...
        absRanks(:);

    wPositive = ...
        sum( ...
        absRanks(d>0));

    wNegative = ...
        sum( ...
        absRanks(d<0));

    denominator = ...
        wPositive+wNegative;

    if denominator==0

        r = ...
            0;

    else

        r = ...
            (wPositive-wNegative) / ...
            denominator;
    end
end


%% ============================================================
% LOCAL FUNCTION
% HOLM STEP-DOWN ADJUSTMENT
% ============================================================

function adjusted = ...
    localHolmAdjust(p)

    p = ...
        double(p(:));

    m = ...
        numel(p);

    [pSorted,order] = ...
        sort(p,'ascend');

    adjustedSorted = ...
        zeros(m,1);

    runningMax = ...
        0;

    for i = 1:m

        candidate = ...
            (m-i+1) * ...
            pSorted(i);

        candidate = ...
            min(candidate,1);

        runningMax = ...
            max( ...
            runningMax, ...
            candidate);

        adjustedSorted(i) = ...
            runningMax;
    end

    adjusted = ...
        zeros(m,1);

    adjusted(order) = ...
        adjustedSorted;
end


%% ============================================================
% LOCAL FUNCTION
% SPEARMAN CORRELATION
% ============================================================

function rho = ...
    localSpearman(x,y)

    x = ...
        double(x(:));

    y = ...
        double(y(:));

    rx = ...
        localAverageRanks(x);

    ry = ...
        localAverageRanks(y);

    rx = ...
        rx(:);

    ry = ...
        ry(:);

    rx = ...
        rx-mean(rx);

    ry = ...
        ry-mean(ry);

    denominator = ...
        norm(rx)*norm(ry);

    if denominator==0

        if isequal(x,y)

            rho = ...
                1;

        else

            rho = ...
                0;
        end

    else

        rho = ...
            dot(rx,ry) / ...
            denominator;
    end

    rho = ...
        min(max(rho,-1),1);
end


%% ============================================================
% LOCAL FUNCTION
% PERCENTILE BOOTSTRAP CONFIDENCE INTERVAL
%
% No Statistics Toolbox percentile helper is required.
% ============================================================

function ci = ...
    localPercentileCI(values,confidencePercent)

    values = ...
        sort(double(values(:)));

    alphaTail = ...
        (100-confidencePercent)/2;

    lowerPercent = ...
        alphaTail;

    upperPercent = ...
        100-alphaTail;

    ci = [ ...
        localPercentile(values,lowerPercent), ...
        localPercentile(values,upperPercent)];
end


%% ============================================================
% LOCAL FUNCTION
% LINEAR-INTERPOLATED PERCENTILE
% ============================================================

function value = ...
    localPercentile(sortedValues,p)

    n = ...
        numel(sortedValues);

    assert(n>=1);

    if n==1

        value = ...
            sortedValues(1);

        return;
    end

    position = ...
        1 + ...
        (n-1)*(p/100);

    lowerIndex = ...
        floor(position);

    upperIndex = ...
        ceil(position);

    if lowerIndex==upperIndex

        value = ...
            sortedValues(lowerIndex);

    else

        fraction = ...
            position-lowerIndex;

        value = ...
            sortedValues(lowerIndex) + ...
            fraction * ...
            ( ...
            sortedValues(upperIndex)- ...
            sortedValues(lowerIndex));
    end
end