clear;
close all;
clc;

%% ============================================================
% STEP 09B-6
% FINAL EXPANDED PAIRED MONTE CARLO FORWARD STUDY
%
% 50 base seeds
% x 5 target SNR levels
% =
% 250 paired RF conditions
%
% Each base seed requires ONE heterogeneous k-Wave simulation.
%
% For each seed:
%
%   p_meas(SNR) = p_system + beta(SNR) * n_hat
%
% where n_hat is a single frozen unit-RMS AWGN realization.
%
% CHECKPOINT / RESUME SAFE.
% ============================================================

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

rootOut = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step09_montecarlo');

seedOutDir = fullfile( ...
    rootOut, ...
    'forward_seeds');

mediumDir = fullfile( ...
    rootOut, ...
    'medium_maps');

if ~exist(seedOutDir,'dir')
    mkdir(seedOutDir);
end

if ~exist(mediumDir,'dir')
    mkdir(mediumDir);
end

sourceFile = fullfile( ...
    rootOut, ...
    'canonical_three_line_192x192.mat');

assert(isfile(sourceFile), ...
    'Frozen canonical three-line source not found.');

%% ============================================================
% FROZEN STUDY DESIGN
% ============================================================

baseSeeds = ...
    (1:50).';

snrLevels_dB = ...
    [5 10 15 20 30];

stabilityCheckpoints = ...
    [10 20 30 40 50];

Nseeds = ...
    numel(baseSeeds);

Nsnr = ...
    numel(snrLevels_dB);

expectedConditions = ...
    Nseeds*Nsnr;

%% ============================================================
% FROZEN PHYSICS
% ============================================================

Nx = 192;
Ny = 192;

dx = 50e-6;
dy = 50e-6;

CFL = 0.20;

simulationEndTime = ...
    16e-6;

PMLSize = ...
    20;

fDesign = ...
    6e6;

sensorRadius = ...
    4.20e-3;

numReceivers = ...
    128;

elementWidth = ...
    0.20e-3;

centerFrequency = ...
    2.0e6;

fractionalBandwidth = ...
    80;

alphaCoeff = ...
    0.75;

alphaPower = ...
    1.5;

%% ============================================================
% EXECUTION POLICY
% ============================================================

forceRerun = ...
    false;

schemaVersion = ...
    "revision_mc_forward_v1";

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09B-6: FINAL MONTE CARLO FORWARD STUDY\n');
fprintf('============================================================\n');

fprintf('Base seeds                = %d\n',Nseeds);
fprintf('SNR levels / seed         = %d\n',Nsnr);
fprintf('Total RF conditions       = %d\n',expectedConditions);

fprintf('\nSNR levels [dB]           = ');
fprintf('%g ',snrLevels_dB);
fprintf('\n');

fprintf('Stability checkpoints     = ');
fprintf('%d ',stabilityCheckpoints);
fprintf('\n');

fprintf('\nForce rerun               = %d\n',forceRerun);
fprintf('Checkpointing             = ON\n');

%% ============================================================
% LOAD FROZEN SOURCE
% ============================================================

P = load( ...
    sourceFile, ...
    'p0', ...
    'meta');

p0Frozen = ...
    double(P.p0);

sourceMeta = ...
    P.meta; %#ok<NASGU>

assert( ...
    isequal(size(p0Frozen),[Nx Ny]), ...
    'Frozen-source dimensions are invalid.');

%% ============================================================
% RUN COUNTERS
% ============================================================

computedSeeds = ...
    0;

reusedSeeds = ...
    0;

studyTimer = ...
    tic;

%% ============================================================
% SEED LOOP
% ============================================================

for q = 1:Nseeds

    baseSeed = ...
        baseSeeds(q);

    seedFile = fullfile( ...
        seedOutDir, ...
        sprintf( ...
        'mc_forward_seed%03d.mat', ...
        baseSeed));

    fprintf('\n\n');
    fprintf('############################################################\n');
    fprintf('MONTE CARLO SEED %d / %d\n', ...
        q,Nseeds);
    fprintf('Base seed = %d\n',baseSeed);
    fprintf('############################################################\n');

    %% ========================================================
    % CHECKPOINT
    % =========================================================

    if ~forceRerun && isfile(seedFile)

        try

            C = load( ...
                seedFile, ...
                'schemaVersionSaved', ...
                'seedTable');

            if isfield(C,'schemaVersionSaved') && ...
                    string(C.schemaVersionSaved) == schemaVersion && ...
                    isfield(C,'seedTable') && ...
                    height(C.seedTable)==Nsnr

                fprintf('Checkpoint valid -> REUSED.\n');

                reusedSeeds = ...
                    reusedSeeds + 1;

                continue;
            end

        catch ME

            fprintf( ...
                'Checkpoint invalid (%s); recomputing.\n', ...
                ME.message);
        end
    end

    computedSeeds = ...
        computedSeeds + 1;

    %% ========================================================
    % RANDOM-STREAM SCHEDULE
    % =========================================================

    noiseSeed = ...
        baseSeed + 300000;

    %% ========================================================
    % GENERATE PRESPECIFIED HETEROGENEOUS MEDIUM
    % =========================================================

    [mediumExpected,mediumMeta] = ...
        makePublicationMonteCarloMedium( ...
        Nx,Ny,dx,dy,baseSeed);

    sound_speed = ...
        mediumExpected.sound_speed;

    density = ...
        mediumExpected.density;

    cExpected = ...
        double(sound_speed);

    rhoExpected = ...
        double(density);

    cExpectedMean = ...
        mean(cExpected(:));

    cExpectedStd = ...
        std(cExpected(:));

    cExpectedMin = ...
        min(cExpected(:));

    cExpectedMax = ...
        max(cExpected(:));

    rhoExpectedMean = ...
        mean(rhoExpected(:));

    rhoExpectedStd = ...
        std(rhoExpected(:));

    rhoExpectedMin = ...
        min(rhoExpected(:));

    rhoExpectedMax = ...
        max(rhoExpected(:));

    expectedCorr = ...
        corr( ...
        cExpected(:), ...
        rhoExpected(:));

    expectedPPW = ...
        min( ...
        cExpectedMin/(dx*fDesign), ...
        cExpectedMin/(dy*fDesign));

    fprintf('\nPrespecified medium:\n');

    fprintf( ...
        'c mean/std/min/max   = %.4f / %.4f / %.4f / %.4f\n', ...
        cExpectedMean, ...
        cExpectedStd, ...
        cExpectedMin, ...
        cExpectedMax);

    fprintf( ...
        'rho mean/std         = %.4f / %.4f\n', ...
        rhoExpectedMean, ...
        rhoExpectedStd);

    fprintf( ...
        'corr(c,rho)          = %.6f\n', ...
        expectedCorr);

    fprintf( ...
        'PPW @ 6 MHz          = %.6f\n', ...
        expectedPPW);

    assert(cExpectedStd > 15 && cExpectedStd < 25);
    assert(rhoExpectedStd > 10 && rhoExpectedStd < 20);

    assert(expectedPPW >= 4, ...
        'Seed %d fails the PPW criterion.',baseSeed);

    assert( ...
        mediumMeta.sound_speed_clipped_pixels == 0, ...
        'Sound-speed clipping occurred for seed %d.',baseSeed);

    assert( ...
        mediumMeta.density_clipped_pixels == 0, ...
        'Density clipping occurred for seed %d.',baseSeed);

    %% ========================================================
    % SAVE DIRECT PATBOX MEDIUM MAP
    % =========================================================

    mediumMapFile = fullfile( ...
        mediumDir, ...
        sprintf( ...
        'montecarlo_medium_seed%03d.mat', ...
        baseSeed));

    save( ...
        mediumMapFile, ...
        'sound_speed', ...
        'density', ...
        'mediumMeta', ...
        '-v7.3');

    %% ========================================================
    % RUN ONE k-WAVE FORWARD SIMULATION
    % =========================================================

    fprintf('\nRunning heterogeneous k-Wave forward...\n');

    forwardTimer = ...
        tic;

    simBase = patSimulate( ...
        sourceFile, ...
        ...
        'SourceModel','initial_pressure_mat', ...
        'InitialPressureVariable','p0', ...
        ...
        'GridSizeX',Nx, ...
        'GridSizeY',Ny, ...
        'Dx',dx, ...
        'Dy',dy, ...
        ...
        'CFL',CFL, ...
        'SimulationEndTime',simulationEndTime, ...
        ...
        'PMLSize',PMLSize, ...
        'DataCast','single', ...
        'PlotSimulation',false, ...
        'SmoothInitialPressure',false, ...
        ...
        'MinFrequency',0, ...
        'MaxFrequency',fDesign, ...
        ...
        'MediumModel','mat', ...
        'MediumMapPath',mediumMapFile, ...
        ...
        'AlphaCoeff',alphaCoeff, ...
        'AlphaPower',alphaPower, ...
        'AlphaMode','full', ...
        ...
        'SensorType','circular', ...
        'SensorModel','kwave_array', ...
        'NumTransducers',numReceivers, ...
        'SensorRadius',sensorRadius, ...
        'ElementWidth',elementWidth, ...
        'ElementIntegrationPoints',0, ...
        'SensorArcDeg',180, ...
        'SensorStartAngleDeg',-90, ...
        'SensorRotationDeg',0, ...
        ...
        'CenterFrequency',centerFrequency, ...
        'FractionalBandwidthPercent', ...
            fractionalBandwidth, ...
        ...
        'NoiseModel','none', ...
        ...
        'RandomSeed',baseSeed);

    forwardRuntime_s = ...
        toc(forwardTimer);

    %% ========================================================
    % SOURCE AUDIT
    % =========================================================

    pReference = ...
        double(simBase.p0_reference);

    sourceRelativeDifference = ...
        norm( ...
        pReference(:)-p0Frozen(:)) / ...
        (norm(p0Frozen(:))+eps);

    assert( ...
        sourceRelativeDifference < 1e-7, ...
        'Frozen source changed at seed %d.',baseSeed);

    %% ========================================================
    % MEDIUM INJECTION AUDIT
    % =========================================================

    cActual = ...
        double(simBase.medium.sound_speed);

    rhoActual = ...
        double(simBase.medium.density);

    cMapRelativeDifference = ...
        norm( ...
        cActual(:)-cExpected(:)) / ...
        (norm(cExpected(:))+eps);

    rhoMapRelativeDifference = ...
        norm( ...
        rhoActual(:)-rhoExpected(:)) / ...
        (norm(rhoExpected(:))+eps);

    cMean = ...
        mean(cActual(:));

    cStd = ...
        std(cActual(:));

    cMin = ...
        min(cActual(:));

    cMax = ...
        max(cActual(:));

    rhoMean = ...
        mean(rhoActual(:));

    rhoStd = ...
        std(rhoActual(:));

    rhoMin = ...
        min(rhoActual(:));

    rhoMax = ...
        max(rhoActual(:));

    cRhoCorr = ...
        corr( ...
        cActual(:), ...
        rhoActual(:));

    fprintf('\nForward-medium audit:\n');

    fprintf( ...
        'c std / rho std      = %.6f / %.6f\n', ...
        cStd,rhoStd);

    fprintf( ...
        'c-map difference     = %.3e\n', ...
        cMapRelativeDifference);

    fprintf( ...
        'rho-map difference   = %.3e\n', ...
        rhoMapRelativeDifference);

    assert(cStd > 15 && cStd < 25, ...
        'Sound-speed heterogeneity missing at seed %d.', ...
        baseSeed);

    assert(rhoStd > 10 && rhoStd < 20, ...
        'Density heterogeneity missing at seed %d.', ...
        baseSeed);

    assert(cMapRelativeDifference < 1e-7, ...
        'Incorrect sound-speed map at seed %d.', ...
        baseSeed);

    assert(rhoMapRelativeDifference < 1e-7, ...
        'Incorrect density map at seed %d.', ...
        baseSeed);

    assert( ...
        strcmpi( ...
        string(simBase.info.medium.model), ...
        "mat"), ...
        'MediumModel is not MAT.');

    %% ========================================================
    % ATTENUATION AUDIT
    % =========================================================

    assert( ...
        abs(double(simBase.medium.alpha_coeff)-alphaCoeff) ...
        < 1e-12);

    assert( ...
        abs(double(simBase.medium.alpha_power)-alphaPower) ...
        < 1e-12);

    %% ========================================================
    % GRID / TIME AUDIT
    % =========================================================

    dt = ...
        double(simBase.kgrid.dt);

    Nt = ...
        simBase.kgrid.Nt;

    tActual = ...
        double(simBase.kgrid.t_array(end));

    dtExpected = ...
        CFL * min(dx,dy) / cMax;

    dtRelativeError = ...
        abs(dt-dtExpected) / ...
        dtExpected;

    assert(dtRelativeError < 1e-10, ...
        'Time grid did not use realized c_max.');

    assert( ...
        abs(tActual-simulationEndTime) < 2*dt, ...
        'Simulation time window audit failed.');

    %% ========================================================
    % PPW AUDIT
    % =========================================================

    ppwAchieved = ...
        min( ...
        cMin/(dx*fDesign), ...
        cMin/(dy*fDesign));

    assert( ...
        ppwAchieved >= 4, ...
        'Seed %d fails PPW >= 4.',baseSeed);

    %% ========================================================
    % SENSOR AUDIT
    % =========================================================

    assert( ...
        strcmpi( ...
        string(simBase.info.sensor_model), ...
        "kwave_array"));

    assert( ...
        simBase.info.num_sensors == ...
        numReceivers);

    assert( ...
        abs( ...
        double(simBase.info.element_width_m)- ...
        elementWidth) < 1e-12);

    assert( ...
        abs( ...
        double(simBase.info.center_frequency_hz)- ...
        centerFrequency) < 1);

    assert( ...
        abs( ...
        double( ...
        simBase.info. ...
        fractional_bandwidth_percent)- ...
        fractionalBandwidth) < 1e-9);

    %% ========================================================
    % ACTUAL RECEIVER RING AUDIT
    % =========================================================

    positions = ...
        double( ...
        simBase.sensor_geometry.positions);

    if size(positions,1) ~= 2 && ...
            size(positions,2)==2

        positions = ...
            positions.';
    end

    assert(size(positions,1)==2);

    assert(size(positions,2)==numReceivers);

    theta = ...
        mod( ...
        atan2( ...
        positions(2,:), ...
        positions(1,:)), ...
        2*pi);

    theta = ...
        sort(theta);

    gaps = ...
        diff( ...
        [theta theta(1)+2*pi]);

    meanAngularGap_deg = ...
        mean(gaps)*180/pi;

    minAngularGap_deg = ...
        min(gaps)*180/pi;

    maxAngularGap_deg = ...
        max(gaps)*180/pi;

    idealAngularGap_deg = ...
        360/numReceivers;

    assert( ...
        abs( ...
        meanAngularGap_deg- ...
        idealAngularGap_deg) ...
        < 1e-6, ...
        'Actual receiver geometry is not the expected full ring.');

    %% ========================================================
    % SYSTEM RF
    % =========================================================

    pSystem = ...
        double( ...
        simBase.sensor_data_system.p);

    pClean = ...
        double( ...
        simBase.sensor_data_clean.p);

    assert(size(pSystem,1)==numReceivers);

    assert(size(pSystem,2)==Nt);

    assert(all(isfinite(pSystem(:))));

    systemRMS = ...
        rmsGlobal(pSystem);

    cleanSystemRelativeDifference = ...
        norm( ...
        pClean(:)-pSystem(:)) / ...
        (norm(pSystem(:))+eps);

    assert(systemRMS > 0);

    %% ========================================================
    % FROZEN NORMALIZED NOISE FOR THIS BASE SEED
    % =========================================================

    oldRng = ...
        rng;

    cleanupRng = ...
        onCleanup(@() rng(oldRng));

    rng(noiseSeed,'twister');

    noiseUnit = ...
        randn(size(pSystem));

    noiseUnit = ...
        noiseUnit / ...
        rmsGlobal(noiseUnit);

    clear cleanupRng;

    assert( ...
        abs(rmsGlobal(noiseUnit)-1) < 1e-12);

    %% ========================================================
    % FIVE PAIRED SNR CONDITIONS
    %
    % Do not store five redundant RF arrays.
    %
    % Exact recovery:
    %
    % p_measured =
    % p_system + beta(s) * noiseUnit
    % =========================================================

    beta = ...
        nan(Nsnr,1);

    achievedSNR_dB = ...
        nan(Nsnr,1);

    maxPairDifference = ...
        0;

    normalizedNoise = ...
        cell(Nsnr,1);

    for s = 1:Nsnr

        targetSNR = ...
            snrLevels_dB(s);

        beta(s) = ...
            systemRMS / ...
            10^(targetSNR/20);

        addedNoise = ...
            beta(s) .* ...
            noiseUnit;

        achievedSNR_dB(s) = ...
            20*log10( ...
            systemRMS / ...
            rmsGlobal(addedNoise));

        normalizedNoise{s} = ...
            addedNoise / ...
            rmsGlobal(addedNoise);
    end

    %% --------------------------------------------------------
    % Exact SNR calibration
    % ---------------------------------------------------------

    snrError = ...
        achievedSNR_dB - ...
        snrLevels_dB(:);

    assert( ...
        max(abs(snrError)) < 1e-10, ...
        'SNR calibration failed at seed %d.', ...
        baseSeed);

    %% --------------------------------------------------------
    % Exact pairing
    % ---------------------------------------------------------

    minNoiseCorrelation = ...
        1;

    for i = 1:Nsnr

        for j = i+1:Nsnr

            ni = ...
                normalizedNoise{i};

            nj = ...
                normalizedNoise{j};

            relativeDifference = ...
                norm(ni(:)-nj(:)) / ...
                (norm(ni(:))+eps);

            pairCorrelation = ...
                corr(ni(:),nj(:));

            maxPairDifference = ...
                max( ...
                maxPairDifference, ...
                relativeDifference);

            minNoiseCorrelation = ...
                min( ...
                minNoiseCorrelation, ...
                pairCorrelation);
        end
    end

    assert(maxPairDifference < 1e-12);

    assert( ...
        minNoiseCorrelation > 1-1e-12);

    %% ========================================================
    % PER-SEED SUMMARY TABLE
    % =========================================================

    isOriginalSeed = ...
        baseSeed <= 10;

    seedTable = table( ...
        repmat(baseSeed,Nsnr,1), ...
        repmat(isOriginalSeed,Nsnr,1), ...
        repmat(mediumMeta.sound_speed_seed,Nsnr,1), ...
        repmat(mediumMeta.density_seed,Nsnr,1), ...
        repmat(noiseSeed,Nsnr,1), ...
        snrLevels_dB(:), ...
        achievedSNR_dB, ...
        beta, ...
        repmat(systemRMS,Nsnr,1), ...
        repmat(cMean,Nsnr,1), ...
        repmat(cStd,Nsnr,1), ...
        repmat(cMin,Nsnr,1), ...
        repmat(cMax,Nsnr,1), ...
        repmat(rhoMean,Nsnr,1), ...
        repmat(rhoStd,Nsnr,1), ...
        repmat(rhoMin,Nsnr,1), ...
        repmat(rhoMax,Nsnr,1), ...
        repmat(cRhoCorr,Nsnr,1), ...
        repmat(dt*1e9,Nsnr,1), ...
        repmat(Nt,Nsnr,1), ...
        repmat(tActual*1e6,Nsnr,1), ...
        repmat(ppwAchieved,Nsnr,1), ...
        repmat(meanAngularGap_deg,Nsnr,1), ...
        repmat(minAngularGap_deg,Nsnr,1), ...
        repmat(maxAngularGap_deg,Nsnr,1), ...
        repmat(sourceRelativeDifference,Nsnr,1), ...
        repmat(cMapRelativeDifference,Nsnr,1), ...
        repmat(rhoMapRelativeDifference,Nsnr,1), ...
        repmat(maxPairDifference,Nsnr,1), ...
        repmat(minNoiseCorrelation,Nsnr,1), ...
        repmat(forwardRuntime_s,Nsnr,1), ...
        ...
        'VariableNames',{ ...
        'BaseSeed', ...
        'OriginalSeedSubset', ...
        'SoundSpeedSeed', ...
        'DensitySeed', ...
        'NoiseSeed', ...
        'TargetSNR_dB', ...
        'AchievedSNR_dB', ...
        'NoiseScale', ...
        'SystemRMS', ...
        'CMean_mps', ...
        'CStd_mps', ...
        'CMin_mps', ...
        'CMax_mps', ...
        'RhoMean_kgm3', ...
        'RhoStd_kgm3', ...
        'RhoMin_kgm3', ...
        'RhoMax_kgm3', ...
        'Corr_C_Rho', ...
        'dt_ns', ...
        'Nt', ...
        'TEnd_us', ...
        'PPW_6MHz', ...
        'MeanAngularGap_deg', ...
        'MinAngularGap_deg', ...
        'MaxAngularGap_deg', ...
        'SourceRelativeDifference', ...
        'CMapRelativeDifference', ...
        'RhoMapRelativeDifference', ...
        'MaxNoisePairDifference', ...
        'MinNoisePairCorrelation', ...
        'ForwardRuntime_s'});

    %% ========================================================
    % COMPACT REPRODUCIBLE RF SPECIFICATION
    % =========================================================

    rfSpecification = struct();

    rfSpecification.description = ...
        ['For each TargetSNR_dB, reconstruct measured RF as ' ...
         'sensor_data_system.p + NoiseScale * noiseUnit.'];

    rfSpecification.snr_levels_dB = ...
        snrLevels_dB;

    rfSpecification.noise_scale = ...
        beta;

    rfSpecification.noise_seed = ...
        noiseSeed;

    rfSpecification.noise_unit_rms = ...
        rmsGlobal(noiseUnit);

    rfSpecification.exact_pairing = ...
        true;

    %% ========================================================
    % CHECKPOINT SAVE
    % =========================================================

    schemaVersionSaved = ...
        schemaVersion;

    % Single precision is sufficient for storing the frozen
    % normalized noise realization and substantially reduces
    % checkpoint size.
    noiseUnitSaved = ...
        single(noiseUnit);

    save( ...
        seedFile, ...
        'schemaVersionSaved', ...
        'baseSeed', ...
        'simBase', ...
        'noiseUnitSaved', ...
        'beta', ...
        'achievedSNR_dB', ...
        'seedTable', ...
        'mediumMeta', ...
        'rfSpecification', ...
        '-v7.3');

    fprintf('\nSeed %d checkpoint saved.\n', ...
        baseSeed);

    fprintf( ...
        'Forward runtime       = %.2f s\n', ...
        forwardRuntime_s);

    fprintf( ...
        'PPW                   = %.4f\n', ...
        ppwAchieved);

    fprintf( ...
        'Max SNR error         = %.3e dB\n', ...
        max(abs(snrError)));

    fprintf( ...
        'Max noise-pair diff   = %.3e\n', ...
        maxPairDifference);

    %% ========================================================
    % PROGRESS ESTIMATE
    % =========================================================

    elapsed = ...
        toc(studyTimer);

    nHandled = ...
        computedSeeds + ...
        reusedSeeds;

    meanWallPerHandledSeed = ...
        elapsed / ...
        max(nHandled,1);

    remainingSeeds = ...
        Nseeds - ...
        nHandled;

    estimatedRemaining_min = ...
        remainingSeeds * ...
        meanWallPerHandledSeed / 60;

    fprintf( ...
        'Approx. remaining     = %.1f min\n', ...
        estimatedRemaining_min);

end

%% ============================================================
% GATHER ALL 50 CHECKPOINTS
% ============================================================

fprintf('\n\n');
fprintf('============================================================\n');
fprintf('GATHERING 250-CONDITION MASTER TABLE\n');
fprintf('============================================================\n');

masterTable = [];

for q = 1:Nseeds

    baseSeed = ...
        baseSeeds(q);

    seedFile = fullfile( ...
        seedOutDir, ...
        sprintf( ...
        'mc_forward_seed%03d.mat', ...
        baseSeed));

    assert(isfile(seedFile), ...
        'Missing production checkpoint for seed %d.', ...
        baseSeed);

    S = load( ...
        seedFile, ...
        'schemaVersionSaved', ...
        'seedTable');

    assert( ...
        string(S.schemaVersionSaved)==schemaVersion, ...
        'Wrong checkpoint schema at seed %d.', ...
        baseSeed);

    assert(height(S.seedTable)==Nsnr);

    masterTable = ...
        [masterTable;S.seedTable]; %#ok<AGROW>
end

%% ============================================================
% MASTER AUDIT
% ============================================================

assert(height(masterTable)==expectedConditions);

assert( ...
    numel(unique(masterTable.BaseSeed)) == ...
    Nseeds);

assert( ...
    numel(unique(masterTable.TargetSNR_dB)) == ...
    Nsnr);

%% ------------------------------------------------------------
% Exactly 50 conditions per SNR
% ------------------------------------------------------------

for s = 1:Nsnr

    targetSNR = ...
        snrLevels_dB(s);

    assert( ...
        nnz(masterTable.TargetSNR_dB==targetSNR) ...
        == Nseeds);
end

%% ------------------------------------------------------------
% Original seeds 1--10 retained
% ------------------------------------------------------------

originalSeeds = ...
    unique( ...
    masterTable.BaseSeed( ...
    masterTable.OriginalSeedSubset));

assert( ...
    isequal( ...
    originalSeeds(:), ...
    (1:10).'));

%% ------------------------------------------------------------
% SNR audit
% ------------------------------------------------------------

maxGlobalSNRError = ...
    max( ...
    abs( ...
    masterTable.AchievedSNR_dB - ...
    masterTable.TargetSNR_dB));

assert(maxGlobalSNRError < 1e-10);

%% ------------------------------------------------------------
% Medium audit
% ------------------------------------------------------------

assert(all( ...
    masterTable.CStd_mps > 15 & ...
    masterTable.CStd_mps < 25));

assert(all( ...
    masterTable.RhoStd_kgm3 > 10 & ...
    masterTable.RhoStd_kgm3 < 20));

assert(all( ...
    masterTable.CMapRelativeDifference < 1e-7));

assert(all( ...
    masterTable.RhoMapRelativeDifference < 1e-7));

%% ------------------------------------------------------------
% PPW audit
% ------------------------------------------------------------

assert(all( ...
    masterTable.PPW_6MHz >= 4));

%% ------------------------------------------------------------
% Receiver geometry
% ------------------------------------------------------------

assert( ...
    max( ...
    abs( ...
    masterTable.MeanAngularGap_deg - ...
    360/128)) < 1e-6);

%% ------------------------------------------------------------
% Pairing
% ------------------------------------------------------------

assert(all( ...
    masterTable.MaxNoisePairDifference < 1e-12));

assert(all( ...
    masterTable.MinNoisePairCorrelation > 1-1e-12));

%% ============================================================
% SAVE MASTER FORWARD TABLE
% ============================================================

masterCsv = fullfile( ...
    rootOut, ...
    'montecarlo_forward_summary_250.csv');

masterMat = fullfile( ...
    rootOut, ...
    'montecarlo_forward_summary_250.mat');

writetable( ...
    masterTable, ...
    masterCsv);

save( ...
    masterMat, ...
    'masterTable', ...
    'schemaVersion', ...
    'snrLevels_dB', ...
    'stabilityCheckpoints', ...
    '-v7.3');

%% ============================================================
% MEDIUM REALIZATION SUMMARY
%
% One row per seed rather than five duplicate SNR rows.
% ============================================================

mediumSummary = ...
    masterTable( ...
    masterTable.TargetSNR_dB==snrLevels_dB(1), ...
    { ...
    'BaseSeed', ...
    'SoundSpeedSeed', ...
    'DensitySeed', ...
    'CMean_mps', ...
    'CStd_mps', ...
    'CMin_mps', ...
    'CMax_mps', ...
    'RhoMean_kgm3', ...
    'RhoStd_kgm3', ...
    'RhoMin_kgm3', ...
    'RhoMax_kgm3', ...
    'Corr_C_Rho', ...
    'dt_ns', ...
    'Nt', ...
    'TEnd_us', ...
    'PPW_6MHz', ...
    'ForwardRuntime_s'});

writetable( ...
    mediumSummary, ...
    fullfile( ...
    rootOut, ...
    'montecarlo_medium_summary_50.csv'));

%% ============================================================
% FINAL CONSOLE AUDIT
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('EXPANDED MONTE CARLO FORWARD AUDIT\n');
fprintf('============================================================\n');

fprintf('Completed seeds            = %d / %d\n', ...
    numel(unique(masterTable.BaseSeed)), ...
    Nseeds);

fprintf('Completed RF conditions    = %d / %d\n', ...
    height(masterTable), ...
    expectedConditions);

fprintf('Computed this run          = %d\n', ...
    computedSeeds);

fprintf('Reused checkpoints         = %d\n', ...
    reusedSeeds);

fprintf('\n');

fprintf('Maximum SNR error          = %.12e dB\n', ...
    maxGlobalSNRError);

fprintf('Maximum c-map difference   = %.12e\n', ...
    max(masterTable.CMapRelativeDifference));

fprintf('Maximum rho-map difference = %.12e\n', ...
    max(masterTable.RhoMapRelativeDifference));

fprintf('Maximum noise-pair diff    = %.12e\n', ...
    max(masterTable.MaxNoisePairDifference));

fprintf('Minimum noise correlation  = %.12f\n', ...
    min(masterTable.MinNoisePairCorrelation));

fprintf('\n');

fprintf('c std range                = %.6f -- %.6f m/s\n', ...
    min(mediumSummary.CStd_mps), ...
    max(mediumSummary.CStd_mps));

fprintf('rho std range              = %.6f -- %.6f kg/m^3\n', ...
    min(mediumSummary.RhoStd_kgm3), ...
    max(mediumSummary.RhoStd_kgm3));

fprintf('c min across realizations  = %.6f m/s\n', ...
    min(mediumSummary.CMin_mps));

fprintf('c max across realizations  = %.6f m/s\n', ...
    max(mediumSummary.CMax_mps));

fprintf('Minimum PPW                = %.6f\n', ...
    min(mediumSummary.PPW_6MHz));

fprintf('\n');

fprintf('Mean forward runtime       = %.2f s / seed\n', ...
    mean(mediumSummary.ForwardRuntime_s));

fprintf('Total forward runtime      = %.2f min\n', ...
    sum(mediumSummary.ForwardRuntime_s)/60);

fprintf('Total script wall time     = %.2f min\n', ...
    toc(studyTimer)/60);

fprintf('\n');
fprintf('Master table:\n%s\n',masterCsv);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09B-6 COMPLETE: PASS\n');
fprintf('============================================================\n');


%% ============================================================
% LOCAL FUNCTION
% ============================================================

function r = rmsGlobal(x)

    x = double(x);

    r = ...
        sqrt(mean(x(:).^2));

end