clear;
close all;
clc;

%% ============================================================
% STEP 09B-3
% Validate exact paired-noise rescaling.
%
% IMPORTANT:
% This is an acquisition-model UNIT TEST only.
% It is NOT one of the final Monte Carlo realizations.
%
% We reuse an existing successful system-level RF record
% solely as a deterministic numerical test vector.
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

outDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step09_montecarlo');

if ~exist(outDir,'dir')
    mkdir(outDir);
end

%% ============================================================
% LOAD EXISTING SUCCESSFUL RF RECORD
% ============================================================

referenceFile = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step03_sequential_forward', ...
    'D5_noise.mat');

assert(isfile(referenceFile), ...
    'Reference D5 simulation not found.');

S = load(referenceFile,'sim');

sim = S.sim;

assert(isfield(sim,'sensor_data_system'));
assert(isfield(sim.sensor_data_system,'p'));

assert(isfield(sim,'sensor_data'));
assert(isfield(sim.sensor_data,'p'));

pSystem = ...
    double(sim.sensor_data_system.p);

pMeasured20Original = ...
    double(sim.sensor_data.p);

assert( ...
    isequal( ...
    size(pSystem), ...
    size(pMeasured20Original)));

%% ============================================================
% EXTRACT ORIGINAL ~20-dB NOISE REALIZATION
% ============================================================

noise20Original = ...
    pMeasured20Original - ...
    pSystem;

systemRMS = ...
    rmsGlobal(pSystem);

noise20RMS = ...
    rmsGlobal(noise20Original);

originalSNR = ...
    20*log10( ...
    systemRMS/noise20RMS);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09B-3: EXACT NOISE-PAIRING VALIDATION\n');
fprintf('============================================================\n');

fprintf('RF dimensions            = %d x %d\n', ...
    size(pSystem,1), ...
    size(pSystem,2));

fprintf('System RMS               = %.12e\n', ...
    systemRMS);

fprintf('Original noise RMS       = %.12e\n', ...
    noise20RMS);

fprintf('Original achieved SNR    = %.9f dB\n', ...
    originalSNR);

assert(abs(originalSNR-20) < 1e-4, ...
    'Reference RF is not sufficiently close to the expected 20-dB case.');

%% ============================================================
% DEFINE ONE FROZEN NORMALIZED NOISE REALIZATION
%
% Unit-RMS representation:
%
%       nHat = n / RMS(n)
%
% This pattern is NEVER regenerated when SNR changes.
% ============================================================

noiseUnit = ...
    noise20Original / ...
    noise20RMS;

noiseUnitRMS = ...
    rmsGlobal(noiseUnit);

fprintf('Normalized-noise RMS     = %.12f\n', ...
    noiseUnitRMS);

assert(abs(noiseUnitRMS-1) < 1e-12, ...
    'Normalized noise does not have unit RMS.');

%% ============================================================
% THREE-SNR PILOT
% ============================================================

snrTest_dB = ...
    [5 20 30];

nSNR = ...
    numel(snrTest_dB);

measuredRF = ...
    cell(nSNR,1);

addedNoise = ...
    cell(nSNR,1);

normalizedNoise = ...
    cell(nSNR,1);

beta = ...
    nan(nSNR,1);

achievedSNR = ...
    nan(nSNR,1);

noiseRMS = ...
    nan(nSNR,1);

for k = 1:nSNR

    targetSNR = ...
        snrTest_dB(k);

    %% --------------------------------------------------------
    % Exact global-SNR scaling
    %
    % targetSNR =
    % 20 log10( RMS(system) / RMS(noise) )
    %
    % Since noiseUnit has RMS = 1:
    %
    % beta =
    % RMS(system) / 10^(targetSNR/20)
    % ---------------------------------------------------------

    beta(k) = ...
        systemRMS / ...
        10^(targetSNR/20);

    addedNoise{k} = ...
        beta(k) .* ...
        noiseUnit;

    measuredRF{k} = ...
        pSystem + ...
        addedNoise{k};

    noiseRMS(k) = ...
        rmsGlobal( ...
        addedNoise{k});

    achievedSNR(k) = ...
        20*log10( ...
        systemRMS / ...
        noiseRMS(k));

    normalizedNoise{k} = ...
        addedNoise{k} / ...
        noiseRMS(k);
end

%% ============================================================
% SNR AUDIT
% ============================================================

fprintf('\n');
fprintf('SNR AUDIT\n');
fprintf('------------------------------------------------------------\n');

for k = 1:nSNR

    fprintf( ...
        ['Target %5.1f dB | beta %.12e | ' ...
         'noise RMS %.12e | achieved %.9f dB\n'], ...
        snrTest_dB(k), ...
        beta(k), ...
        noiseRMS(k), ...
        achievedSNR(k));
end

snrError = ...
    achievedSNR - ...
    snrTest_dB(:);

fprintf('\nMaximum |SNR error| = %.12e dB\n', ...
    max(abs(snrError)));

assert( ...
    max(abs(snrError)) < 1e-10, ...
    'Target-SNR calibration failed.');

%% ============================================================
% EXACT NORMALIZED-NOISE PAIRING AUDIT
% ============================================================

fprintf('\n');
fprintf('NORMALIZED-NOISE PAIRING\n');
fprintf('------------------------------------------------------------\n');

pairRows = [];

for i = 1:nSNR

    for j = i+1:nSNR

        ni = ...
            normalizedNoise{i};

        nj = ...
            normalizedNoise{j};

        relativeDifference = ...
            norm(ni(:)-nj(:)) / ...
            (norm(ni(:))+eps);

        correlation = ...
            corr(ni(:),nj(:));

        cosineSimilarity = ...
            dot(ni(:),nj(:)) / ...
            (norm(ni(:))*norm(nj(:))+eps);

        fprintf( ...
            ['%2d vs %2d dB | relative diff %.12e | ' ...
             'corr %.12f | cosine %.12f\n'], ...
            snrTest_dB(i), ...
            snrTest_dB(j), ...
            relativeDifference, ...
            correlation, ...
            cosineSimilarity);

        newRow = table( ...
            snrTest_dB(i), ...
            snrTest_dB(j), ...
            relativeDifference, ...
            correlation, ...
            cosineSimilarity, ...
            'VariableNames',{ ...
            'SNR1_dB', ...
            'SNR2_dB', ...
            'NormalizedNoiseRelativeDifference', ...
            'Correlation', ...
            'CosineSimilarity'});

        pairRows = ...
            [pairRows;newRow]; %#ok<AGROW>
    end
end

assert( ...
    max( ...
    pairRows.NormalizedNoiseRelativeDifference) ...
    < 1e-12, ...
    'Normalized noise realization changed across SNR.');

assert( ...
    min(pairRows.Correlation) > ...
    1-1e-12, ...
    'Noise-pattern correlation is not unity.');

assert( ...
    min(pairRows.CosineSimilarity) > ...
    1-1e-12, ...
    'Noise-pattern cosine similarity is not unity.');

%% ============================================================
% SCALING-RATIO AUDIT
%
% If the normalized pattern is identical:
%
% RMS(n_S1)/RMS(n_S2)
% =
% 10^((S2-S1)/20)
% ============================================================

fprintf('\n');
fprintf('NOISE-AMPLITUDE RATIO AUDIT\n');
fprintf('------------------------------------------------------------\n');

ratioRows = [];

for i = 1:nSNR

    for j = i+1:nSNR

        observedRatio = ...
            noiseRMS(i) / ...
            noiseRMS(j);

        expectedRatio = ...
            10^( ...
            (snrTest_dB(j)- ...
             snrTest_dB(i))/20);

        relError = ...
            abs( ...
            observedRatio-expectedRatio) / ...
            expectedRatio;

        fprintf( ...
            ['%2d vs %2d dB | observed %.9f | ' ...
             'expected %.9f | rel.err %.3e\n'], ...
            snrTest_dB(i), ...
            snrTest_dB(j), ...
            observedRatio, ...
            expectedRatio, ...
            relError);

        newRow = table( ...
            snrTest_dB(i), ...
            snrTest_dB(j), ...
            observedRatio, ...
            expectedRatio, ...
            relError, ...
            'VariableNames',{ ...
            'SNR1_dB', ...
            'SNR2_dB', ...
            'ObservedNoiseRMSRatio', ...
            'ExpectedNoiseRMSRatio', ...
            'RelativeError'});

        ratioRows = ...
            [ratioRows;newRow]; %#ok<AGROW>

        assert( ...
            relError < 1e-12, ...
            'Noise-amplitude ratio audit failed.');
    end
end

%% ============================================================
% 20-dB NUMERICAL CONSISTENCY CHECK
%
% IMPORTANT:
% The stored reference achieved approximately:
%
%     20.000000245 dB
%
% whereas the regenerated case below is calibrated to:
%
%     exactly 20.000000000 dB
%
% Therefore bitwise identity is neither expected nor required.
% The correct requirement is extremely small relative RF
% discrepancy.
% ============================================================

idx20 = ...
    find(snrTest_dB==20,1);

relativeRFRecoveryError = ...
    norm( ...
    measuredRF{idx20}(:)- ...
    pMeasured20Original(:)) / ...
    (norm(pMeasured20Original(:))+eps);

fprintf('\n');
fprintf('20-dB RF NUMERICAL CONSISTENCY\n');
fprintf('------------------------------------------------------------\n');

fprintf('Stored reference SNR     = %.9f dB\n', ...
    originalSNR);

fprintf('Regenerated target SNR   = %.9f dB\n', ...
    achievedSNR(idx20));

fprintf('Relative RF difference   = %.12e\n', ...
    relativeRFRecoveryError);

fprintf(['Note: exact bitwise reproduction is not expected because ' ...
         'the stored reference was calibrated to %.9f dB rather than ' ...
         'exactly 20.000000000 dB.\n'], ...
    originalSNR);

assert( ...
    relativeRFRecoveryError < 1e-7, ...
    '20-dB RF numerical consistency check failed.');

%% ============================================================
% OPTIONAL DIRECT ORIGINAL-NOISE NORMALIZATION CHECK
%
% The extracted stored noise itself should reproduce the same
% unit-RMS noise pattern used above.
% ============================================================

originalNormalizedNoise = ...
    noise20Original / ...
    rmsGlobal(noise20Original);

normalizationDifference = ...
    norm( ...
    originalNormalizedNoise(:)- ...
    noiseUnit(:)) / ...
    (norm(noiseUnit(:))+eps);

fprintf('\n');
fprintf('REFERENCE-NOISE NORMALIZATION CHECK\n');
fprintf('------------------------------------------------------------\n');

fprintf('Relative difference      = %.12e\n', ...
    normalizationDifference);

assert( ...
    normalizationDifference < 1e-14, ...
    'Reference-noise normalization is inconsistent.');

%% ============================================================
% SAVE UNIT-TEST RECORD
% ============================================================

pilot = struct();

pilot.reference_file = ...
    referenceFile;

pilot.note = ...
    ['Acquisition-model unit test only; not part of ' ...
     'the final Monte Carlo cohort.'];

pilot.snr_dB = ...
    snrTest_dB;

pilot.system_rms = ...
    systemRMS;

pilot.original_reference_snr_dB = ...
    originalSNR;

pilot.noise_unit = ...
    single(noiseUnit);

pilot.beta = ...
    beta;

pilot.noise_rms = ...
    noiseRMS;

pilot.achieved_snr_dB = ...
    achievedSNR;

pilot.maximum_snr_error_dB = ...
    max(abs(snrError));

pilot.pairing_table = ...
    pairRows;

pilot.amplitude_ratio_table = ...
    ratioRows;

pilot.relative_rf_difference_20dB = ...
    relativeRFRecoveryError;

pilot.reference_noise_normalization_difference = ...
    normalizationDifference;

%% ------------------------------------------------------------
% Save only compact unit-test information.
% Do not save every measured RF matrix here.
% ------------------------------------------------------------

save( ...
    fullfile( ...
        outDir, ...
        'noise_pairing_unit_test.mat'), ...
    'pilot', ...
    '-v7.3');

writetable( ...
    pairRows, ...
    fullfile( ...
        outDir, ...
        'noise_pairing_unit_test.csv'));

writetable( ...
    ratioRows, ...
    fullfile( ...
        outDir, ...
        'noise_amplitude_ratio_unit_test.csv'));

%% ============================================================
% FINAL
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('NOISE PAIRING: PASS\n');
fprintf('============================================================\n');

fprintf('Same system RF across SNR       : PASS\n');
fprintf('Exact target-SNR calibration    : PASS\n');
fprintf('Same normalized noise pattern   : PASS\n');
fprintf('Expected amplitude ratios       : PASS\n');
fprintf('20-dB RF numerical consistency  : PASS\n');

fprintf('\n');
fprintf('STEP 09B-3 COMPLETE\n');
fprintf('============================================================\n');


%% ============================================================
% LOCAL FUNCTION
% ============================================================

function r = rmsGlobal(x)

    x = double(x);

    r = ...
        sqrt(mean(x(:).^2));

end