clear;
close all;
clc;

%% ============================================================
% STEP 09B-5
% CORRECTED real forward pilot for expanded paired Monte Carlo.
%
% One full-physics k-Wave simulation:
%
%   fixed canonical three-line source
%   prescribed heterogeneous c(x,y), rho(x,y)
%   power-law attenuation
%   finite detector aperture
%   2 MHz / 80% detector response
%
% Then five paired AWGN measurements are generated from the
% SAME system RF and SAME normalized noise realization:
%
%   SNR = 5, 10, 15, 20, 30 dB
%
% IMPORTANT:
% Acoustic heterogeneity is injected using:
%
%   MediumModel   = 'mat'
%   MediumMapPath = MAT file containing:
%                   sound_speed
%                   density
%
% This is the interface already validated in the successful
% sequential D3/D4/D5 revision simulations.
% ============================================================

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

outDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step09_montecarlo');

if ~exist(outDir,'dir')
    mkdir(outDir);
end

mediumDir = fullfile( ...
    outDir, ...
    'medium_maps');

if ~exist(mediumDir,'dir')
    mkdir(mediumDir);
end

sourceFile = fullfile( ...
    outDir, ...
    'canonical_three_line_192x192.mat');

assert(isfile(sourceFile), ...
    'Frozen canonical three-line source not found.');

%% ============================================================
% FROZEN MONTE CARLO DESIGN
% ============================================================

baseSeed = 1;

snrLevels_dB = ...
    [5 10 15 20 30];

noiseSeed = ...
    baseSeed + 300000;

Nx = 192;
Ny = 192;

dx = 50e-6;
dy = 50e-6;

CFL = 0.20;

tEnd = ...
    16e-6;

fDesign = ...
    6e6;

%% ============================================================
% LOAD FROZEN SOURCE
% ============================================================

P = load( ...
    sourceFile, ...
    'p0', ...
    'meta');

p0Frozen = ...
    double(P.p0);

sourceMeta = ...
    P.meta;

assert( ...
    isequal(size(p0Frozen),[Nx Ny]), ...
    'Unexpected frozen-source dimensions.');

%% ============================================================
% GENERATE EXACT PUBLICATION MONTE CARLO MEDIUM
%
% This is the generator validated in STEP 09B-4.
% ============================================================

[mediumExpected,mediumMeta] = ...
    makePublicationMonteCarloMedium( ...
    Nx,Ny,dx,dy,baseSeed);

sound_speed = ...
    mediumExpected.sound_speed;

density = ...
    mediumExpected.density;

%% ============================================================
% PRE-SIMULATION MEDIUM AUDIT
% ============================================================

cExpected = ...
    double(sound_speed);

rhoExpected = ...
    double(density);

cExpectedMean = ...
    mean(cExpected(:));

cExpectedStd = ...
    std(cExpected(:));

cExpectedMin = ...
    min(cExpected(:));

cExpectedMax = ...
    max(cExpected(:));

rhoExpectedMean = ...
    mean(rhoExpected(:));

rhoExpectedStd = ...
    std(rhoExpected(:));

rhoExpectedMin = ...
    min(rhoExpected(:));

rhoExpectedMax = ...
    max(rhoExpected(:));

expectedCorr = ...
    corr( ...
    cExpected(:), ...
    rhoExpected(:));

expectedPPW = ...
    min( ...
    cExpectedMin/(dx*fDesign), ...
    cExpectedMin/(dy*fDesign));

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09B-5: CORRECTED REAL FORWARD PILOT -- SEED 1\n');
fprintf('============================================================\n');

fprintf('\n');
fprintf('EXPECTED MEDIUM BEFORE k-WAVE\n');
fprintf('------------------------------------------------------------\n');

fprintf('Base seed              = %d\n', ...
    baseSeed);

fprintf('Sound-speed seed       = %d\n', ...
    mediumMeta.sound_speed_seed);

fprintf('Density seed           = %d\n', ...
    mediumMeta.density_seed);

fprintf('\n');

fprintf('c mean/std/min/max     = %.9f / %.9f / %.9f / %.9f m/s\n', ...
    cExpectedMean, ...
    cExpectedStd, ...
    cExpectedMin, ...
    cExpectedMax);

fprintf('rho mean/std/min/max   = %.9f / %.9f / %.9f / %.9f kg/m^3\n', ...
    rhoExpectedMean, ...
    rhoExpectedStd, ...
    rhoExpectedMin, ...
    rhoExpectedMax);

fprintf('corr(c,rho)            = %.9f\n', ...
    expectedCorr);

fprintf('Expected PPW @ 6 MHz   = %.6f\n', ...
    expectedPPW);

assert(cExpectedStd > 15 && cExpectedStd < 25, ...
    'Expected sound-speed field is not heterogeneous.');

assert(rhoExpectedStd > 10 && rhoExpectedStd < 20, ...
    'Expected density field is not heterogeneous.');

assert(expectedPPW >= 4, ...
    'Expected heterogeneous medium fails PPW criterion.');

%% ============================================================
% WRITE PATBOX MEDIUM-MAP FILE
%
% PATBox MediumModel='mat' expects direct variables:
%
%       sound_speed
%       density
%
% Do not save only a nested "medium" structure.
% ============================================================

mediumMapFile = fullfile( ...
    mediumDir, ...
    sprintf( ...
    'montecarlo_medium_seed%03d.mat', ...
    baseSeed));

save( ...
    mediumMapFile, ...
    'sound_speed', ...
    'density', ...
    'mediumMeta', ...
    '-v7.3');

fprintf('\n');
fprintf('MEDIUM MAP FILE\n');
fprintf('------------------------------------------------------------\n');

fprintf('%s\n',mediumMapFile);

Mcheck = ...
    whos('-file',mediumMapFile);

savedNames = ...
    string({Mcheck.name});

assert(any(savedNames=="sound_speed"), ...
    'Medium MAT does not contain sound_speed.');

assert(any(savedNames=="density"), ...
    'Medium MAT does not contain density.');

%% ============================================================
% ONE REAL FULL-PHYSICS FORWARD SIMULATION
%
% Noise is deliberately disabled.
% ============================================================

fprintf('\n');
fprintf('Running one heterogeneous full-physics PATBox/k-Wave simulation...\n');

forwardTimer = tic;

simBase = patSimulate( ...
    sourceFile, ...
    ...
    'SourceModel','initial_pressure_mat', ...
    'InitialPressureVariable','p0', ...
    ...
    'GridSizeX',Nx, ...
    'GridSizeY',Ny, ...
    'Dx',dx, ...
    'Dy',dy, ...
    ...
    'CFL',CFL, ...
    'SimulationEndTime',tEnd, ...
    ...
    'PMLSize',20, ...
    'DataCast','single', ...
    'PlotSimulation',false, ...
    'SmoothInitialPressure',false, ...
    ...
    'MinFrequency',0, ...
    'MaxFrequency',fDesign, ...
    ...
    'MediumModel','mat', ...
    'MediumMapPath',mediumMapFile, ...
    ...
    'AlphaCoeff',0.75, ...
    'AlphaPower',1.5, ...
    'AlphaMode','full', ...
    ...
    'SensorType','circular', ...
    'SensorModel','kwave_array', ...
    'NumTransducers',128, ...
    'SensorRadius',4.20e-3, ...
    'ElementWidth',0.20e-3, ...
    'ElementIntegrationPoints',0, ...
    'SensorArcDeg',180, ...
    'SensorStartAngleDeg',-90, ...
    'SensorRotationDeg',0, ...
    ...
    'CenterFrequency',2.0e6, ...
    'FractionalBandwidthPercent',80, ...
    ...
    'NoiseModel','none', ...
    ...
    'RandomSeed',baseSeed);

forwardRuntime_s = ...
    toc(forwardTimer);

%% ============================================================
% BASIC RECORD AUDIT
% ============================================================

assert(isfield(simBase,'sensor_data_system'));
assert(isfield(simBase.sensor_data_system,'p'));

assert(isfield(simBase,'sensor_data_clean'));
assert(isfield(simBase.sensor_data_clean,'p'));

assert(isfield(simBase,'p0_reference'));

assert(isfield(simBase,'medium'));

assert(isfield(simBase.medium,'sound_speed'));

assert(isfield(simBase.medium,'density'));

assert(isfield(simBase,'kgrid'));

assert(isfield(simBase,'info'));

%% ============================================================
% SOURCE CONSISTENCY
% ============================================================

pReference = ...
    double(simBase.p0_reference);

assert( ...
    isequal(size(pReference),size(p0Frozen)));

sourceRelativeDifference = ...
    norm( ...
    pReference(:)-p0Frozen(:)) / ...
    (norm(p0Frozen(:))+eps);

fprintf('\n');
fprintf('SOURCE AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('Frozen/source relative difference = %.12e\n', ...
    sourceRelativeDifference);

assert(sourceRelativeDifference < 1e-7, ...
    'PATBox source differs from frozen canonical source.');

%% ============================================================
% CRITICAL MEDIUM-INJECTION AUDIT
%
% This is the audit that the previous pilot was missing.
% ============================================================

cActual = ...
    double(simBase.medium.sound_speed);

rhoActual = ...
    double(simBase.medium.density);

assert( ...
    isequal(size(cActual),size(cExpected)), ...
    'Forward sound-speed map has wrong size.');

assert( ...
    isequal(size(rhoActual),size(rhoExpected)), ...
    'Forward density map has wrong size.');

cMapRelativeDifference = ...
    norm( ...
    cActual(:)-cExpected(:)) / ...
    (norm(cExpected(:))+eps);

rhoMapRelativeDifference = ...
    norm( ...
    rhoActual(:)-rhoExpected(:)) / ...
    (norm(rhoExpected(:))+eps);

cMean = ...
    mean(cActual(:));

cStd = ...
    std(cActual(:));

cMin = ...
    min(cActual(:));

cMax = ...
    max(cActual(:));

rhoMean = ...
    mean(rhoActual(:));

rhoStd = ...
    std(rhoActual(:));

rhoMin = ...
    min(rhoActual(:));

rhoMax = ...
    max(rhoActual(:));

cRhoCorr = ...
    corr(cActual(:),rhoActual(:));

fprintf('\n');
fprintf('ACTUAL PATBOX MEDIUM AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('c mean          = %.9f m/s\n',cMean);
fprintf('c std           = %.9f m/s\n',cStd);
fprintf('c min           = %.9f m/s\n',cMin);
fprintf('c max           = %.9f m/s\n',cMax);

fprintf('\n');

fprintf('rho mean        = %.9f kg/m^3\n',rhoMean);
fprintf('rho std         = %.9f kg/m^3\n',rhoStd);
fprintf('rho min         = %.9f kg/m^3\n',rhoMin);
fprintf('rho max         = %.9f kg/m^3\n',rhoMax);

fprintf('\n');

fprintf('corr(c,rho)     = %.9f\n', ...
    cRhoCorr);

fprintf('\n');

fprintf('c map relative difference   = %.12e\n', ...
    cMapRelativeDifference);

fprintf('rho map relative difference = %.12e\n', ...
    rhoMapRelativeDifference);

%% ------------------------------------------------------------
% REAL heterogeneity requirements
% ------------------------------------------------------------

assert(cStd > 15 && cStd < 25, ...
    ['Heterogeneous sound-speed map was not actually ' ...
     'used by the forward solver.']);

assert(rhoStd > 10 && rhoStd < 20, ...
    ['Heterogeneous density map was not actually ' ...
     'used by the forward solver.']);

%% ------------------------------------------------------------
% Pixel-by-pixel injection consistency
% ------------------------------------------------------------

assert(cMapRelativeDifference < 1e-7, ...
    ['Forward sound-speed map differs from the ' ...
     'prespecified Monte Carlo medium.']);

assert(rhoMapRelativeDifference < 1e-7, ...
    ['Forward density map differs from the ' ...
     'prespecified Monte Carlo medium.']);

%% ============================================================
% PATBOX MEDIUM-METADATA AUDIT
% ============================================================

fprintf('\n');
fprintf('PATBOX MEDIUM METADATA\n');
fprintf('------------------------------------------------------------\n');

assert(isfield(simBase.info,'medium'), ...
    'sim.info.medium missing.');

disp(simBase.info.medium);

assert(isfield(simBase.info.medium,'model'));

assert(strcmpi( ...
    string(simBase.info.medium.model), ...
    "mat"), ...
    'PATBox did not record MediumModel=mat.');

if isfield(simBase.info,'config')

    assert(strcmpi( ...
        string(simBase.info.config.MediumModel), ...
        "mat"));

    recordedMediumPath = ...
        string(simBase.info.config.MediumMapPath);

    fprintf('Recorded MediumMapPath:\n%s\n', ...
        recordedMediumPath);
end

%% ============================================================
% ATTENUATION AUDIT
% ============================================================

fprintf('\n');
fprintf('ATTENUATION AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('alpha coeff      = %.6f\n', ...
    double(simBase.medium.alpha_coeff));

fprintf('alpha power      = %.6f\n', ...
    double(simBase.medium.alpha_power));

assert(abs( ...
    double(simBase.medium.alpha_coeff)-0.75) ...
    < 1e-12);

assert(abs( ...
    double(simBase.medium.alpha_power)-1.5) ...
    < 1e-12);

%% ============================================================
% GRID / TIME AUDIT
% ============================================================

dt = ...
    double(simBase.kgrid.dt);

Nt = ...
    simBase.kgrid.Nt;

tActual = ...
    double(simBase.kgrid.t_array(end));

dtCFLNominal = ...
    CFL * min(dx,dy) / cMax;

fprintf('\n');
fprintf('GRID / TIME AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('Grid              = %d x %d\n', ...
    simBase.kgrid.Nx, ...
    simBase.kgrid.Ny);

fprintf('dx / dy           = %.6f / %.6f um\n', ...
    double(simBase.kgrid.dx)*1e6, ...
    double(simBase.kgrid.dy)*1e6);

fprintf('Realized c_max    = %.9f m/s\n', ...
    cMax);

fprintf('Nominal CFL dt    = %.9f ns\n', ...
    dtCFLNominal*1e9);

fprintf('Actual dt         = %.9f ns\n', ...
    dt*1e9);

fprintf('Nt                = %d\n', ...
    Nt);

fprintf('t_end             = %.9f us\n', ...
    tActual*1e6);

assert(simBase.kgrid.Nx==Nx);
assert(simBase.kgrid.Ny==Ny);

assert(abs(double(simBase.kgrid.dx)-dx)<1e-12);
assert(abs(double(simBase.kgrid.dy)-dy)<1e-12);

assert(abs(tActual-tEnd) < 2*dt);

%% ------------------------------------------------------------
% Critical check:
% dt must no longer be the homogeneous 1500-m/s value.
% ------------------------------------------------------------

homogeneousDt = ...
    CFL * min(dx,dy) / 1500;

fprintf('Homogeneous-1500 dt = %.9f ns\n', ...
    homogeneousDt*1e9);

assert( ...
    abs(dt-homogeneousDt) > 1e-11, ...
    ['Time grid still appears to have been constructed ' ...
     'from the homogeneous 1500-m/s medium.']);

%% ============================================================
% PPW AUDIT
% ============================================================

ppwAchieved = ...
    min( ...
    cMin/(dx*fDesign), ...
    cMin/(dy*fDesign));

fprintf('\n');
fprintf('SPATIAL-SAMPLING AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('c_min             = %.9f m/s\n', ...
    cMin);

fprintf('PPW @ 6 MHz       = %.6f\n', ...
    ppwAchieved);

assert(ppwAchieved >= 4, ...
    'PPW acceptance criterion failed.');

%% ============================================================
% SENSOR AUDIT
% ============================================================

fprintf('\n');
fprintf('SENSOR AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('Sensor model      = %s\n', ...
    string(simBase.info.sensor_model));

fprintf('Receivers         = %d\n', ...
    simBase.info.num_sensors);

fprintf('Element width     = %.6f mm\n', ...
    double(simBase.info.element_width_m)*1e3);

fprintf('Center frequency  = %.6f MHz\n', ...
    double(simBase.info.center_frequency_hz)*1e-6);

fprintf('Fractional BW     = %.6f %%\n', ...
    double(simBase.info.fractional_bandwidth_percent));

fprintf('Recorded aperture = %.6f deg\n', ...
    double(simBase.info.aperture_deg));

assert(strcmpi( ...
    string(simBase.info.sensor_model), ...
    "kwave_array"));

assert(simBase.info.num_sensors==128);

assert(abs( ...
    double(simBase.info.element_width_m)-0.20e-3) ...
    < 1e-12);

assert(abs( ...
    double(simBase.info.center_frequency_hz)-2e6) ...
    < 1);

assert(abs( ...
    double(simBase.info.fractional_bandwidth_percent)-80) ...
    < 1e-9);

%% ============================================================
% RECEIVER-GEOMETRY AUDIT
%
% Do not rely only on SensorArcDeg parameter naming.
% Numerically inspect the actual receiver-center positions.
% ============================================================

assert(isfield(simBase,'sensor_geometry'));

assert(isfield(simBase.sensor_geometry,'positions'));

positions = ...
    double(simBase.sensor_geometry.positions);

if size(positions,1) ~= 2 && ...
        size(positions,2) == 2

    positions = ...
        positions.';
end

assert(size(positions,1)==2);

assert(size(positions,2)==128);

theta = ...
    mod( ...
    atan2( ...
    positions(2,:), ...
    positions(1,:)), ...
    2*pi);

theta = ...
    sort(theta);

angularGaps = ...
    diff( ...
    [theta theta(1)+2*pi]);

meanAngularGap_deg = ...
    mean(angularGaps)*180/pi;

maxAngularGap_deg = ...
    max(angularGaps)*180/pi;

minAngularGap_deg = ...
    min(angularGaps)*180/pi;

fprintf('\n');
fprintf('RECEIVER ANGULAR AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('Mean angular gap = %.9f deg\n', ...
    meanAngularGap_deg);

fprintf('Min angular gap  = %.9f deg\n', ...
    minAngularGap_deg);

fprintf('Max angular gap  = %.9f deg\n', ...
    maxAngularGap_deg);

fprintf('Ideal 128-ring gap = %.9f deg\n', ...
    360/128);

assert(abs( ...
    meanAngularGap_deg-360/128) < 1e-6, ...
    'Receiver ring is not full-view/equiangular as expected.');

%% ============================================================
% SYSTEM RF AUDIT
% ============================================================

pSystem = ...
    double(simBase.sensor_data_system.p);

pClean = ...
    double(simBase.sensor_data_clean.p);

assert(size(pSystem,1)==128);
assert(size(pSystem,2)==Nt);

assert(isequal( ...
    size(pSystem), ...
    size(pClean)));

assert(all(isfinite(pSystem(:))));
assert(all(isfinite(pClean(:))));

systemRMS = ...
    rmsGlobal(pSystem);

cleanRMS = ...
    rmsGlobal(pClean);

cleanSystemRelativeDifference = ...
    norm( ...
    pClean(:)-pSystem(:)) / ...
    (norm(pSystem(:))+eps);

fprintf('\n');
fprintf('SYSTEM RF AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('RF dimensions     = %d x %d\n', ...
    size(pSystem,1), ...
    size(pSystem,2));

fprintf('Clean RMS         = %.12e\n', ...
    cleanRMS);

fprintf('System RMS        = %.12e\n', ...
    systemRMS);

fprintf('Clean/system diff = %.12e\n', ...
    cleanSystemRelativeDifference);

assert(systemRMS > 0);

%% ============================================================
% ONE FROZEN NORMALIZED NOISE REALIZATION
% ============================================================

oldState = ...
    rng;

cleanupRng = ...
    onCleanup(@() rng(oldState));

rng(noiseSeed,'twister');

noiseUnit = ...
    randn(size(pSystem));

noiseUnit = ...
    noiseUnit / ...
    rmsGlobal(noiseUnit);

clear cleanupRng;

fprintf('\n');
fprintf('PAIRED-NOISE SOURCE\n');
fprintf('------------------------------------------------------------\n');

fprintf('Noise seed        = %d\n', ...
    noiseSeed);

fprintf('Noise unit RMS    = %.12f\n', ...
    rmsGlobal(noiseUnit));

assert(abs( ...
    rmsGlobal(noiseUnit)-1) ...
    < 1e-12);

%% ============================================================
% BUILD FIVE EXACTLY PAIRED MEASUREMENTS
% ============================================================

nSNR = ...
    numel(snrLevels_dB);

measuredRF = ...
    cell(nSNR,1);

normalizedNoise = ...
    cell(nSNR,1);

beta = ...
    nan(nSNR,1);

achievedSNR_dB = ...
    nan(nSNR,1);

for s = 1:nSNR

    targetSNR = ...
        snrLevels_dB(s);

    beta(s) = ...
        systemRMS / ...
        10^(targetSNR/20);

    addedNoise = ...
        beta(s) .* ...
        noiseUnit;

    measuredRF{s} = ...
        pSystem + ...
        addedNoise;

    noiseRMS = ...
        rmsGlobal(addedNoise);

    achievedSNR_dB(s) = ...
        20*log10( ...
        systemRMS/noiseRMS);

    normalizedNoise{s} = ...
        addedNoise / ...
        noiseRMS;
end

%% ============================================================
% FIVE-SNR AUDIT
% ============================================================

fprintf('\n');
fprintf('FIVE-SNR AUDIT\n');
fprintf('------------------------------------------------------------\n');

for s = 1:nSNR

    fprintf( ...
        ['Target %5.1f dB | beta %.12e | ' ...
         'achieved %.12f dB\n'], ...
        snrLevels_dB(s), ...
        beta(s), ...
        achievedSNR_dB(s));
end

snrError = ...
    achievedSNR_dB(:) - ...
    snrLevels_dB(:);

fprintf('\n');
fprintf('Maximum |SNR error| = %.12e dB\n', ...
    max(abs(snrError)));

assert(max(abs(snrError)) < 1e-10, ...
    'Five-SNR calibration failed.');

%% ============================================================
% FIVE-SNR EXACT PAIRING AUDIT
% ============================================================

maxPairDifference = ...
    0;

minPairCorrelation = ...
    1;

for i = 1:nSNR

    for j = i+1:nSNR

        ni = ...
            normalizedNoise{i};

        nj = ...
            normalizedNoise{j};

        relativeDifference = ...
            norm(ni(:)-nj(:)) / ...
            (norm(ni(:))+eps);

        pairCorrelation = ...
            corr(ni(:),nj(:));

        maxPairDifference = ...
            max( ...
            maxPairDifference, ...
            relativeDifference);

        minPairCorrelation = ...
            min( ...
            minPairCorrelation, ...
            pairCorrelation);
    end
end

fprintf('\n');
fprintf('FIVE-SNR PAIRING AUDIT\n');
fprintf('------------------------------------------------------------\n');

fprintf('Maximum normalized-noise difference = %.12e\n', ...
    maxPairDifference);

fprintf('Minimum noise correlation           = %.12f\n', ...
    minPairCorrelation);

assert(maxPairDifference < 1e-12);

assert(minPairCorrelation > 1-1e-12);

%% ============================================================
% SUMMARY TABLE
% ============================================================

pilotTable = table( ...
    repmat(baseSeed,nSNR,1), ...
    repmat(mediumMeta.sound_speed_seed,nSNR,1), ...
    repmat(mediumMeta.density_seed,nSNR,1), ...
    repmat(noiseSeed,nSNR,1), ...
    snrLevels_dB(:), ...
    beta, ...
    achievedSNR_dB, ...
    repmat(systemRMS,nSNR,1), ...
    'VariableNames',{ ...
    'BaseSeed', ...
    'SoundSpeedSeed', ...
    'DensitySeed', ...
    'NoiseSeed', ...
    'TargetSNR_dB', ...
    'NoiseScale', ...
    'AchievedSNR_dB', ...
    'SystemRMS'});

disp(pilotTable);

%% ============================================================
% SAVE CORRECTED PILOT
% ============================================================

pilotMeta = struct();

pilotMeta.schema_version = ...
    'revision_mc_forward_pilot_v2';

pilotMeta.base_seed = ...
    baseSeed;

pilotMeta.sound_speed_seed = ...
    mediumMeta.sound_speed_seed;

pilotMeta.density_seed = ...
    mediumMeta.density_seed;

pilotMeta.noise_seed = ...
    noiseSeed;

pilotMeta.source_file = ...
    sourceFile;

pilotMeta.medium_map_file = ...
    mediumMapFile;

pilotMeta.snr_levels_dB = ...
    snrLevels_dB;

pilotMeta.forward_runtime_s = ...
    forwardRuntime_s;

pilotMeta.ppw_achieved = ...
    ppwAchieved;

pilotMeta.medium_c_relative_difference = ...
    cMapRelativeDifference;

pilotMeta.medium_rho_relative_difference = ...
    rhoMapRelativeDifference;

pilotMeta.max_noise_pair_difference = ...
    maxPairDifference;

pilotMeta.min_noise_pair_correlation = ...
    minPairCorrelation;

pilotMeta.actual_medium = struct( ...
    'c_mean_mps',cMean, ...
    'c_std_mps',cStd, ...
    'c_min_mps',cMin, ...
    'c_max_mps',cMax, ...
    'rho_mean_kgm3',rhoMean, ...
    'rho_std_kgm3',rhoStd, ...
    'rho_min_kgm3',rhoMin, ...
    'rho_max_kgm3',rhoMax, ...
    'corr_c_rho',cRhoCorr);

pilotFile = fullfile( ...
    outDir, ...
    'montecarlo_forward_pilot_seed001_corrected.mat');

save( ...
    pilotFile, ...
    'simBase', ...
    'measuredRF', ...
    'noiseUnit', ...
    'beta', ...
    'achievedSNR_dB', ...
    'pilotTable', ...
    'pilotMeta', ...
    'mediumMeta', ...
    '-v7.3');

writetable( ...
    pilotTable, ...
    fullfile( ...
    outDir, ...
    'montecarlo_forward_pilot_seed001_corrected.csv'));

%% ============================================================
% FINAL
% ============================================================

fprintf('\n');
fprintf('Forward runtime = %.2f s\n', ...
    forwardRuntime_s);

fprintf('\n');
fprintf('Saved corrected pilot:\n%s\n', ...
    pilotFile);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09B-5 CORRECTED FORWARD PILOT: PASS\n');
fprintf('============================================================\n');

fprintf('Frozen source preserved          : PASS\n');
fprintf('MediumModel = MAT                : PASS\n');
fprintf('Exact c(x,y) map injected        : PASS\n');
fprintf('Exact rho(x,y) map injected      : PASS\n');
fprintf('Heterogeneous medium present     : PASS\n');
fprintf('Time grid uses heterogeneous c   : PASS\n');
fprintf('Power-law attenuation            : PASS\n');
fprintf('Finite receiver aperture         : PASS\n');
fprintf('2-MHz / 80%% detector response    : PASS\n');
fprintf('Full-view receiver ring          : PASS\n');
fprintf('PPW >= 4                         : PASS\n');
fprintf('Five target SNRs                 : PASS\n');
fprintf('Exact paired normalized noise    : PASS\n');

fprintf('\n');
fprintf('STEP 09B-5 COMPLETE\n');
fprintf('============================================================\n');


%% ============================================================
% LOCAL FUNCTION
% ============================================================

function r = rmsGlobal(x)

    x = double(x);

    r = ...
        sqrt(mean(x(:).^2));

end