function stages = revisionPhysicsStages(mediumFile)
%REVISIONPHYSICSSTAGES
% Controlled cumulative physical-degradation stages for manuscript revision.
%
% D0 Ideal
% D1 + detector bandwidth
% D2 + finite detector aperture
% D3 + acoustic heterogeneity
% D4 + power-law attenuation
% D5 + additive white Gaussian noise
%
% IMPORTANT:
% Limited angular view is NOT included here. It is studied separately.

    % ============================================================
    % Fixed publication parameters
    % ============================================================

    fc = 2e6;
    fbw = 80;

    elementWidth = 0.20e-3;

    alphaCoeff = 0.75;
    alphaPower = 1.5;

    targetSNR = 20;

    % ============================================================
    % D0: ideal point-receiver broadband acquisition
    % ============================================================

    stages(1) = makeStage( ...
        0, ...
        'D0_ideal', ...
        'Ideal broadband point receivers', ...
        { ...
        'SensorModel','cartesian_point', ...
        'ElementWidth',50e-6, ...
        'CenterFrequency',0, ...
        'FractionalBandwidthPercent',0, ...
        'MediumModel','homogeneous', ...
        'SoundSpeed',1500, ...
        'Density',1000, ...
        'AlphaCoeff',0, ...
        'NoiseModel','none' ...
        });

    % ============================================================
    % D1: bandwidth only
    % ============================================================

    stages(2) = makeStage( ...
        1, ...
        'D1_bandwidth', ...
        '+ detector bandwidth', ...
        { ...
        'SensorModel','cartesian_point', ...
        'ElementWidth',50e-6, ...
        'CenterFrequency',fc, ...
        'FractionalBandwidthPercent',fbw, ...
        'MediumModel','homogeneous', ...
        'SoundSpeed',1500, ...
        'Density',1000, ...
        'AlphaCoeff',0, ...
        'NoiseModel','none' ...
        });

    % ============================================================
    % D2: bandwidth + true finite detector aperture
    % ============================================================

    stages(3) = makeStage( ...
        2, ...
        'D2_finite_aperture', ...
        '+ finite detector aperture', ...
        { ...
        'SensorModel','kwave_array', ...
        'ElementWidth',elementWidth, ...
        'CenterFrequency',fc, ...
        'FractionalBandwidthPercent',fbw, ...
        'MediumModel','homogeneous', ...
        'SoundSpeed',1500, ...
        'Density',1000, ...
        'AlphaCoeff',0, ...
        'NoiseModel','none' ...
        });

    % ============================================================
    % D3: + acoustic heterogeneity
    % ============================================================

    stages(4) = makeStage( ...
        3, ...
        'D3_heterogeneity', ...
        '+ acoustic heterogeneity', ...
        { ...
        'SensorModel','kwave_array', ...
        'ElementWidth',elementWidth, ...
        'CenterFrequency',fc, ...
        'FractionalBandwidthPercent',fbw, ...
        'MediumModel','mat', ...
        'MediumMapPath',mediumFile, ...
        'AlphaCoeff',0, ...
        'NoiseModel','none' ...
        });

    % ============================================================
    % D4: + attenuation
    % ============================================================

    stages(5) = makeStage( ...
        4, ...
        'D4_attenuation', ...
        '+ power-law attenuation', ...
        { ...
        'SensorModel','kwave_array', ...
        'ElementWidth',elementWidth, ...
        'CenterFrequency',fc, ...
        'FractionalBandwidthPercent',fbw, ...
        'MediumModel','mat', ...
        'MediumMapPath',mediumFile, ...
        'AlphaCoeff',alphaCoeff, ...
        'AlphaPower',alphaPower, ...
        'AlphaMode','full', ...
        'NoiseModel','none' ...
        });

    % ============================================================
    % D5: + AWGN
    % ============================================================

    stages(6) = makeStage( ...
        5, ...
        'D5_noise', ...
        '+ additive noise', ...
        { ...
        'SensorModel','kwave_array', ...
        'ElementWidth',elementWidth, ...
        'CenterFrequency',fc, ...
        'FractionalBandwidthPercent',fbw, ...
        'MediumModel','mat', ...
        'MediumMapPath',mediumFile, ...
        'AlphaCoeff',alphaCoeff, ...
        'AlphaPower',alphaPower, ...
        'AlphaMode','full', ...
        'NoiseModel','awgn', ...
        'NoiseScaling','global', ...
        'NoiseCalibrationMode','target_snr', ...
        'TargetSNRdB',targetSNR ...
        });
end


function stage = makeStage(index,id,label,args)

    stage = struct();

    stage.Index = index;
    stage.Id = id;
    stage.Label = label;
    stage.SimArgs = args;
end