clear;
close all;
clc;

%% ============================================================
% STEP 08C-2
% Morphology/acquisition generalization reconstruction study
%
% 3 replicates
% x 4 morphology families
% x 3 acquisition configurations
% x 6 reconstruction methods
%
% = 216 reconstruction outcomes
% ============================================================

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

%% ------------------------------------------------------------
% Forward simulations
% ------------------------------------------------------------

simDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step08_generalization_forward', ...
    'simulations');

assert(isfolder(simDir), ...
    'Forward simulation directory not found.');

%% ------------------------------------------------------------
% Phantom definitions
% ------------------------------------------------------------

phantomDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step08_morphology_suite', ...
    'phantoms');

assert(isfolder(phantomDir), ...
    'Morphology phantom directory not found.');

%% ------------------------------------------------------------
% Output
% ------------------------------------------------------------

outputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step08_generalization_reconstruction');

conditionDir = fullfile( ...
    outputDir, ...
    'conditions');

if ~exist(conditionDir,'dir')
    mkdir(conditionDir);
end

%% ============================================================
% STUDY DEFINITIONS
% ============================================================

families = [ ...
    "sparse", ...
    "dense", ...
    "cluttered", ...
    "fluence"];

replicateSeeds = [ ...
    101, ...
    202, ...
    303];

configs = ...
    generalizationAcquisitionConfigs();

methodFields = { ...
    'DAS', ...
    'CFDAS', ...
    'SCFDAS', ...
    'DMAS', ...
    'DSDMAS', ...
    'TR'};

methodLabels = [ ...
    "DAS", ...
    "CF-DAS", ...
    "SCF-DAS", ...
    "DMAS", ...
    "DS-DMAS", ...
    "TR"];

nReplicates = ...
    numel(replicateSeeds);

nFamilies = ...
    numel(families);

nConfigs = ...
    numel(configs);

nMethods = ...
    numel(methodLabels);

nConditions = ...
    nReplicates * ...
    nFamilies * ...
    nConfigs;

nExpectedRows = ...
    nConditions * ...
    nMethods;

%% ============================================================
% EXECUTION POLICY
% ============================================================

% If false, completed condition files are reused.
forceRerun = false;

pipelineVersion = ...
    "generalization_revision_v1";

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 08C-2: GENERALIZATION RECONSTRUCTION STUDY\n');
fprintf('============================================================\n');

fprintf('Replicates          = %d\n',nReplicates);
fprintf('Morphologies        = %d\n',nFamilies);
fprintf('Acquisitions        = %d\n',nConfigs);
fprintf('Methods             = %d\n',nMethods);

fprintf('Conditions          = %d\n',nConditions);
fprintf('Expected outcomes   = %d\n',nExpectedRows);

fprintf('\nCheckpointing       = ON\n');
fprintf('Force rerun         = %d\n',forceRerun);

%% ============================================================
% LOOP
% ============================================================

conditionCounter = 0;
computedCounter = 0;
reusedCounter = 0;

studyTimer = tic;

for r = 1:nReplicates

    for a = 1:nConfigs

        acquisition = ...
            configs(a);

        for f = 1:nFamilies

            conditionCounter = ...
                conditionCounter + 1;

            family = ...
                families(f);

            %% =================================================
            % IDENTIFIERS
            % ==================================================

            conditionId = sprintf( ...
                'R%d_%s_%s', ...
                r, ...
                char(family), ...
                acquisition.Id);

            fprintf('\n\n');
            fprintf('############################################################\n');
            fprintf('CONDITION %d/%d\n', ...
                conditionCounter,nConditions);

            fprintf('%s\n',conditionId);
            fprintf('############################################################\n');

            %% =================================================
            % PATHS
            % ==================================================

            simFile = fullfile( ...
                simDir, ...
                [conditionId '.mat']);

            phantomFile = fullfile( ...
                phantomDir, ...
                sprintf( ...
                'R%d_%s_seed%d.mat', ...
                r, ...
                char(family), ...
                replicateSeeds(r)));

            resultFile = fullfile( ...
                conditionDir, ...
                [conditionId '_results.mat']);

            csvFile = fullfile( ...
                conditionDir, ...
                [conditionId '_metrics.csv']);

            assert(isfile(simFile), ...
                'Missing simulation: %s',simFile);

            assert(isfile(phantomFile), ...
                'Missing phantom: %s',phantomFile);

            %% =================================================
            % CHECKPOINT
            % ==================================================

            if ~forceRerun && ...
                    isfile(resultFile) && ...
                    isfile(csvFile)

                try

                    old = load( ...
                        resultFile, ...
                        'pipelineVersionSaved');

                    if isfield(old,'pipelineVersionSaved') && ...
                            string(old.pipelineVersionSaved) == ...
                            pipelineVersion

                        fprintf('Existing result reused.\n');

                        reusedCounter = ...
                            reusedCounter + 1;

                        continue;
                    end

                catch
                    % Invalid/incomplete checkpoint -> recompute.
                end
            end

            computedCounter = ...
                computedCounter + 1;

            %% =================================================
            % LOAD FORWARD SIMULATION
            % ==================================================

            A = load(simFile,'sim');

            sim = A.sim;

            %% =================================================
            % LOAD PHANTOM METADATA
            % ==================================================

            P = load( ...
                phantomFile, ...
                'p0', ...
                'components', ...
                'meta');

            pReference = ...
                double(P.p0);

            components = ...
                P.components;

            morphologyMeta = ...
                P.meta;

            %% =================================================
            % REFERENCE CONSISTENCY
            % ==================================================

            assert(isfield(sim,'p0_reference'), ...
                'sim.p0_reference missing.');

            simReference = ...
                double(sim.p0_reference);

            assert( ...
                isequal( ...
                size(simReference), ...
                size(pReference)), ...
                'Reference image dimensions differ.');

            relativeReferenceDifference = ...
                norm( ...
                simReference(:)- ...
                pReference(:)) / ...
                (norm(pReference(:))+eps);

            fprintf('\nInput audit\n');
            fprintf('------------------------------------------------------------\n');

            fprintf('Reference mismatch = %.6e\n', ...
                relativeReferenceDifference);

            assert( ...
                relativeReferenceDifference < 1e-7, ...
                'Forward and phantom references differ.');

            %% =================================================
            % ACQUISITION AUDIT
            % ==================================================

            rfMeasured = ...
                double(sim.sensor_data.p);

            nChannelsActual = ...
                size(rfMeasured,1);

            achievedSNR = ...
                sim.info.acquisition. ...
                achieved_additive_snr_db;

            fprintf('Channels           = %d\n', ...
                nChannelsActual);

            fprintf('dt                 = %.9f ns\n', ...
                double(sim.kgrid.dt)*1e9);

            fprintf('Nt                 = %d\n', ...
                sim.kgrid.Nt);

            fprintf('Achieved SNR       = %.6f dB\n', ...
                achievedSNR);

            assert( ...
                nChannelsActual == ...
                acquisition.NumTransducers);

            assert( ...
                abs(achievedSNR-20) < 0.05);

            %% =================================================
            % MEDIUM STATISTICS
            % ==================================================

            cMap = ...
                double(sim.medium.sound_speed);

            rhoMap = ...
                double(sim.medium.density);

            cMean = ...
                mean(cMap(:));

            cStd = ...
                std(cMap(:));

            rhoMean = ...
                mean(rhoMap(:));

            rhoStd = ...
                std(rhoMap(:));

            cRhoCorrelation = ...
                corr(cMap(:),rhoMap(:));

            fprintf('c mean/std         = %.3f / %.3f m/s\n', ...
                cMean,cStd);

            fprintf('rho mean/std       = %.3f / %.3f kg/m^3\n', ...
                rhoMean,rhoStd);

            %% =================================================
            % 1. FIVE BEAMFORMERS
            % ==================================================

            [bf,bfInfo] = ...
                publicationBeamformers( ...
                sim, ...
                'SoundSpeed',1500, ...
                'Interpolation','linear', ...
                'CFPower',1.0, ...
                'SCFPower',1.5);

            %% =================================================
            % 2. TIME REVERSAL
            % ==================================================

            [pTR,trInfo] = ...
                publicationTimeReversal( ...
                sim, ...
                'DataCast','single', ...
                'PMLSize',20, ...
                'PlotSimulation',false);

            %% =================================================
            % COMBINE
            % ==================================================

            reconstructions = bf;

            reconstructions.TR = ...
                pTR;

            %% =================================================
            % RUNTIME MAP
            % ==================================================

            runtimeMap = struct();

            runtimeMap.DAS = ...
                bfInfo.total_runtime_DAS_s;

            runtimeMap.CFDAS = ...
                bfInfo.total_runtime_CFDAS_s;

            runtimeMap.SCFDAS = ...
                bfInfo.total_runtime_SCFDAS_s;

            runtimeMap.DMAS = ...
                bfInfo.total_runtime_DMAS_s;

            runtimeMap.DSDMAS = ...
                bfInfo.total_runtime_DSDMAS_s;

            runtimeMap.TR = ...
                trInfo.elapsed_seconds;

            %% =================================================
            % EVALUATION STORAGE
            % ==================================================

            genericMetrics = struct();
            taskMetrics = struct();

            conditionRows = [];

            %% =================================================
            % SIX METHODS
            % ==================================================

            for m = 1:nMethods

                fieldName = ...
                    methodFields{m};

                methodLabel = ...
                    methodLabels(m);

                fprintf('\nEvaluating %-8s ...\n', ...
                    methodLabel);

                reconstruction = ...
                    double( ...
                    reconstructions.(fieldName));

                assert(all(isfinite(reconstruction(:))), ...
                    '%s contains non-finite values.', ...
                    methodLabel);

                %% ---------------------------------------------
                % Generic image-quality metrics
                % ----------------------------------------------

                G = ...
                    publicationEvaluate( ...
                    reconstruction, ...
                    pReference);

                genericMetrics.(fieldName) = ...
                    G;

                %% ---------------------------------------------
                % Vascular task metrics
                % ----------------------------------------------

                V = ...
                    publicationVascularTaskMetrics( ...
                    reconstruction, ...
                    pReference, ...
                    sim.kgrid, ...
                    components, ...
                    morphologyMeta, ...
                    ...
                    'ThresholdFraction',0.10, ...
                    'Tolerance_m',0.10e-3, ...
                    'SegmentRecoveredFraction',0.60, ...
                    'SamplesPerSegment',15);

                %% ---------------------------------------------
                % Low/high fluence recovery should only be
                % interpreted for the fluence family.
                % ----------------------------------------------

                if family ~= "fluence"

                    V.low_fluence_terminal_recovery = NaN;

                    V.high_fluence_terminal_recovery = NaN;
                end

                %% ---------------------------------------------
                % Vessel-to-clutter ratio should only be
                % interpreted for the clutter family.
                % ----------------------------------------------

                if family ~= "cluttered"

                    V.vessel_to_clutter_ratio_db = NaN;
                end

                taskMetrics.(fieldName) = ...
                    V;

                %% ---------------------------------------------
                % Reconstruction-model metadata
                % ----------------------------------------------

                if fieldName == "TR"

                    reconPhysicsModel = ...
                        "heterogeneous_recorded_c_rho";

                    if trInfo.equivalent_center_approximation

                        finiteApertureTreatment = ...
                            "equivalent_element_centres";

                    else

                        finiteApertureTreatment = ...
                            "point_receiver_coordinates";
                    end

                    runtimeDefinition = ...
                        "actual_TR_wall_time";

                else

                    reconPhysicsModel = ...
                        "scalar_c_1500";

                    finiteApertureTreatment = ...
                        "physical_element_centres";

                    runtimeDefinition = ...
                        "shared_delay_plus_weighting";
                end

                %% ---------------------------------------------
                % One result row
                % ----------------------------------------------

                newRow = table( ...
                    ...
                    r, ...
                    replicateSeeds(r), ...
                    family, ...
                    string(acquisition.Id), ...
                    string(acquisition.Label), ...
                    acquisition.NumTransducers, ...
                    acquisition.CenterFrequency/1e6, ...
                    acquisition.FractionalBandwidthPercent, ...
                    methodLabel, ...
                    ...
                    morphologyMeta.segmentCount, ...
                    morphologyMeta.branchPointCount, ...
                    morphologyMeta.terminalPointCount, ...
                    ...
                    cMean, ...
                    cStd, ...
                    rhoMean, ...
                    rhoStd, ...
                    cRhoCorrelation, ...
                    achievedSNR, ...
                    ...
                    G.raw_nrmse, ...
                    G.si_nrmse, ...
                    G.correlation, ...
                    G.ssim, ...
                    G.cnr, ...
                    G.sbr_db, ...
                    G.scale_factor, ...
                    G.signal_rms, ...
                    G.background_rms, ...
                    ...
                    V.centerline_recall, ...
                    V.mean_segment_continuity, ...
                    V.median_segment_continuity, ...
                    V.branch_point_recovery, ...
                    V.terminal_branch_recovery, ...
                    V.low_fluence_terminal_recovery, ...
                    V.high_fluence_terminal_recovery, ...
                    V.vessel_to_clutter_ratio_db, ...
                    ...
                    runtimeMap.(fieldName), ...
                    string(runtimeDefinition), ...
                    string(reconPhysicsModel), ...
                    string(finiteApertureTreatment), ...
                    ...
                    'VariableNames',{ ...
                    ...
                    'Replicate', ...
                    'MorphologySeed', ...
                    'Family', ...
                    'Acquisition', ...
                    'AcquisitionLabel', ...
                    'Channels', ...
                    'CenterFrequency_MHz', ...
                    'FractionalBandwidth_percent', ...
                    'Method', ...
                    ...
                    'Segments', ...
                    'BranchPoints', ...
                    'TerminalPoints', ...
                    ...
                    'CMean_mps', ...
                    'CStd_mps', ...
                    'RhoMean_kgm3', ...
                    'RhoStd_kgm3', ...
                    'Corr_C_Rho', ...
                    'AchievedSNR_dB', ...
                    ...
                    'Raw_NRMSE', ...
                    'SI_NRMSE', ...
                    'Correlation', ...
                    'SSIM', ...
                    'CNR', ...
                    'SBR_dB', ...
                    'ScaleFactor', ...
                    'Signal_RMS', ...
                    'Background_RMS', ...
                    ...
                    'CenterlineRecall', ...
                    'MeanSegmentContinuity', ...
                    'MedianSegmentContinuity', ...
                    'BranchPointRecovery', ...
                    'TerminalBranchRecovery', ...
                    'LowFluenceTerminalRecovery', ...
                    'HighFluenceTerminalRecovery', ...
                    'VesselToClutterRatio_dB', ...
                    ...
                    'Runtime_s', ...
                    'RuntimeDefinition', ...
                    'ReconstructionPhysicsModel', ...
                    'FiniteApertureTreatment'});

                conditionRows = ...
                    [conditionRows;newRow]; %#ok<AGROW>

                %% ---------------------------------------------
                % Console
                % ----------------------------------------------

                fprintf( ...
                    ['SI %.4f | SSIM %.4f | Corr %.4f | ' ...
                     'Centerline %.3f | Branch %.3f | Terminal %.3f\n'], ...
                    G.si_nrmse, ...
                    G.ssim, ...
                    G.correlation, ...
                    V.centerline_recall, ...
                    V.branch_point_recovery, ...
                    V.terminal_branch_recovery);
            end

            %% =================================================
            % CONDITION AUDIT
            % ==================================================

            assert(height(conditionRows)==6);

            assert( ...
                all(isfinite(conditionRows.SI_NRMSE)));

            assert( ...
                all(isfinite(conditionRows.Correlation)));

            assert( ...
                all(isfinite(conditionRows.SSIM)));

            assert( ...
                all( ...
                conditionRows.CenterlineRecall >= 0 & ...
                conditionRows.CenterlineRecall <= 1));

            assert( ...
                all( ...
                conditionRows.MeanSegmentContinuity >= 0 & ...
                conditionRows.MeanSegmentContinuity <= 1));

            assert( ...
                all( ...
                conditionRows.BranchPointRecovery >= 0 & ...
                conditionRows.BranchPointRecovery <= 1));

            assert( ...
                all( ...
                conditionRows.TerminalBranchRecovery >= 0 & ...
                conditionRows.TerminalBranchRecovery <= 1));

            %% =================================================
            % SAVE CONDITION CHECKPOINT
            % ==================================================

            pipelineVersionSaved = ...
                pipelineVersion;

            save( ...
                resultFile, ...
                ...
                'pipelineVersionSaved', ...
                'conditionId', ...
                'pReference', ...
                'reconstructions', ...
                'genericMetrics', ...
                'taskMetrics', ...
                'bfInfo', ...
                'trInfo', ...
                'conditionRows', ...
                '-v7.3');

            writetable( ...
                conditionRows, ...
                csvFile);

            fprintf('\nCondition checkpoint saved.\n');

            %% =================================================
            % PROGRESS
            % ==================================================

            elapsedStudy = ...
                toc(studyTimer);

            meanConditionTime = ...
                elapsedStudy / ...
                max(computedCounter,1);

            remainingCompute = ...
                nConditions - ...
                computedCounter - ...
                reusedCounter;

            approximateRemainingMinutes = ...
                max(0,remainingCompute) * ...
                meanConditionTime / 60;

            fprintf( ...
                'Approximate remaining compute time: %.1f min\n', ...
                approximateRemainingMinutes);
        end
    end
end

%% ============================================================
% GATHER ALL CONDITION CSV FILES
% ============================================================

fprintf('\n\n');
fprintf('============================================================\n');
fprintf('GATHERING MASTER RESULT TABLE\n');
fprintf('============================================================\n');

csvFiles = dir( ...
    fullfile( ...
    conditionDir, ...
    '*_metrics.csv'));

assert(numel(csvFiles)==nConditions, ...
    ['Expected %d completed condition CSV files, ' ...
     'but found %d.'], ...
    nConditions,numel(csvFiles));

masterTable = [];

for k = 1:numel(csvFiles)

    filePath = fullfile( ...
        csvFiles(k).folder, ...
        csvFiles(k).name);

    Tk = readtable( ...
        filePath, ...
        'TextType','string');

    assert(height(Tk)==nMethods, ...
        'Condition CSV does not contain six methods.');

    masterTable = ...
        [masterTable;Tk]; %#ok<AGROW>
end

%% ============================================================
% MASTER AUDIT
% ============================================================

assert(height(masterTable)==nExpectedRows, ...
    'Expected 216 result rows.');

fprintf('\nRows                  = %d\n', ...
    height(masterTable));

fprintf('Unique replicates     = %d\n', ...
    numel(unique(masterTable.Replicate)));

fprintf('Unique families       = %d\n', ...
    numel(unique(masterTable.Family)));

fprintf('Unique acquisitions   = %d\n', ...
    numel(unique(masterTable.Acquisition)));

fprintf('Unique methods        = %d\n', ...
    numel(unique(masterTable.Method)));

%% ------------------------------------------------------------
% Expected dimensions
% ------------------------------------------------------------

assert(numel(unique(masterTable.Replicate))==3);
assert(numel(unique(masterTable.Family))==4);
assert(numel(unique(masterTable.Acquisition))==3);
assert(numel(unique(masterTable.Method))==6);

%% ------------------------------------------------------------
% Generic metric audit
% ------------------------------------------------------------

assert(all(isfinite(masterTable.SI_NRMSE)));
assert(all(isfinite(masterTable.Correlation)));
assert(all(isfinite(masterTable.SSIM)));
assert(all(isfinite(masterTable.CNR)));
assert(all(isfinite(masterTable.SBR_dB)));

%% ------------------------------------------------------------
% Core vascular task metrics
% ------------------------------------------------------------

coreTaskColumns = { ...
    'CenterlineRecall', ...
    'MeanSegmentContinuity', ...
    'BranchPointRecovery', ...
    'TerminalBranchRecovery'};

for k = 1:numel(coreTaskColumns)

    values = ...
        masterTable.(coreTaskColumns{k});

    assert(all(isfinite(values)));

    assert(all(values >= 0 & values <= 1));
end

%% ============================================================
% SPECIAL-TASK AVAILABILITY
% ============================================================

isFluence = ...
    masterTable.Family == "fluence";

isClutter = ...
    masterTable.Family == "cluttered";

fprintf('\nSpecial task metric availability\n');
fprintf('------------------------------------------------------------\n');

fprintf('Fluence rows          = %d\n', ...
    nnz(isFluence));

fprintf('Clutter rows          = %d\n', ...
    nnz(isClutter));

fprintf('Finite low-fluence    = %d\n', ...
    nnz( ...
    isFluence & ...
    isfinite( ...
    masterTable.LowFluenceTerminalRecovery)));

fprintf('Finite high-fluence   = %d\n', ...
    nnz( ...
    isFluence & ...
    isfinite( ...
    masterTable.HighFluenceTerminalRecovery)));

fprintf('Finite vessel/clutter = %d\n', ...
    nnz( ...
    isClutter & ...
    isfinite( ...
    masterTable.VesselToClutterRatio_dB)));

%% ============================================================
% SAVE MASTER RESULTS
% ============================================================

masterCsv = fullfile( ...
    outputDir, ...
    'generalization_reconstruction_metrics_216.csv');

writetable( ...
    masterTable, ...
    masterCsv);

save( ...
    fullfile( ...
        outputDir, ...
        'generalization_reconstruction_metrics_216.mat'), ...
    'masterTable', ...
    'pipelineVersion', ...
    '-v7.3');

%% ============================================================
% SIMPLE RANGE SUMMARY
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('GENERALIZATION RECONSTRUCTION AUDIT\n');
fprintf('============================================================\n');

fprintf('Completed conditions = %d / %d\n', ...
    nConditions,nConditions);

fprintf('Completed outcomes   = %d / %d\n', ...
    height(masterTable),nExpectedRows);

fprintf('\nGeneric metric ranges:\n');

fprintf('SI-NRMSE    %.4f -- %.4f\n', ...
    min(masterTable.SI_NRMSE), ...
    max(masterTable.SI_NRMSE));

fprintf('Correlation %.4f -- %.4f\n', ...
    min(masterTable.Correlation), ...
    max(masterTable.Correlation));

fprintf('SSIM        %.4f -- %.4f\n', ...
    min(masterTable.SSIM), ...
    max(masterTable.SSIM));

fprintf('\nTask metric ranges:\n');

fprintf('Centerline  %.4f -- %.4f\n', ...
    min(masterTable.CenterlineRecall), ...
    max(masterTable.CenterlineRecall));

fprintf('Continuity  %.4f -- %.4f\n', ...
    min(masterTable.MeanSegmentContinuity), ...
    max(masterTable.MeanSegmentContinuity));

fprintf('Branch      %.4f -- %.4f\n', ...
    min(masterTable.BranchPointRecovery), ...
    max(masterTable.BranchPointRecovery));

fprintf('Terminal    %.4f -- %.4f\n', ...
    min(masterTable.TerminalBranchRecovery), ...
    max(masterTable.TerminalBranchRecovery));

fprintf('\nCheckpoint reuse:\n');

fprintf('Computed this run = %d\n', ...
    computedCounter);

fprintf('Reused            = %d\n', ...
    reusedCounter);

fprintf('\nTotal wall time = %.2f min\n', ...
    toc(studyTimer)/60);

fprintf('\n============================================================\n');
fprintf('STEP 08C-2 COMPLETE\n');
fprintf('============================================================\n');

fprintf('\nMaster table:\n%s\n',masterCsv);