clear;
close all;
clc;

%% ============================================================
% STEP 09C
% FINAL EXPANDED MONTE CARLO RECONSTRUCTION STUDY
%
% 50 paired realizations
% x 5 SNR levels
% x 6 reconstruction methods
%
% = 1500 reconstruction outcomes
%
% Metrics:
%   SI-NRMSE
%   Correlation
%   SSIM
%   CNR
%   SBR
%
% CHECKPOINT / RESUME SAFE.
% ============================================================

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

mcRoot = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step09_montecarlo');

forwardDir = fullfile( ...
    mcRoot, ...
    'forward_seeds');

conditionDir = fullfile( ...
    mcRoot, ...
    'reconstruction_conditions');

if ~exist(conditionDir,'dir')
    mkdir(conditionDir);
end

assert(isfolder(forwardDir), ...
    'Monte Carlo forward directory not found.');

%% ============================================================
% FROZEN DESIGN
% ============================================================

baseSeeds = ...
    (1:50).';

snrLevels_dB = ...
    [5 10 15 20 30];

methods = [ ...
    "DAS", ...
    "CF-DAS", ...
    "SCF-DAS", ...
    "DMAS", ...
    "DS-DMAS", ...
    "TR"];

methodFields = { ...
    'DAS', ...
    'CFDAS', ...
    'SCFDAS', ...
    'DMAS', ...
    'DSDMAS', ...
    'TR'};

nSeeds = ...
    numel(baseSeeds);

nSNR = ...
    numel(snrLevels_dB);

nMethods = ...
    numel(methods);

nConditions = ...
    nSeeds*nSNR;

nExpectedRows = ...
    nConditions*nMethods;

%% ============================================================
% FROZEN RECONSTRUCTION SETTINGS
% ============================================================

beamformerSoundSpeed = ...
    1500;

beamformerInterpolation = ...
    'linear';

cfPower = ...
    1.0;

scfPower = ...
    1.5;

%% ============================================================
% EXECUTION POLICY
% ============================================================

forceRerun = ...
    false;

schemaVersion = ...
    "revision_mc_reconstruction_v1";

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09C: EXPANDED MONTE CARLO RECONSTRUCTION\n');
fprintf('============================================================\n');

fprintf('Base seeds              = %d\n',nSeeds);
fprintf('SNR levels              = %d\n',nSNR);
fprintf('RF conditions           = %d\n',nConditions);
fprintf('Methods                 = %d\n',nMethods);
fprintf('Expected outcomes       = %d\n',nExpectedRows);

fprintf('\nSNR levels [dB]         = ');
fprintf('%g ',snrLevels_dB);
fprintf('\n');

fprintf('Checkpointing           = ON\n');
fprintf('Force rerun             = %d\n',forceRerun);

%% ============================================================
% COUNTERS
% ============================================================

conditionCounter = ...
    0;

computedConditions = ...
    0;

reusedConditions = ...
    0;

studyTimer = ...
    tic;

%% ============================================================
% SEED LOOP
% ============================================================

for q = 1:nSeeds

    baseSeed = ...
        baseSeeds(q);

    forwardFile = fullfile( ...
        forwardDir, ...
        sprintf( ...
        'mc_forward_seed%03d.mat', ...
        baseSeed));

    assert(isfile(forwardFile), ...
        'Missing forward checkpoint for seed %d.', ...
        baseSeed);

    %% --------------------------------------------------------
    % Load one physical forward simulation for this seed.
    % ---------------------------------------------------------

    F = load( ...
        forwardFile, ...
        'simBase', ...
        'beta', ...
        'achievedSNR_dB', ...
        'seedTable', ...
        'mediumMeta', ...
        'rfSpecification');

    simBase = ...
        F.simBase;

    assert(isfield(simBase,'sensor_data_system'));
    assert(isfield(simBase.sensor_data_system,'p'));

    pSystem = ...
        double(simBase.sensor_data_system.p);

    pReference = ...
        double(simBase.p0_reference);

    assert(all(isfinite(pSystem(:))));
    assert(all(isfinite(pReference(:))));

    %% ========================================================
    % REGENERATE THE EXACT NORMALIZED NOISE REALIZATION
    % =========================================================

    noiseSeed = ...
        baseSeed + 300000;

    oldRng = ...
        rng;

    cleanupRng = ...
        onCleanup(@() rng(oldRng));

    rng(noiseSeed,'twister');

    noiseUnit = ...
        randn(size(pSystem));

    noiseUnit = ...
        noiseUnit / ...
        rmsGlobal(noiseUnit);

    clear cleanupRng;

    assert(abs(rmsGlobal(noiseUnit)-1)<1e-12);

    %% ========================================================
    % MEDIUM STATISTICS
    % =========================================================

    cMap = ...
        double(simBase.medium.sound_speed);

    rhoMap = ...
        double(simBase.medium.density);

    cMean = ...
        mean(cMap(:));

    cStd = ...
        std(cMap(:));

    cMin = ...
        min(cMap(:));

    cMax = ...
        max(cMap(:));

    rhoMean = ...
        mean(rhoMap(:));

    rhoStd = ...
        std(rhoMap(:));

    cRhoCorr = ...
        corr(cMap(:),rhoMap(:));

    %% ========================================================
    % SNR LOOP
    % =========================================================

    for s = 1:nSNR

        conditionCounter = ...
            conditionCounter + 1;

        targetSNR = ...
            snrLevels_dB(s);

        conditionId = ...
            sprintf( ...
            'seed%03d_snr%02d', ...
            baseSeed, ...
            targetSNR);

        resultFile = fullfile( ...
            conditionDir, ...
            [conditionId '_metrics.mat']);

        csvFile = fullfile( ...
            conditionDir, ...
            [conditionId '_metrics.csv']);

        fprintf('\n');
        fprintf('############################################################\n');
        fprintf('CONDITION %d / %d\n', ...
            conditionCounter,nConditions);

        fprintf('Seed %d | SNR %.1f dB\n', ...
            baseSeed,targetSNR);

        fprintf('############################################################\n');

        %% ====================================================
        % CHECKPOINT
        % =====================================================

        if ~forceRerun && ...
                isfile(resultFile) && ...
                isfile(csvFile)

            try

                C = load( ...
                    resultFile, ...
                    'schemaVersionSaved', ...
                    'conditionTable');

                if isfield(C,'schemaVersionSaved') && ...
                        string(C.schemaVersionSaved)== ...
                        schemaVersion && ...
                        isfield(C,'conditionTable') && ...
                        height(C.conditionTable)==nMethods

                    fprintf('Checkpoint valid -> REUSED.\n');

                    reusedConditions = ...
                        reusedConditions + 1;

                    continue;
                end

            catch ME

                fprintf( ...
                    'Checkpoint invalid (%s); recomputing.\n', ...
                    ME.message);
            end
        end

        computedConditions = ...
            computedConditions + 1;

        %% ====================================================
        % RECONSTRUCT EXACT MEASURED RF
        % =====================================================

        betaCurrent = ...
            F.beta(s);

        addedNoise = ...
            betaCurrent .* ...
            noiseUnit;

        measuredRF = ...
            pSystem + ...
            addedNoise;

        measuredNoiseRMS = ...
            rmsGlobal(addedNoise);

        systemRMS = ...
            rmsGlobal(pSystem);

        achievedSNR = ...
            20*log10( ...
            systemRMS / ...
            measuredNoiseRMS);

        snrError = ...
            achievedSNR-targetSNR;

        fprintf('\nRF audit\n');
        fprintf('------------------------------------------------------------\n');

        fprintf('System RMS       = %.12e\n', ...
            systemRMS);

        fprintf('Noise RMS        = %.12e\n', ...
            measuredNoiseRMS);

        fprintf('Target SNR       = %.9f dB\n', ...
            targetSNR);

        fprintf('Achieved SNR     = %.12f dB\n', ...
            achievedSNR);

        fprintf('SNR error        = %.3e dB\n', ...
            snrError);

        assert(abs(snrError)<1e-10, ...
            'Reconstructed RF has incorrect SNR.');

        %% ====================================================
        % BUILD CONDITION-SPECIFIC SIM STRUCT
        %
        % All methods receive EXACTLY the same measured RF.
        % =====================================================

        simCase = ...
            simBase;

        simCase.sensor_data.p = ...
            measuredRF;

        %% ----------------------------------------------------
        % Update acquisition metadata for traceability.
        % -----------------------------------------------------

        if ~isfield(simCase.info,'acquisition')
            simCase.info.acquisition = struct();
        end

        simCase.info.acquisition.base_random_seed = ...
            baseSeed;

        simCase.info.acquisition.noise_model = ...
            'awgn';

        simCase.info.acquisition.noise_scaling = ...
            'global';

        simCase.info.acquisition.noise_calibration_mode = ...
            'target_snr';

        simCase.info.acquisition.target_snr_db = ...
            targetSNR;

        simCase.info.acquisition.achieved_additive_snr_db = ...
            achievedSNR;

        simCase.info.acquisition.achieved_snr_db = ...
            achievedSNR;

        %% ====================================================
        % FIVE BEAMFORMERS
        % =====================================================

        fprintf('\nRunning five beamformers...\n');

        [bf,bfInfo] = ...
            publicationBeamformers( ...
            simCase, ...
            'SoundSpeed', ...
                beamformerSoundSpeed, ...
            'Interpolation', ...
                beamformerInterpolation, ...
            'CFPower', ...
                cfPower, ...
            'SCFPower', ...
                scfPower);

        %% ====================================================
        % TIME REVERSAL
        %
        % IMPORTANT:
        % publicationTimeReversal uses the recorded heterogeneous
        % c(x,y), rho(x,y), while intentionally performing no
        % attenuation compensation and no detector deconvolution.
        % =====================================================

        fprintf('\nRunning time reversal...\n');

        [pTR,trInfo] = ...
            publicationTimeReversal( ...
            simCase, ...
            'DataCast','single', ...
            'PMLSize',20, ...
            'PlotSimulation',false);

        %% ====================================================
        % COLLECT RECONSTRUCTIONS
        % =====================================================

        recon = ...
            bf;

        recon.TR = ...
            pTR;

        %% ====================================================
        % RUNTIME DEFINITIONS
        % =====================================================

        runtimeMap = struct();

        runtimeMap.DAS = ...
            bfInfo.total_runtime_DAS_s;

        runtimeMap.CFDAS = ...
            bfInfo.total_runtime_CFDAS_s;

        runtimeMap.SCFDAS = ...
            bfInfo.total_runtime_SCFDAS_s;

        runtimeMap.DMAS = ...
            bfInfo.total_runtime_DMAS_s;

        runtimeMap.DSDMAS = ...
            bfInfo.total_runtime_DSDMAS_s;

        runtimeMap.TR = ...
            trInfo.elapsed_seconds;

        %% ====================================================
        % METRICS
        % =====================================================

        conditionTable = [];

        metricStruct = struct();

        for m = 1:nMethods

            method = ...
                methods(m);

            fieldName = ...
                methodFields{m};

            reconstruction = ...
                double(recon.(fieldName));

            assert( ...
                isequal( ...
                size(reconstruction), ...
                size(pReference)), ...
                '%s reconstruction has wrong dimensions.', ...
                method);

            assert( ...
                all(isfinite(reconstruction(:))), ...
                '%s reconstruction contains non-finite values.', ...
                method);

            M = ...
                publicationEvaluate( ...
                reconstruction, ...
                pReference);

            metricStruct.(fieldName) = ...
                M;

            %% -----------------------------------------------
            % Reconstruction-model metadata
            % -----------------------------------------------

            if method == "TR"

                reconstructionPhysics = ...
                    "heterogeneous_recorded_c_rho";

                runtimeDefinition = ...
                    "direct_TR_wall_time";

                finiteApertureTreatment = ...
                    "equivalent_element_centres";

            else

                reconstructionPhysics = ...
                    "scalar_straight_ray_c1500";

                runtimeDefinition = ...
                    "shared_delay_plus_weighting";

                finiteApertureTreatment = ...
                    "physical_element_centres";
            end

            %% -----------------------------------------------
            % ONE RESULT ROW
            % -----------------------------------------------

            newRow = table( ...
                ...
                baseSeed, ...
                baseSeed<=10, ...
                noiseSeed, ...
                targetSNR, ...
                achievedSNR, ...
                method, ...
                ...
                cMean, ...
                cStd, ...
                cMin, ...
                cMax, ...
                rhoMean, ...
                rhoStd, ...
                cRhoCorr, ...
                ...
                M.raw_nrmse, ...
                M.si_nrmse, ...
                M.correlation, ...
                M.ssim, ...
                M.cnr, ...
                M.sbr_db, ...
                M.scale_factor, ...
                M.signal_rms, ...
                M.background_rms, ...
                ...
                runtimeMap.(fieldName), ...
                string(runtimeDefinition), ...
                string(reconstructionPhysics), ...
                string(finiteApertureTreatment), ...
                ...
                'VariableNames',{ ...
                ...
                'BaseSeed', ...
                'OriginalSeedSubset', ...
                'NoiseSeed', ...
                'TargetSNR_dB', ...
                'AchievedSNR_dB', ...
                'Method', ...
                ...
                'CMean_mps', ...
                'CStd_mps', ...
                'CMin_mps', ...
                'CMax_mps', ...
                'RhoMean_kgm3', ...
                'RhoStd_kgm3', ...
                'Corr_C_Rho', ...
                ...
                'Raw_NRMSE', ...
                'SI_NRMSE', ...
                'Correlation', ...
                'SSIM', ...
                'CNR', ...
                'SBR_dB', ...
                'ScaleFactor', ...
                'Signal_RMS', ...
                'Background_RMS', ...
                ...
                'Runtime_s', ...
                'RuntimeDefinition', ...
                'ReconstructionPhysicsModel', ...
                'FiniteApertureTreatment'});

            conditionTable = ...
                [conditionTable;newRow]; %#ok<AGROW>

            fprintf( ...
                ['%-8s | SI %.4f | Corr %.4f | ' ...
                 'SSIM %.4f | CNR %.4f | SBR %.3f dB\n'], ...
                method, ...
                M.si_nrmse, ...
                M.correlation, ...
                M.ssim, ...
                M.cnr, ...
                M.sbr_db);
        end

        %% ====================================================
        % CONDITION AUDIT
        % =====================================================

        assert(height(conditionTable)==6);

        assert(all(isfinite(conditionTable.SI_NRMSE)));

        assert(all(isfinite(conditionTable.Correlation)));

        assert(all(isfinite(conditionTable.SSIM)));

        assert(all(isfinite(conditionTable.CNR)));

        assert(all(isfinite(conditionTable.SBR_dB)));

        assert(all( ...
            conditionTable.SI_NRMSE >= 0));

        assert(all( ...
            conditionTable.Correlation >= -1 & ...
            conditionTable.Correlation <= 1));

        %% ====================================================
        % SAVE CONDITION CHECKPOINT
        %
        % Reconstructions are deliberately NOT stored here.
        % Statistical analysis requires the metrics, and selected
        % images can be regenerated later if required.
        % =====================================================

        schemaVersionSaved = ...
            schemaVersion;

        save( ...
            resultFile, ...
            'schemaVersionSaved', ...
            'baseSeed', ...
            'targetSNR', ...
            'achievedSNR', ...
            'conditionTable', ...
            'metricStruct', ...
            'bfInfo', ...
            'trInfo', ...
            '-v7.3');

        writetable( ...
            conditionTable, ...
            csvFile);

        fprintf('\nCondition checkpoint saved.\n');

        %% ====================================================
        % PROGRESS
        % =====================================================

        elapsedStudy = ...
            toc(studyTimer);

        handledConditions = ...
            computedConditions + ...
            reusedConditions;

        meanWallPerCondition = ...
            elapsedStudy / ...
            max(handledConditions,1);

        remainingConditions = ...
            nConditions - ...
            handledConditions;

        estimatedRemainingMinutes = ...
            remainingConditions * ...
            meanWallPerCondition / 60;

        fprintf( ...
            'Approx. remaining time = %.1f min\n', ...
            estimatedRemainingMinutes);
    end
end

%% ============================================================
% GATHER ALL 250 CONDITION TABLES
% ============================================================

fprintf('\n\n');
fprintf('============================================================\n');
fprintf('GATHERING 1500-OUTCOME MASTER TABLE\n');
fprintf('============================================================\n');

masterTable = [];

for q = 1:nSeeds

    baseSeed = ...
        baseSeeds(q);

    for s = 1:nSNR

        targetSNR = ...
            snrLevels_dB(s);

        conditionId = ...
            sprintf( ...
            'seed%03d_snr%02d', ...
            baseSeed, ...
            targetSNR);

        resultFile = fullfile( ...
            conditionDir, ...
            [conditionId '_metrics.mat']);

        assert(isfile(resultFile), ...
            'Missing reconstruction checkpoint: %s', ...
            conditionId);

        S = load( ...
            resultFile, ...
            'schemaVersionSaved', ...
            'conditionTable');

        assert( ...
            string(S.schemaVersionSaved)==schemaVersion);

        assert(height(S.conditionTable)==6);

        masterTable = ...
            [masterTable;S.conditionTable]; %#ok<AGROW>
    end
end

%% ============================================================
% MASTER DIMENSION AUDIT
% ============================================================

assert(height(masterTable)==nExpectedRows);

assert(numel(unique(masterTable.BaseSeed))==50);

assert(numel(unique(masterTable.TargetSNR_dB))==5);

assert(numel(unique(masterTable.Method))==6);

%% ------------------------------------------------------------
% Every seed x SNR block must have exactly six methods.
% ------------------------------------------------------------

for q = 1:nSeeds

    for s = 1:nSNR

        idx = ...
            masterTable.BaseSeed==baseSeeds(q) & ...
            masterTable.TargetSNR_dB==snrLevels_dB(s);

        assert(nnz(idx)==6);
    end
end

%% ------------------------------------------------------------
% Every SNR must contain 50 x 6 = 300 outcomes.
% ------------------------------------------------------------

for s = 1:nSNR

    idx = ...
        masterTable.TargetSNR_dB==snrLevels_dB(s);

    assert(nnz(idx)==300);
end

%% ------------------------------------------------------------
% Every method must contain 50 x 5 = 250 outcomes.
% ------------------------------------------------------------

for m = 1:nMethods

    idx = ...
        masterTable.Method==methods(m);

    assert(nnz(idx)==250);
end

%% ============================================================
% METRIC FINITENESS AUDIT
% ============================================================

metricColumns = { ...
    'SI_NRMSE', ...
    'Correlation', ...
    'SSIM', ...
    'CNR', ...
    'SBR_dB'};

for k = 1:numel(metricColumns)

    values = ...
        masterTable.(metricColumns{k});

    assert(all(isfinite(values)), ...
        'Non-finite values found in %s.', ...
        metricColumns{k});
end

%% ============================================================
% PAIRING / SNR AUDIT
% ============================================================

maxSNRError = ...
    max( ...
    abs( ...
    masterTable.AchievedSNR_dB - ...
    masterTable.TargetSNR_dB));

assert(maxSNRError < 1e-10);

%% ============================================================
% SAVE MASTER TABLE
% ============================================================

masterCsv = fullfile( ...
    mcRoot, ...
    'montecarlo_reconstruction_metrics_1500.csv');

masterMat = fullfile( ...
    mcRoot, ...
    'montecarlo_reconstruction_metrics_1500.mat');

writetable( ...
    masterTable, ...
    masterCsv);

save( ...
    masterMat, ...
    'masterTable', ...
    'schemaVersion', ...
    'baseSeeds', ...
    'snrLevels_dB', ...
    'methods', ...
    '-v7.3');

%% ============================================================
% SIMPLE DESCRIPTIVE SUMMARY
%
% NO inferential statistics here.
% ============================================================

summaryTable = [];

for s = 1:nSNR

    for m = 1:nMethods

        idx = ...
            masterTable.TargetSNR_dB==snrLevels_dB(s) & ...
            masterTable.Method==methods(m);

        X = ...
            masterTable(idx,:);

        newRow = table( ...
            snrLevels_dB(s), ...
            methods(m), ...
            mean(X.SI_NRMSE), ...
            std(X.SI_NRMSE), ...
            mean(X.Correlation), ...
            std(X.Correlation), ...
            mean(X.SSIM), ...
            std(X.SSIM), ...
            mean(X.CNR), ...
            std(X.CNR), ...
            mean(X.SBR_dB), ...
            std(X.SBR_dB), ...
            ...
            'VariableNames',{ ...
            'SNR_dB', ...
            'Method', ...
            'Mean_SI_NRMSE', ...
            'SD_SI_NRMSE', ...
            'Mean_Correlation', ...
            'SD_Correlation', ...
            'Mean_SSIM', ...
            'SD_SSIM', ...
            'Mean_CNR', ...
            'SD_CNR', ...
            'Mean_SBR_dB', ...
            'SD_SBR_dB'});

        summaryTable = ...
            [summaryTable;newRow]; %#ok<AGROW>
    end
end

writetable( ...
    summaryTable, ...
    fullfile( ...
    mcRoot, ...
    'montecarlo_descriptive_summary_30.csv'));

%% ============================================================
% CONSOLE AUDIT
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('EXPANDED MONTE CARLO RECONSTRUCTION AUDIT\n');
fprintf('============================================================\n');

fprintf('Completed RF conditions = %d / %d\n', ...
    nConditions,nConditions);

fprintf('Completed outcomes      = %d / %d\n', ...
    height(masterTable),nExpectedRows);

fprintf('Computed this run       = %d\n', ...
    computedConditions);

fprintf('Reused checkpoints      = %d\n', ...
    reusedConditions);

fprintf('\nMaximum SNR error       = %.12e dB\n', ...
    maxSNRError);

fprintf('\nMetric ranges:\n');

fprintf('SI-NRMSE    %.6f -- %.6f\n', ...
    min(masterTable.SI_NRMSE), ...
    max(masterTable.SI_NRMSE));

fprintf('Correlation %.6f -- %.6f\n', ...
    min(masterTable.Correlation), ...
    max(masterTable.Correlation));

fprintf('SSIM        %.6f -- %.6f\n', ...
    min(masterTable.SSIM), ...
    max(masterTable.SSIM));

fprintf('CNR         %.6f -- %.6f\n', ...
    min(masterTable.CNR), ...
    max(masterTable.CNR));

fprintf('SBR         %.6f -- %.6f dB\n', ...
    min(masterTable.SBR_dB), ...
    max(masterTable.SBR_dB));

fprintf('\nTotal wall time = %.2f min\n', ...
    toc(studyTimer)/60);

fprintf('\nMaster table:\n%s\n', ...
    masterCsv);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 09C COMPLETE: PASS\n');
fprintf('============================================================\n');


%% ============================================================
% LOCAL FUNCTION
% ============================================================

function r = rmsGlobal(x)

    x = double(x);

    r = ...
        sqrt(mean(x(:).^2));

end