clear;
close all;
clc;

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

inputFile = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step08_generalization_reconstruction', ...
    'generalization_reconstruction_metrics_216.csv');

outputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step08_generalization_analysis');

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

assert(isfile(inputFile));

T = readtable( ...
    inputFile, ...
    'TextType','string');

assert(height(T)==216);

%% ============================================================
% DEFINITIONS
% ============================================================

methods = [ ...
    "DAS", ...
    "CF-DAS", ...
    "SCF-DAS", ...
    "DMAS", ...
    "DS-DMAS", ...
    "TR"];

families = [ ...
    "sparse", ...
    "dense", ...
    "cluttered", ...
    "fluence"];

acquisitions = [ ...
    "A1_reference", ...
    "A2_N96", ...
    "A3_fc3MHz"];

metrics = [ ...
    "SI_NRMSE", ...
    "Correlation", ...
    "SSIM", ...
    "CNR", ...
    "SBR_dB", ...
    "CenterlineRecall", ...
    "BranchPointRecovery", ...
    "TerminalBranchRecovery"];

metricLabels = { ...
    'SI-NRMSE', ...
    'Correlation', ...
    'SSIM', ...
    'CNR', ...
    'SBR', ...
    'Centerline recall', ...
    'Branch-point recovery', ...
    'Terminal recovery'};

higherIsBetter = [ ...
    false, ...
    true, ...
    true, ...
    true, ...
    true, ...
    true, ...
    true, ...
    true];

nMethods = numel(methods);
nMetrics = numel(metrics);

%% ============================================================
% REDUNDANCY AUDIT
% ============================================================

continuityDifference = ...
    max(abs( ...
    T.CenterlineRecall - ...
    T.MeanSegmentContinuity));

fprintf('\n');
fprintf('============================================================\n');
fprintf('TASK-METRIC REDUNDANCY AUDIT\n');
fprintf('============================================================\n');

fprintf( ...
    'max |Centerline - MeanContinuity| = %.6e\n', ...
    continuityDifference);

fprintf( ...
    ['MeanSegmentContinuity will not be used as an ' ...
     'independent main-paper metric.\n']);

%% ============================================================
% CONDITION IDs
% ============================================================

conditionKey = ...
    "R" + string(T.Replicate) + ...
    "_" + T.Family + ...
    "_" + T.Acquisition;

uniqueConditions = ...
    unique(conditionKey,'stable');

assert(numel(uniqueConditions)==36);

%% ============================================================
% RANK ALL METHODS WITHIN EVERY CONDITION
% ============================================================

rankRows = [];

for c = 1:numel(uniqueConditions)

    condition = ...
        uniqueConditions(c);

    idxCondition = ...
        conditionKey == condition;

    Tc = T(idxCondition,:);

    assert(height(Tc)==6);

    for q = 1:nMetrics

        metricName = ...
            metrics(q);

        values = ...
            Tc.(metricName);

        ranks = ...
            localRankValues( ...
            values, ...
            higherIsBetter(q));

        bestValue = ...
            localBestValue( ...
            values, ...
            higherIsBetter(q));

        bestMask = ...
            abs(values-bestValue) <= ...
            max(1e-12,1e-10*abs(bestValue));

        for m = 1:height(Tc)

            newRow = table( ...
                condition, ...
                Tc.Replicate(m), ...
                Tc.Family(m), ...
                Tc.Acquisition(m), ...
                Tc.Method(m), ...
                metricName, ...
                values(m), ...
                ranks(m), ...
                bestMask(m), ...
                'VariableNames',{ ...
                'Condition', ...
                'Replicate', ...
                'Family', ...
                'Acquisition', ...
                'Method', ...
                'Metric', ...
                'Value', ...
                'Rank', ...
                'BestOrTiedBest'});

            rankRows = ...
                [rankRows;newRow]; %#ok<AGROW>
        end
    end
end

assert(height(rankRows)== ...
    36*6*nMetrics);

%% ============================================================
% OVERALL RANK SUMMARY
% ============================================================

rankSummary = [];

for q = 1:nMetrics

    for m = 1:nMethods

        idx = ...
            rankRows.Metric == metrics(q) & ...
            rankRows.Method == methods(m);

        R = rankRows(idx,:);

        newRow = table( ...
            metrics(q), ...
            methods(m), ...
            mean(R.Rank), ...
            median(R.Rank), ...
            sum(R.BestOrTiedBest), ...
            mean(R.Value), ...
            std(R.Value), ...
            'VariableNames',{ ...
            'Metric', ...
            'Method', ...
            'MeanRank', ...
            'MedianRank', ...
            'BestOrTiedCount', ...
            'MeanValue', ...
            'SDValue'});

        rankSummary = ...
            [rankSummary;newRow]; %#ok<AGROW>
    end
end

writetable( ...
    rankSummary, ...
    fullfile( ...
    outputDir, ...
    'overall_rank_summary.csv'));

%% ============================================================
% MORPHOLOGY RANK SUMMARY
% ============================================================

familyRanks = [];

for q = 1:nMetrics

    for f = 1:numel(families)

        for m = 1:nMethods

            idx = ...
                rankRows.Metric == metrics(q) & ...
                rankRows.Family == families(f) & ...
                rankRows.Method == methods(m);

            newRow = table( ...
                metrics(q), ...
                families(f), ...
                methods(m), ...
                mean(rankRows.Rank(idx)), ...
                'VariableNames',{ ...
                'Metric', ...
                'Family', ...
                'Method', ...
                'MeanRank'});

            familyRanks = ...
                [familyRanks;newRow]; %#ok<AGROW>
        end
    end
end

writetable( ...
    familyRanks, ...
    fullfile( ...
    outputDir, ...
    'mean_rank_by_morphology.csv'));

%% ============================================================
% ACQUISITION RANK SUMMARY
% ============================================================

acquisitionRanks = [];

for q = 1:nMetrics

    for a = 1:numel(acquisitions)

        for m = 1:nMethods

            idx = ...
                rankRows.Metric == metrics(q) & ...
                rankRows.Acquisition == acquisitions(a) & ...
                rankRows.Method == methods(m);

            newRow = table( ...
                metrics(q), ...
                acquisitions(a), ...
                methods(m), ...
                mean(rankRows.Rank(idx)), ...
                'VariableNames',{ ...
                'Metric', ...
                'Acquisition', ...
                'Method', ...
                'MeanRank'});

            acquisitionRanks = ...
                [acquisitionRanks;newRow]; %#ok<AGROW>
        end
    end
end

writetable( ...
    acquisitionRanks, ...
    fullfile( ...
    outputDir, ...
    'mean_rank_by_acquisition.csv'));

%% ============================================================
% RANK-STABILITY CORRELATIONS
% ============================================================

stabilityRows = [];

for q = 1:nMetrics

    %% --------------------------------------------------------
    % Morphologies
    % ---------------------------------------------------------

    morphologyRankVectors = ...
        zeros(numel(families),nMethods);

    for f = 1:numel(families)

        for m = 1:nMethods

            idx = ...
                familyRanks.Metric == metrics(q) & ...
                familyRanks.Family == families(f) & ...
                familyRanks.Method == methods(m);

            morphologyRankVectors(f,m) = ...
                familyRanks.MeanRank(idx);
        end
    end

    morphCorr = [];

    for i = 1:numel(families)

        for j = i+1:numel(families)

            morphCorr(end+1,1) = ... %#ok<AGROW>
                localSpearman( ...
                morphologyRankVectors(i,:), ...
                morphologyRankVectors(j,:));
        end
    end

    %% --------------------------------------------------------
    % Acquisitions
    % ---------------------------------------------------------

    acquisitionRankVectors = ...
        zeros(numel(acquisitions),nMethods);

    for a = 1:numel(acquisitions)

        for m = 1:nMethods

            idx = ...
                acquisitionRanks.Metric == metrics(q) & ...
                acquisitionRanks.Acquisition == acquisitions(a) & ...
                acquisitionRanks.Method == methods(m);

            acquisitionRankVectors(a,m) = ...
                acquisitionRanks.MeanRank(idx);
        end
    end

    acqCorr = [];

    for i = 1:numel(acquisitions)

        for j = i+1:numel(acquisitions)

            acqCorr(end+1,1) = ... %#ok<AGROW>
                localSpearman( ...
                acquisitionRankVectors(i,:), ...
                acquisitionRankVectors(j,:));
        end
    end

    newRow = table( ...
        metrics(q), ...
        mean(morphCorr), ...
        min(morphCorr), ...
        mean(acqCorr), ...
        min(acqCorr), ...
        'VariableNames',{ ...
        'Metric', ...
        'MeanMorphologySpearman', ...
        'MinimumMorphologySpearman', ...
        'MeanAcquisitionSpearman', ...
        'MinimumAcquisitionSpearman'});

    stabilityRows = ...
        [stabilityRows;newRow]; %#ok<AGROW>
end

writetable( ...
    stabilityRows, ...
    fullfile( ...
    outputDir, ...
    'rank_stability_summary.csv'));

%% ============================================================
% FLUENCE-SPECIFIC SUMMARY
% ============================================================

fluenceRows = [];

TF = T(T.Family=="fluence",:);

for m = 1:nMethods

    idx = TF.Method == methods(m);

    low = ...
        TF.LowFluenceTerminalRecovery(idx);

    high = ...
        TF.HighFluenceTerminalRecovery(idx);

    newRow = table( ...
        methods(m), ...
        mean(low,'omitnan'), ...
        std(low,'omitnan'), ...
        mean(high,'omitnan'), ...
        std(high,'omitnan'), ...
        mean(high-low,'omitnan'), ...
        'VariableNames',{ ...
        'Method', ...
        'LowFluenceMean', ...
        'LowFluenceSD', ...
        'HighFluenceMean', ...
        'HighFluenceSD', ...
        'HighMinusLowMean'});

    fluenceRows = ...
        [fluenceRows;newRow]; %#ok<AGROW>
end

writetable( ...
    fluenceRows, ...
    fullfile( ...
    outputDir, ...
    'fluence_terminal_recovery_summary.csv'));

%% ============================================================
% CLUTTER-SPECIFIC SUMMARY
% ============================================================

clutterRows = [];

TC = T(T.Family=="cluttered",:);

for m = 1:nMethods

    idx = TC.Method == methods(m);

    values = ...
        TC.VesselToClutterRatio_dB(idx);

    newRow = table( ...
        methods(m), ...
        mean(values,'omitnan'), ...
        std(values,'omitnan'), ...
        min(values), ...
        max(values), ...
        'VariableNames',{ ...
        'Method', ...
        'MeanVesselToClutter_dB', ...
        'SDVesselToClutter_dB', ...
        'MinVesselToClutter_dB', ...
        'MaxVesselToClutter_dB'});

    clutterRows = ...
        [clutterRows;newRow]; %#ok<AGROW>
end

writetable( ...
    clutterRows, ...
    fullfile( ...
    outputDir, ...
    'clutter_separation_summary.csv'));

%% ============================================================
% FIGURE 1
% APPLICATION-ORIENTED TASK PERFORMANCE
% ============================================================

fig1 = figure( ...
    'Color','w', ...
    'Position',[40 60 1550 560]);

tl = tiledlayout( ...
    fig1, ...
    1,3, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% ------------------------------------------------------------
% Panel A: terminal recovery by morphology
% ------------------------------------------------------------

ax = nexttile(tl);

terminalMatrix = ...
    zeros(numel(families),nMethods);

for f = 1:numel(families)

    for m = 1:nMethods

        idx = ...
            T.Family == families(f) & ...
            T.Method == methods(m);

        terminalMatrix(f,m) = ...
            mean( ...
            T.TerminalBranchRecovery(idx));
    end
end

bar(ax,terminalMatrix);

grid(ax,'on');
box(ax,'on');

ylim(ax,[0 1.05]);

xticks(ax,1:numel(families));

xticklabels(ax,{ ...
    'Sparse', ...
    'Branching', ...
    '+Clutter', ...
    '+Fluence'});

ylabel(ax,'Terminal-branch recovery');

title(ax, ...
    '(a) Weak-branch preservation');

%% ------------------------------------------------------------
% Panel B: fluence
% ------------------------------------------------------------

ax = nexttile(tl);

fluenceMatrix = [ ...
    fluenceRows.LowFluenceMean, ...
    fluenceRows.HighFluenceMean];

bar(ax,fluenceMatrix);

grid(ax,'on');
box(ax,'on');

ylim(ax,[0 1.05]);

xticks(ax,1:nMethods);
xticklabels(ax,cellstr(methods));
xtickangle(ax,30);

ylabel(ax,'Terminal-branch recovery');

legend(ax, ...
    {'Low fluence','High fluence'}, ...
    'Location','southoutside', ...
    'Orientation','horizontal');

title(ax, ...
    '(b) Fluence-dependent recovery');

%% ------------------------------------------------------------
% Panel C: clutter
% ------------------------------------------------------------

ax = nexttile(tl);

bar(ax, ...
    clutterRows.MeanVesselToClutter_dB);

grid(ax,'on');
box(ax,'on');

xticks(ax,1:nMethods);
xticklabels(ax,cellstr(methods));
xtickangle(ax,30);

ylabel(ax,'Vessel-to-clutter ratio [dB]');

title(ax, ...
    '(c) Clutter rejection');

title( ...
    tl, ...
    'Task-oriented performance across vascular imaging challenges', ...
    'FontSize',16, ...
    'FontWeight','bold');

lgd = legend( ...
    tl.Children(end), ...
    cellstr(methods)); %#ok<NASGU>

exportgraphics( ...
    fig1, ...
    fullfile( ...
    outputDir, ...
    'Fig_R1_1_task_oriented_generalization.png'), ...
    'Resolution',300);

%% ============================================================
% FIGURE 2
% MEAN RANK AND WIN FREQUENCY
% ============================================================

meanRankMatrix = ...
    zeros(nMetrics,nMethods);

bestCountMatrix = ...
    zeros(nMetrics,nMethods);

for q = 1:nMetrics

    for m = 1:nMethods

        idx = ...
            rankSummary.Metric == metrics(q) & ...
            rankSummary.Method == methods(m);

        meanRankMatrix(q,m) = ...
            rankSummary.MeanRank(idx);

        bestCountMatrix(q,m) = ...
            rankSummary.BestOrTiedCount(idx);
    end
end

fig2 = figure( ...
    'Color','w', ...
    'Position',[80 80 1450 680]);

tl2 = tiledlayout( ...
    fig2, ...
    1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% Mean rank
ax = nexttile(tl2);

imagesc(ax,meanRankMatrix);

colorbar(ax);

xticks(ax,1:nMethods);
xticklabels(ax,cellstr(methods));
xtickangle(ax,30);

yticks(ax,1:nMetrics);
yticklabels(ax,metricLabels);

title(ax, ...
    '(a) Mean rank across 36 conditions');

for q = 1:nMetrics

    for m = 1:nMethods

        text( ...
            ax,m,q, ...
            sprintf('%.2f', ...
            meanRankMatrix(q,m)), ...
            'HorizontalAlignment','center', ...
            'FontWeight','bold');
    end
end

%% Best/tied
ax = nexttile(tl2);

imagesc(ax,bestCountMatrix);

colorbar(ax);

xticks(ax,1:nMethods);
xticklabels(ax,cellstr(methods));
xtickangle(ax,30);

yticks(ax,1:nMetrics);
yticklabels(ax,metricLabels);

title(ax, ...
    '(b) Best or tied-best count / 36');

for q = 1:nMetrics

    for m = 1:nMethods

        text( ...
            ax,m,q, ...
            sprintf('%d', ...
            bestCountMatrix(q,m)), ...
            'HorizontalAlignment','center', ...
            'FontWeight','bold');
    end
end

title( ...
    tl2, ...
    'Reconstruction-ranking stability across morphology and acquisition conditions', ...
    'FontSize',16, ...
    'FontWeight','bold');

exportgraphics( ...
    fig2, ...
    fullfile( ...
    outputDir, ...
    'Fig_R2_4_overall_rank_stability.png'), ...
    'Resolution',300);

%% ============================================================
% FIGURE 3
% MORPHOLOGY / ACQUISITION STABILITY
% ============================================================

fig3 = figure( ...
    'Color','w', ...
    'Position',[100 100 1250 560]);

stabilityMatrix = [ ...
    stabilityRows.MeanMorphologySpearman, ...
    stabilityRows.MeanAcquisitionSpearman];

bar(stabilityMatrix);

grid on;
box on;

ylim([-0.3 1.05]);

xticks(1:nMetrics);
xticklabels(metricLabels);
xtickangle(30);

ylabel('Mean pairwise Spearman rank correlation');

legend( ...
    {'Across morphologies', ...
     'Across acquisition configurations'}, ...
    'Location','southoutside', ...
    'Orientation','horizontal');

title( ...
    'Stability of algorithm rankings across morphology and acquisition changes');

yline(0,'-','HandleVisibility','off');

exportgraphics( ...
    fig3, ...
    fullfile( ...
    outputDir, ...
    'Fig_R2_4_rank_correlation_stability.png'), ...
    'Resolution',300);

%% ============================================================
% CONSOLE SUMMARY
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('OVERALL RANK SUMMARY\n');
fprintf('============================================================\n');

disp(rankSummary);

fprintf('\n');
fprintf('============================================================\n');
fprintf('RANK STABILITY\n');
fprintf('============================================================\n');

disp(stabilityRows);

fprintf('\n');
fprintf('============================================================\n');
fprintf('FLUENCE TASK\n');
fprintf('============================================================\n');

disp(fluenceRows);

fprintf('\n');
fprintf('============================================================\n');
fprintf('CLUTTER TASK\n');
fprintf('============================================================\n');

disp(clutterRows);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 08D COMPLETE\n');
fprintf('============================================================\n');

%% ============================================================
% LOCAL FUNCTIONS
% ============================================================

function best = ...
    localBestValue(values,higherIsBetter)

    if higherIsBetter
        best = max(values);
    else
        best = min(values);
    end
end


function ranks = ...
    localRankValues(values,higherIsBetter)

    values = double(values(:));

    if higherIsBetter
        working = -values;
    else
        working = values;
    end

    [sortedValues,order] = ...
        sort(working,'ascend');

    ranks = zeros(size(values));

    i = 1;

    while i <= numel(values)

        j = i;

        tolerance = ...
            max( ...
            1e-12, ...
            1e-10*abs(sortedValues(i)));

        while j < numel(values) && ...
                abs( ...
                sortedValues(j+1)- ...
                sortedValues(i)) <= tolerance

            j = j+1;
        end

        averageRank = ...
            mean(i:j);

        ranks(order(i:j)) = ...
            averageRank;

        i = j+1;
    end
end


function rho = ...
    localSpearman(x,y)

    x = double(x(:));
    y = double(y(:));

    rx = localRankValues(x,false);
    ry = localRankValues(y,false);

    rx = rx-mean(rx);
    ry = ry-mean(ry);

    rho = ...
        dot(rx,ry) / ...
        (norm(rx)*norm(ry)+eps);
end