clear;
close all;
clc;

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

outputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step08_generalization_forward');

mediumDir = ...
    fullfile(outputDir,'media');

if ~exist(mediumDir,'dir')
    mkdir(mediumDir);
end

%% ============================================================
% GRID
% ============================================================

Nx = 192;
Ny = 192;

dx = 50e-6;
dy = 50e-6;

kgrid = ...
    kWaveGrid(Nx,dx,Ny,dy);

%% ============================================================
% THREE MEDIUM STRESS LEVELS
% ============================================================

mediumSeeds = [ ...
    3101, ...
    3202, ...
    3303];

targetCStd = [ ...
    15, ...
    20, ...
    25];

targetRhoStd = [ ...
    10, ...
    15, ...
    20];

nReplicates = 3;

media = cell(nReplicates,1);

summaryRows = [];

%% ============================================================
% GENERATE
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 08B-1: GENERALIZATION MEDIA\n');
fprintf('============================================================\n');

for r = 1:nReplicates

    cfg = struct();

    cfg.randomSeed = ...
        mediumSeeds(r);

    cfg.c0 = 1500;

    cfg.soundSpeedStd = ...
        targetCStd(r);

    cfg.soundSpeedBounds = ...
        [1420 1580];

    cfg.rho0 = 1000;

    cfg.densityStd = ...
        targetRhoStd(r);

    cfg.densityBounds = ...
        [940 1060];

    cfg.nInclusionsRange = ...
        [3 6];

    [medium,meta] = ...
        makeRandomForwardMedium( ...
        kgrid,cfg);

    sound_speed = ...
        medium.sound_speed;

    density = ...
        medium.density;

    fileName = ...
        sprintf( ...
        'medium_R%d_seed%d.mat', ...
        r,mediumSeeds(r));

    filePath = ...
        fullfile( ...
        mediumDir,fileName);

    save( ...
        filePath, ...
        'sound_speed', ...
        'density', ...
        'meta');

    media{r} = struct( ...
        'file',filePath, ...
        'medium',medium, ...
        'meta',meta);

    newRow = table( ...
        r, ...
        mediumSeeds(r), ...
        targetCStd(r), ...
        meta.soundSpeedMean, ...
        meta.soundSpeedStd, ...
        meta.soundSpeedMin, ...
        meta.soundSpeedMax, ...
        targetRhoStd(r), ...
        meta.densityMean, ...
        meta.densityStd, ...
        meta.soundDensityCorrelation, ...
        'VariableNames',{ ...
        'Replicate', ...
        'MediumSeed', ...
        'TargetCStd', ...
        'CMean', ...
        'CStd', ...
        'CMin', ...
        'CMax', ...
        'TargetRhoStd', ...
        'RhoMean', ...
        'RhoStd', ...
        'CorrCRho'});

    summaryRows = ...
        [summaryRows;newRow]; %#ok<AGROW>

    fprintf('\nR%d\n',r);
    fprintf('---------------------------------------------\n');

    fprintf('c mean       = %.3f m/s\n', ...
        meta.soundSpeedMean);

    fprintf('c std        = %.3f m/s\n', ...
        meta.soundSpeedStd);

    fprintf('c range      = %.3f -- %.3f m/s\n', ...
        meta.soundSpeedMin, ...
        meta.soundSpeedMax);

    fprintf('rho mean     = %.3f kg/m^3\n', ...
        meta.densityMean);

    fprintf('rho std      = %.3f kg/m^3\n', ...
        meta.densityStd);

    fprintf('corr(c,rho)  = %.4f\n', ...
        meta.soundDensityCorrelation);

end

%% ============================================================
% COMMON TEMPORAL SAMPLING DESIGN
% ============================================================

cGlobalMax = -inf;

for r = 1:nReplicates

    cCurrent = ...
        max( ...
        double( ...
        media{r}.medium.sound_speed(:)));

    cGlobalMax = ...
        max(cGlobalMax,cCurrent);
end

baseCFL = 0.20;

dtTarget = ...
    baseCFL * min(dx,dy) / ...
    cGlobalMax;

fprintf('\n');
fprintf('============================================================\n');
fprintf('GLOBAL TIME-SAMPLING DESIGN\n');
fprintf('============================================================\n');

fprintf('Global maximum c = %.3f m/s\n', ...
    cGlobalMax);

fprintf('Common target dt = %.9f ns\n', ...
    dtTarget*1e9);

%% ============================================================
% CFL PER REPLICATE
% ============================================================

CFL = zeros(nReplicates,1);

for r = 1:nReplicates

    cMaxR = max( ...
        double( ...
        media{r}.medium.sound_speed(:)));

    CFL(r) = ...
        dtTarget * cMaxR / ...
        min(dx,dy);

    fprintf( ...
        'R%d CFL = %.9f\n', ...
        r,CFL(r));

    assert(CFL(r) <= 0.2000001, ...
        'CFL exceeds design maximum.');
end

%% ============================================================
% SAVE
% ============================================================

writetable( ...
    summaryRows, ...
    fullfile( ...
        outputDir, ...
        'generalization_medium_summary.csv'));

save( ...
    fullfile( ...
        outputDir, ...
        'generalization_medium_design.mat'), ...
    'media', ...
    'summaryRows', ...
    'dtTarget', ...
    'cGlobalMax', ...
    'CFL', ...
    'mediumSeeds', ...
    'targetCStd', ...
    'targetRhoStd', ...
    '-v7.3');

disp(summaryRows);

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 08B-1 COMPLETE\n');
fprintf('============================================================\n');