clear;
close all;
clc;

%% ============================================================
% PATHS
% ============================================================

patboxRoot = ...
    'C:\Users\asus\Documents\GitHub\PATBox';

revisionDir = ...
    fullfile(patboxRoot,'revision');

addpath(patboxRoot,'-begin');
addpath(revisionDir,'-begin');

install_patbox();

inputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step03_sequential_forward');

outputDir = fullfile( ...
    revisionDir, ...
    'outputs', ...
    'step06_sequential_reconstruction');

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

%% ============================================================
% STAGES
% ============================================================

stageFiles = { ...
    'D0_ideal.mat', ...
    'D1_bandwidth.mat', ...
    'D2_finite_aperture.mat', ...
    'D3_heterogeneity.mat', ...
    'D4_attenuation.mat', ...
    'D5_noise.mat'};

stageIds = { ...
    'D0_ideal', ...
    'D1_bandwidth', ...
    'D2_finite_aperture', ...
    'D3_heterogeneity', ...
    'D4_attenuation', ...
    'D5_noise'};

stageLabels = { ...
    'Ideal', ...
    '+ Bandwidth', ...
    '+ Finite aperture', ...
    '+ Heterogeneity', ...
    '+ Attenuation', ...
    '+ Noise'};

nStages = numel(stageFiles);

%% ============================================================
% METHODS
% ============================================================

methodFields = { ...
    'DAS', ...
    'CFDAS', ...
    'SCFDAS', ...
    'DMAS', ...
    'DSDMAS', ...
    'TR'};

methodLabels = { ...
    'DAS', ...
    'CF-DAS', ...
    'SCF-DAS', ...
    'DMAS', ...
    'DS-DMAS', ...
    'TR'};

nMethods = numel(methodFields);

%% ============================================================
% RESULT STORAGE
% ============================================================

template = struct( ...
    'StageIndex',NaN, ...
    'Stage',"", ...
    'StageLabel',"", ...
    'Method',"", ...
    ...
    'Raw_NRMSE',NaN, ...
    'SI_NRMSE',NaN, ...
    'Correlation',NaN, ...
    'SSIM',NaN, ...
    'CNR',NaN, ...
    'SBR_dB',NaN, ...
    ...
    'ScaleFactor',NaN, ...
    'Signal_RMS',NaN, ...
    'Background_RMS',NaN, ...
    'ZeroBackground',false, ...
    ...
    'Runtime_s',NaN, ...
    'RuntimeDefinition',"", ...
    ...
    'ReconSoundSpeedModel',"", ...
    'FiniteApertureTreatment',"");

rows = repmat( ...
    template, ...
    nStages*nMethods, ...
    1);

rowIndex = 0;

%% ============================================================
% CROSS-STAGE AUDIT VARIABLES
% ============================================================

referenceMaster = [];
receiverMaster = [];

dtMaster = NaN;
NtMaster = NaN;

%% ============================================================
% RUN ALL SIX STAGES
% ============================================================

for s = 1:nStages

    fprintf('\n\n');
    fprintf('############################################################\n');
    fprintf('STAGE %d/%d : %s\n', ...
        s,nStages,stageLabels{s});
    fprintf('############################################################\n');

    inputFile = ...
        fullfile(inputDir,stageFiles{s});

    assert(isfile(inputFile), ...
        'Missing stage file: %s',inputFile);

    S = load(inputFile,'sim');

    sim = S.sim;

    %% ---------------------------------------------------------
    % STAGE CONSISTENCY AUDIT
    % ----------------------------------------------------------

    pRef = double(sim.p0_reference);

    receiverPositions = ...
        double(sim.sensor_geometry.positions);

    currentDt = double(sim.kgrid.dt);
    currentNt = double(sim.kgrid.Nt);

    if s == 1

        referenceMaster = pRef;
        receiverMaster = receiverPositions;

        dtMaster = currentDt;
        NtMaster = currentNt;

    else

        refDifference = ...
            norm(pRef(:)-referenceMaster(:)) / ...
            (norm(referenceMaster(:))+eps);

        assert(refDifference < 1e-12, ...
            'Reference phantom changed across physics stages.');

        assert( ...
            isequal(size(receiverPositions), ...
                    size(receiverMaster)), ...
            'Receiver geometry dimensions changed.');

        geometryDifference = ...
            max(abs( ...
            receiverPositions(:)- ...
            receiverMaster(:)));

        assert(geometryDifference < 1e-12, ...
            'Receiver centres changed across stages.');

        assert( ...
            abs(currentDt-dtMaster) < 1e-15, ...
            'dt changed across sequential stages.');

        assert(currentNt == NtMaster, ...
            'Nt changed across sequential stages.');
    end

    fprintf('\nStage audit: PASS\n');

    fprintf('dt           = %.9f ns\n', ...
        currentDt*1e9);

    fprintf('Nt           = %d\n',currentNt);

    fprintf('Receivers    = %d\n', ...
        size(receiverPositions,1));

    %% =========================================================
    % FIVE AUDITED BEAMFORMERS
    % ==========================================================

    [bf,bfInfo] = ...
        publicationBeamformers( ...
        sim, ...
        'SoundSpeed',1500, ...
        'Interpolation','linear', ...
        'CFPower',1.0, ...
        'SCFPower',1.5);

    %% =========================================================
    % AUDITED TIME REVERSAL
    % ==========================================================

    [pTR,trInfo] = ...
        publicationTimeReversal( ...
        sim, ...
        'DataCast','single', ...
        'PMLSize',20, ...
        'PlotSimulation',false);

    %% =========================================================
    % COMBINE RECONSTRUCTIONS
    % ==========================================================

    recons = bf;

    recons.TR = pTR;

    %% =========================================================
    % RUNTIME MAPPING
    % ==========================================================

    runtimeMap = struct();

    runtimeMap.DAS = ...
        bfInfo.total_runtime_DAS_s;

    runtimeMap.CFDAS = ...
        bfInfo.total_runtime_CFDAS_s;

    runtimeMap.SCFDAS = ...
        bfInfo.total_runtime_SCFDAS_s;

    runtimeMap.DMAS = ...
        bfInfo.total_runtime_DMAS_s;

    runtimeMap.DSDMAS = ...
        bfInfo.total_runtime_DSDMAS_s;

    runtimeMap.TR = ...
        trInfo.elapsed_seconds;

    %% =========================================================
    % EVALUATE ALL SIX METHODS
    % ==========================================================

    stageMetrics = struct();

    for m = 1:nMethods

        fieldName = ...
            methodFields{m};

        methodLabel = ...
            methodLabels{m};

        fprintf('\nEvaluating %s...\n', ...
            methodLabel);

        recon = ...
            double(recons.(fieldName));

        assert(all(isfinite(recon(:))), ...
            '%s produced non-finite values.', ...
            methodLabel);

        metric = ...
            publicationEvaluate( ...
            recon, ...
            pRef);

        stageMetrics.(fieldName) = ...
            metric;

        rowIndex = rowIndex + 1;

        rows(rowIndex).StageIndex = s-1;

        rows(rowIndex).Stage = ...
            string(stageIds{s});

        rows(rowIndex).StageLabel = ...
            string(stageLabels{s});

        rows(rowIndex).Method = ...
            string(methodLabel);

        rows(rowIndex).Raw_NRMSE = ...
            metric.raw_nrmse;

        rows(rowIndex).SI_NRMSE = ...
            metric.si_nrmse;

        rows(rowIndex).Correlation = ...
            metric.correlation;

        rows(rowIndex).SSIM = ...
            metric.ssim;

        rows(rowIndex).CNR = ...
            metric.cnr;

        rows(rowIndex).SBR_dB = ...
            metric.sbr_db;

        rows(rowIndex).ScaleFactor = ...
            metric.scale_factor;

        rows(rowIndex).Signal_RMS = ...
            metric.signal_rms;

        rows(rowIndex).Background_RMS = ...
            metric.background_rms;

        rows(rowIndex).ZeroBackground = ...
            metric.sbr_zero_background;

        rows(rowIndex).Runtime_s = ...
            runtimeMap.(fieldName);

        if strcmp(fieldName,'TR')

            rows(rowIndex).RuntimeDefinition = ...
                "actual_TR_wall_time";

            rows(rowIndex).ReconSoundSpeedModel = ...
                "recorded_c_rho_maps";

            if trInfo.equivalent_center_approximation

                rows(rowIndex).FiniteApertureTreatment = ...
                    "equivalent_element_centres";

            else

                rows(rowIndex).FiniteApertureTreatment = ...
                    "point_receiver_coordinates";
            end

        else

            rows(rowIndex).RuntimeDefinition = ...
                "shared_delay_plus_method_weighting";

            rows(rowIndex).ReconSoundSpeedModel = ...
                "scalar_c_1500";

            rows(rowIndex).FiniteApertureTreatment = ...
                "physical_element_centres";
        end

        fprintf( ...
            '%-8s SI-NRMSE %.4f | SSIM %.4f | Corr %.4f | CNR %.4f | SBR %.2f dB\n', ...
            methodLabel, ...
            metric.si_nrmse, ...
            metric.ssim, ...
            metric.correlation, ...
            metric.cnr, ...
            metric.sbr_db);
    end

    %% =========================================================
    % SAVE EACH STAGE SEPARATELY
    % ==========================================================

    stageOutput = struct();

    stageOutput.stageId = stageIds{s};
    stageOutput.stageLabel = stageLabels{s};

    stageOutput.reference = pRef;

    stageOutput.reconstructions = recons;

    stageOutput.metrics = stageMetrics;

    stageOutput.beamformingInfo = bfInfo;
    stageOutput.timeReversalInfo = trInfo;

    save( ...
        fullfile( ...
            outputDir, ...
            sprintf('%s_reconstruction_results.mat', ...
            stageIds{s})), ...
        'stageOutput', ...
        '-v7.3');

end

%% ============================================================
% LONG-FORM RESULT TABLE
% ============================================================

T = struct2table(rows);

assert(height(T)==36, ...
    'Expected exactly 36 reconstruction outcomes.');

assert(all(isfinite(T.SI_NRMSE)), ...
    'Non-finite SI-NRMSE detected.');

assert(all(isfinite(T.Correlation)), ...
    'Non-finite correlation detected.');

assert(all(isfinite(T.SSIM)), ...
    'Non-finite SSIM detected.');

assert(all(isfinite(T.CNR)), ...
    'Non-finite CNR detected.');

assert(all(isfinite(T.SBR_dB)), ...
    'Non-finite SBR detected.');

%% ============================================================
% SAVE CSV
% ============================================================

csvFile = fullfile( ...
    outputDir, ...
    'sequential_reconstruction_metrics.csv');

writetable(T,csvFile);

%% ============================================================
% COMPACT SCIENTIFIC TABLE
% ============================================================

compactTable = T(:,{ ...
    'StageIndex', ...
    'Stage', ...
    'Method', ...
    'SI_NRMSE', ...
    'Correlation', ...
    'SSIM', ...
    'CNR', ...
    'SBR_dB'});

fprintf('\n\n');
fprintf('============================================================\n');
fprintf('FINAL SEQUENTIAL RECONSTRUCTION RESULTS\n');
fprintf('============================================================\n');

disp(compactTable);

%% ============================================================
% ZERO-BACKGROUND AUDIT
% ============================================================

if any(T.ZeroBackground)

    fprintf('\nWARNING:\n');
    fprintf('At least one reconstruction has zero background RMS.\n');

    disp(T( ...
        T.ZeroBackground, ...
        {'Stage','Method','SBR_dB','Background_RMS'}));

else

    fprintf('\nZero-background audit: PASS\n');
end

%% ============================================================
% MODEL-KNOWLEDGE SUMMARY
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('MODEL-KNOWLEDGE POLICY\n');
fprintf('============================================================\n');

fprintf(['DAS/CF-DAS/SCF-DAS/DMAS/DS-DMAS:\n' ...
         '  scalar straight-line c_ref = 1500 m/s\n\n']);

fprintf(['TR:\n' ...
         '  uses recorded c(x,y) and rho(x,y)\n' ...
         '  no attenuation compensation\n' ...
         '  no detector-response deconvolution\n' ...
         '  finite-aperture traces injected at element centres\n']);

%% ============================================================
% SAVE COMPLETE TABLE
% ============================================================

save( ...
    fullfile( ...
        outputDir, ...
        'sequential_reconstruction_metrics.mat'), ...
    'T', ...
    'compactTable');

fprintf('\n');
fprintf('============================================================\n');
fprintf('STEP 06 COMPLETE\n');
fprintf('============================================================\n');

fprintf('\nResults written to:\n%s\n', ...
    outputDir);