function args = benchmarkReconArgs(cfg)
%BENCHMARKRECONARGS Name-value pairs for patReconstruct from benchmark config.

    args = {
        'envelope_signal', coerceLogical(cfg.envelope_signal), ...
        'remove_negatives', coerceLogical(cfg.remove_negatives), ...
        'bandpass_filter', coerceLogical(cfg.bandpass_filter), ...
        'frequency_low', cfg.frequency_low, ...
        'frequency_high', cfg.frequency_high, ...
        'SaveOutput', false, ...
        'SaveMat', false, ...
        'SavePng', false ...
    };
end
