function cfg = loadPatboxYaml(section)
%LOADPATBOXYAML Load PATBox configuration from params.yaml.
%
%   cfg = loadPatboxYaml()              % full config struct
%   cfg = loadPatboxYaml('simulation')  % one section

    cfg_file = fullfile(patboxRoot(), 'params.yaml');
    defaults = defaultPatboxConfig();

    if ~isfile(cfg_file)
        cfg = defaults;
    else
        cfg = parseSectionedYaml(cfg_file);
        cfg = mergePatboxConfig(defaults, cfg);
    end

    if nargin >= 1
        section = matlab.lang.makeValidName(char(section));
        if ~isfield(cfg, section)
            error('PATBox:UnknownSection', 'Unknown params.yaml section: %s', section);
        end
        cfg = cfg.(section);
    end
end

function root = patboxRoot()
    root = fileparts(fileparts(mfilename('fullpath')));
end

function cfg = defaultPatboxConfig()
    cfg.reconstruction = struct( ...
        'AlgorithmName', 'DMAS', ...
        'envelope_signal', false, ...
        'remove_negatives', true, ...
        'bandpass_filter', false, ...
        'frequency_low', 0.1e6, ...
        'frequency_high', 10.0e6, ...
        'SaveOutput', true, ...
        'SaveMat', true, ...
        'SavePng', true, ...
        'OutputDir', 'output/recon', ...
        'OutputSuffix', '', ...
        'iterative', struct( ...
            'interp_method', 'linear', ...
            'InitialGuess', 'DMAS', ...
            'NumIterations', 5, ...
            'StepSize', 0.25, ...
            'UpdateMethod', 'TR'));
    cfg.simulation = struct( ...
        'UseSimulation', true, ...
        'SensorDataPath', '', ...
        'ImagePath', 'data/Example1.bmp', ...
        'RandomSeed', 1, ...
        'GridSize', 512, ...
        'GridSizeX', 512, ...
        'GridSizeY', 520, ...
        'Dx', 0, ...
        'Dy', 0, ...
        'PointsPerWavelength', 4, ...
        'CFL', 0.2, ...
        'SimulationEndTime', 0, ...
        'PMLSize', 20, ...
        'DataCast', 'gpuArray-single', ...
        'PlotSimulation', false, ...
        'SmoothInitialPressure', true, ...
        'MinFrequency', 0, ...
        'MaxFrequency', 5.0e6, ...
        'SourceModel', 'normalized_image', ...
        'SourceMapPath', '', ...
        'InitialPressureVariable', 'p0', ...
        'AbsorptionVariable', 'mu_a', ...
        'FluenceVariable', 'fluence', ...
        'Gruneisen', 0.12, ...
        'SourceScale', 1, ...
        'P0Scale', 2, ...
        'AllowNegativeInitialPressure', false, ...
        'MediumModel', 'homogeneous', ...
        'MediumMapPath', '', ...
        'SoundSpeed', 1500, ...
        'Density', 1000, ...
        'SoundSpeedStd', 20, ...
        'DensityStd', 15, ...
        'CorrelationLength', 1.0e-3, ...
        'AlphaCoeff', 0, ...
        'AlphaPower', 1.5, ...
        'AlphaMode', 'full', ...
        'BonA', 0, ...
        'CouplingLayerThickness', 0, ...
        'CouplingLayerSide', 'xmin', ...
        'CouplingSoundSpeed', 1480, ...
        'CouplingDensity', 1000, ...
        'CouplingAlphaCoeff', 0, ...
        'CouplingBonA', 0, ...
        'SensorType', 'linear', ...
        'SensorModel', 'auto', ...
        'NumTransducers', 128, ...
        'Pitch', 3.0e-4, ...
        'Kerf', 3.0e-5, ...
        'ElementWidth', 2.7e-4, ...
        'ElementIntegrationPoints', 0, ...
        'SensorMargin', 0, ...
        'SensorRadius', 0, ...
        'SensorArcDeg', 180, ...
        'SensorStartAngleDeg', -90, ...
        'SensorRotationDeg', 0, ...
        'ArrayCenterX', 0, ...
        'ArrayCenterY', 0, ...
        'SensorPositionStd', 0, ...
        'SensorRadialPositionStd', 0, ...
        'SensorAngularPositionStdDeg', 0, ...
        'SensorAngleStdDeg', 0, ...
        'ReconstructionGeometryMode', 'calibrated', ...
        'RequireSourceInsideClosedAperture', true, ...
        'SourceSupportThreshold', 1.0e-3, ...
        'UseDirectivity', true, ...
        'DirectivityPattern', 'pressure', ...
        'CenterFrequency', 5.0e6, ...
        'FractionalBandwidthPercent', 80, ...
        'ImpulseResponsePath', '', ...
        'ImpulseResponseVariable', '', ...
        'NoiseLevel', 0.1, ...
        'NoiseModel', 'awgn', ...
        'TargetSNRdB', 20, ...
        'NoiseCalibrationMode', 'target_snr', ...
        'NoiseScale', 1, ...
        'NoiseScaling', 'global', ...
        'NoiseDataPath', '', ...
        'MeasuredNoiseVariable', '', ...
        'MeasuredNoiseSampleRate', 0, ...
        'MeasuredNoiseStartSample', 0, ...
        'MeasuredNoiseDetrend', 'constant', ...
        'MeasuredNoiseAllowTiling', false, ...
        'NoiseColorBeta', 1, ...
        'MeasuredNoiseFraction', 0.7, ...
        'BaselineDriftLevel', 0, ...
        'ImpulseNoiseProbability', 0, ...
        'ImpulseNoiseScale', 10, ...
        'LaserEnergyStd', 0, ...
        'ChannelGainStd', 0, ...
        'TimeJitterStd', 0, ...
        'TriggerJitterStd', 0, ...
        'CrosstalkFraction', 0, ...
        'CrosstalkWrap', false, ...
        'DeadChannelFraction', 0, ...
        'InterferenceFrequenciesHz', [], ...
        'InterferenceRelativeAmplitudes', [], ...
        'ADCBitDepth', 0, ...
        'SaturationLevel', 0);
    cfg.benchmark_algorithms = struct( ...
        'IncludeIterative', true, ...
        'envelope_signal', false, ...
        'remove_negatives', true, ...
        'bandpass_filter', false, ...
        'frequency_low', 0.1e6, ...
        'frequency_high', 10.0e6, ...
        'Algorithms', {{}}, ...
        'Metrics', {{'CompTime', 'RMSE', 'PSNR', 'SSIM', 'SNR', 'Sharpness', 'UIQI', 'CNR', 'SBR'}}, ...
        'OutputPath', 'output/algorithm_benchmark_table.png', ...
        'SaveCsv', true, ...
        'CsvPath', 'output/algorithm_benchmark_table.csv');
    cfg.multi_reconstruction = struct( ...
        'IncludeIterative', false, ...
        'envelope_signal', false, ...
        'remove_negatives', true, ...
        'bandpass_filter', false, ...
        'frequency_low', 0.1e6, ...
        'frequency_high', 10.0e6, ...
        'Algorithms', {{ ...
            'DS-DMAS' ...
            'MV-DAS' ...
            'VDAS' ...
            'SCF-DAS' ...
            'CFMV-DAS' ...
            'FBP' ...
            'UBP' ...
            'DMAS-UBP' ...
            'VDAS-UBP' ...
            'TR'}}, ...
        'OutputDir', 'output/recon', ...
        'OutputSuffix', '', ...
        'SaveFigure', true, ...
        'SaveMat', true, ...
        'SavePng', false);
end

function cfg = mergePatboxConfig(defaults, overrides)
    cfg = defaults;
    sections = intersect(fieldnames(defaults), fieldnames(overrides));
    for i = 1:numel(sections)
        cfg.(sections{i}) = mergeStructFields(defaults.(sections{i}), overrides.(sections{i}));
    end
end

function out = mergeStructFields(defaults, overrides)
    out = defaults;
    keys = fieldnames(overrides);
    for i = 1:numel(keys)
        key = keys{i};
        if ~isfield(defaults, key)
            out.(key) = overrides.(key);
            continue;
        end
        if isstruct(defaults.(key)) && isstruct(overrides.(key))
            out.(key) = mergeStructFields(defaults.(key), overrides.(key));
        else
            out.(key) = overrides.(key);
        end
    end
end

function cfg = parseSectionedYaml(cfg_file)
    cfg = defaultPatboxConfig();
    current_section = '';
    current_subsection = '';
    list_key = '';
    lines = split(string(fileread(cfg_file)), newline);

    for i = 1:numel(lines)
        raw_line = stripInlineYamlComment(char(lines(i)));
        line = strtrim(raw_line);
        if line == "" || startsWith(line, "#")
            continue;
        end

        if startsWith(line, "- ")
            item = char(strtrim(extractAfter(line, 2)));
            if strcmp(current_section, 'benchmark_algorithms') && ~isempty(list_key)
                cfg.benchmark_algorithms.(list_key){end + 1} = parseYamlValue(item); %#ok<AGROW>
            elseif strcmp(current_section, 'multi_reconstruction') && ~isempty(list_key)
                cfg.multi_reconstruction.(list_key){end + 1} = parseYamlValue(item); %#ok<AGROW>
            end
            continue;
        end

        if endsWith(line, ":") && ~contains(strtrim(extractBefore(line, ":")), " ")
            section_name = char(strtrim(extractBefore(line, ":")));
            if startsWith(raw_line, "  ") && strcmp(current_section, 'reconstruction') && ...
                    strcmp(section_name, 'iterative')
                current_subsection = 'iterative';
                list_key = '';
                continue;
            end
            if isTopLevelYamlLine(raw_line)
                current_section = section_name;
                current_subsection = '';
                list_key = '';
                continue;
            end
        end

        parts_key = '';
        parts_value = '';
        colon = find(line == ':', 1, 'first');
        if isempty(colon)
            continue;
        end
        parts_key = strtrim(line(1:colon-1));
        parts_value = strtrim(line(colon+1:end));
        if isempty(parts_key)
            continue;
        end

        key = char(matlab.lang.makeValidName(parts_key));
        if ~isvarname(key)
            continue;
        end
        raw_value = parts_value;
        if isempty(raw_value)
            if strcmp(current_section, 'benchmark_algorithms')
                list_key = key;
                cfg.benchmark_algorithms.(list_key) = {};
            elseif strcmp(current_section, 'multi_reconstruction')
                list_key = key;
                cfg.multi_reconstruction.(list_key) = {};
            end
            continue;
        end
        value = parseYamlValue(raw_value);

        if strcmp(current_section, 'reconstruction') && strcmp(current_subsection, 'iterative')
            cfg.reconstruction.iterative.(key) = value;
        elseif strcmp(current_section, 'reconstruction')
            cfg.reconstruction.(key) = value;
        elseif strcmp(current_section, 'simulation')
            cfg.simulation.(key) = value;
        elseif strcmp(current_section, 'benchmark_algorithms')
            cfg.benchmark_algorithms.(key) = value;
            list_key = '';
        elseif strcmp(current_section, 'multi_reconstruction')
            cfg.multi_reconstruction.(key) = value;
            list_key = '';
        end
    end
end

function tf = isTopLevelYamlLine(raw_line)
    tf = ~startsWith(raw_line, " ") && ~startsWith(raw_line, sprintf('\t'));
end

function text = stripInlineYamlComment(text)
    % Strip unquoted trailing comments so "linear # options" -> "linear".
    inSingle = false;
    inDouble = false;
    for i = 1:numel(text)
        ch = text(i);
        if ch == "'" && ~inDouble
            inSingle = ~inSingle;
        elseif ch == '"' && ~inSingle
            inDouble = ~inDouble;
        elseif ch == '#' && ~inSingle && ~inDouble
            text = text(1:i-1);
            return;
        end
    end
end

function value = parseYamlValue(raw_value)
    raw_value = char(raw_value);

    if strcmpi(raw_value, 'true')
        value = true;
    elseif strcmpi(raw_value, 'false')
        value = false;
    elseif strcmpi(raw_value, 'null') || strcmp(raw_value, '~')
        value = [];
    elseif strcmp(raw_value, '[]')
        value = [];
    elseif startsWith(raw_value, '[') && endsWith(raw_value, ']')
        body = strtrim(raw_value(2:end-1));
        if isempty(body)
            value = [];
        else
            tokens = strsplit(body, ',');
            value = cellfun(@(x) parseYamlValue(strtrim(x)), tokens, 'UniformOutput', false);
            nums = cellfun(@(x) isnumeric(x) && isscalar(x), value);
            if all(nums)
                value = cell2mat(value);
            end
        end
    elseif (startsWith(raw_value, '"') && endsWith(raw_value, '"')) || ...
            (startsWith(raw_value, '''') && endsWith(raw_value, ''''))
        value = char(raw_value(2:end - 1));
    elseif strcmp(raw_value, '""') || strcmp(raw_value, "''")
        value = '';
    elseif ~isnan(str2double(raw_value))
        value = str2double(raw_value);
    else
        value = raw_value;
    end
end
