function stages = sequentialPhysicsStages(overrides)
%SEQUENTIALPHYSICSSTAGES Cumulative PAT forward-model degradation stages.
%
%   stages = sequentialPhysicsStages()
%   stages = sequentialPhysicsStages(struct('TargetSNRdB', 15))
%
% Each stage is the previous stage plus one impairment. Order:
%   1) ideal
%   2) + bandwidth limit
%   3) + limited aperture
%   4) + heterogeneous medium
%   5) + attenuation (AlphaCoeff, AlphaPower = 1, AlphaMode = no_dispersion)
%   6) + power-law absorption (AlphaPower = 1.5, AlphaMode = full)
%   7) + measurement noise
%
% overrides may replace numeric/string fields used by later stages
% (for example FractionalBandwidthPercent, SensorArcDeg, TargetSNRdB).

    if nargin < 1 || isempty(overrides)
        overrides = struct();
    end

    bwPct = getOverride(overrides, 'FractionalBandwidthPercent', 80);
    centerHz = getOverride(overrides, 'CenterFrequency', 5.0e6);
    arcDeg = getOverride(overrides, 'SensorArcDeg', 180);
    alphaCoeff = getOverride(overrides, 'AlphaCoeff', 0.75);
    alphaPower = getOverride(overrides, 'AlphaPower', 1.5);
    targetSnr = getOverride(overrides, 'TargetSNRdB', 20);
    soundStd = getOverride(overrides, 'SoundSpeedStd', 20);
    densStd = getOverride(overrides, 'DensityStd', 15);

    % Ideal closed-aperture circular acquisition: no BW filter, homogeneous,
    % lossless medium, noiseless receive chain.
    base = { ...
        'SensorType', 'circular', ...
        'SensorArcDeg', 360, ...
        'FractionalBandwidthPercent', 0, ...
        'CenterFrequency', centerHz, ...
        'MediumModel', 'homogeneous', ...
        'AlphaCoeff', 0, ...
        'AlphaPower', 1.5, ...
        'AlphaMode', 'full', ...
        'NoiseModel', 'none', ...
        'TargetSNRdB', targetSnr, ...
        'SoundSpeedStd', soundStd, ...
        'DensityStd', densStd ...
        };

    stages = { ...
        stageSpec(1, 'ideal', 'Ideal closed aperture', base), ...
        stageSpec(2, 'bw', 'Ideal + bandwidth limit', [base, { ...
            'FractionalBandwidthPercent', bwPct}]), ...
        stageSpec(3, 'bw_aperture', 'BW + limited aperture', [base, { ...
            'FractionalBandwidthPercent', bwPct, ...
            'SensorType', 'arc', ...
            'SensorArcDeg', arcDeg}]), ...
        stageSpec(4, 'bw_aperture_hetero', 'BW + aperture + heterogeneous', [base, { ...
            'FractionalBandwidthPercent', bwPct, ...
            'SensorType', 'arc', ...
            'SensorArcDeg', arcDeg, ...
            'MediumModel', 'gaussian'}]), ...
        stageSpec(5, 'bw_aperture_hetero_att', ...
            'Previous + attenuation (no dispersion)', [base, { ...
            'FractionalBandwidthPercent', bwPct, ...
            'SensorType', 'arc', ...
            'SensorArcDeg', arcDeg, ...
            'MediumModel', 'gaussian', ...
            'AlphaCoeff', alphaCoeff, ...
            'AlphaPower', 1.0, ...
            'AlphaMode', 'no_dispersion'}]), ...
        stageSpec(6, 'bw_aperture_hetero_att_pl', ...
            'Previous + power-law absorption', [base, { ...
            'FractionalBandwidthPercent', bwPct, ...
            'SensorType', 'arc', ...
            'SensorArcDeg', arcDeg, ...
            'MediumModel', 'gaussian', ...
            'AlphaCoeff', alphaCoeff, ...
            'AlphaPower', alphaPower, ...
            'AlphaMode', 'full'}]), ...
        stageSpec(7, 'bw_aperture_hetero_att_pl_noise', ...
            'Previous + AWGN', [base, { ...
            'FractionalBandwidthPercent', bwPct, ...
            'SensorType', 'arc', ...
            'SensorArcDeg', arcDeg, ...
            'MediumModel', 'gaussian', ...
            'AlphaCoeff', alphaCoeff, ...
            'AlphaPower', alphaPower, ...
            'AlphaMode', 'full', ...
            'NoiseModel', 'awgn', ...
            'TargetSNRdB', targetSnr}]) ...
        };
end

function stage = stageSpec(index, id, label, simArgs)
    stage = struct( ...
        'Index', index, ...
        'Id', char(id), ...
        'Label', char(label), ...
        'SimArgs', {simArgs});
end

function value = getOverride(overrides, name, defaultValue)
    if isstruct(overrides) && isfield(overrides, name) && ~isempty(overrides.(name))
        value = overrides.(name);
    else
        value = defaultValue;
    end
end
